import type { RequestHandler } from 'express';
import { hasAnyPermission, hasPermission, Permission, Role } from '@mym/shared';
import { User } from '../modules/users/user.model';
import { ApiError } from './errorHandler';
import { verifyAccessToken } from '../utils/tokens';

export const requireAuth: RequestHandler = async (request, _response, next) => { try { const token = request.cookies.accessToken; if (!token) throw new ApiError(401, 'UNAUTHENTICATED'); const payload = verifyAccessToken(token); const user: any = await User.findOne({ _id: payload.sub, active: true, deletedAt: null }).lean(); if (!user) throw new ApiError(401, 'UNAUTHENTICATED'); request.user = { id: user._id.toString(), roles: user.roles, permissionOverrides: user.permissionOverrides ?? [], permissionDeniedOverrides: user.permissionDeniedOverrides ?? [], salonIds: (user.salonIds ?? []).map(String), managedSalonIds: (user.managedSalonIds ?? []).map(String), active: user.active }; next(); } catch { next(new ApiError(401, 'UNAUTHENTICATED')); } };
export const requirePermission = (permission: Permission): RequestHandler => (request, _response, next) => { const allowed = request.user?.roles.some((role) => hasPermission(role, permission, request.user?.permissionOverrides, request.user?.permissionDeniedOverrides)); if (!allowed) return next(new ApiError(403, 'FORBIDDEN')); next(); };
export const requireAnyPermission = (permissions: Permission[]): RequestHandler => (request, _response, next) => { const allowed = request.user?.roles.some((role) => hasAnyPermission(role, permissions, request.user?.permissionOverrides, request.user?.permissionDeniedOverrides)); if (!allowed) return next(new ApiError(403, 'FORBIDDEN')); next(); };
export const requireRole = (...roles: Role[]): RequestHandler => (request, _response, next) => request.user?.roles.some((role) => roles.includes(role)) ? next() : next(new ApiError(403, 'FORBIDDEN'));
export function canAccessSalon(user: NonNullable<Express.Request['user']>, salonId: string): boolean { return user.roles.includes(Role.ADMIN) || user.salonIds.includes(salonId) || user.roles.some((role) => hasPermission(role, Permission.SALONS_READ, user.permissionOverrides)); }
export const requireSalonScope = (source: 'params' | 'body' | 'query' = 'params', key = 'salonId'): RequestHandler => (request, _response, next) => { const salonId = String(request[source][key] ?? ''); if (!request.user || !salonId || !canAccessSalon(request.user, salonId)) return next(new ApiError(403, 'SALON_SCOPE_FORBIDDEN')); next(); };
