export enum Role {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  SALON_MANAGER = 'SALON_MANAGER',
  STAFF = 'STAFF',
}

export enum StaffSubrole {
  WAITER = 'WAITER',
  MAITRE = 'MAITRE',
  COOK = 'COOK',
  KITCHEN_ASSISTANT = 'KITCHEN_ASSISTANT',
  BARTENDER = 'BARTENDER',
  DJ = 'DJ',
  DECORATION = 'DECORATION',
  CLEANING = 'CLEANING',
  SECURITY = 'SECURITY',
  COORDINATOR = 'COORDINATOR',
  RECEPTION = 'RECEPTION',
  OTHER = 'OTHER',
}

export enum StaffEmploymentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
}
