export enum Role {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  SALON_MANAGER = 'SALON_MANAGER',
  STAFF = 'STAFF',
  ACCOUNTING = 'ACCOUNTING',
  OPERATIONS = 'OPERATIONS',
  SALES = 'SALES',
  VALIDATOR = 'VALIDATOR'
}
