'use client';
/* eslint-disable react-hooks/set-state-in-effect */

import { ChangeEvent, useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Download, FileSpreadsheet, LoaderCircle, Upload, XCircle } from 'lucide-react';
import { Permission } from '@mym/shared';
import { useSession } from '@/components/session-provider';
import { Button, PageHeader, Select } from '@/components/ui/primitives';
import { api } from '@/lib/api';
import { userCanAccess } from '@/lib/admin-permissions';
import { useToast } from '@/components/ui/toast-provider';

type ImportType = 'contracts' | 'production' | 'expenses';
type Job = {
  _id: string; type: ImportType; originalFileName: string; status: string; totalRows: number; validRows: number; errorRows: number;
  duplicateRows: number; importedRows: number; skippedRows: number; headers: string[]; previewRows: Array<{ rowNumber: number; values: Record<string, string>; errors: string[] }>;
  createdAt: string; executedAt?: string;
};
type UploadResponse = { import: Job; headers: string[]; suggestedMapping: Record<string, string>; fields: { required: string[]; optional: string[] } };
type ErrorRow = { _id: string; rowNumber: number; code: string; message: string; sourceRow?: Record<string, string> };
const typeLabels: Record<ImportType, string> = { contracts: 'Contratos', production: 'Producción', expenses: 'Gastos' };
const statusLabels: Record<string, string> = { uploaded: 'Archivo cargado', validated: 'Validado', executing: 'Importando', completed: 'Completado', completed_with_errors: 'Completado con errores', failed: 'Fallido' };
const dateTime = new Intl.DateTimeFormat('es-AR', { timeZone: 'America/Argentina/Buenos_Aires', dateStyle: 'short', timeStyle: 'short' });

export function ImportsWorkspace() {
  const { user } = useSession(); const { showToast } = useToast();
  const [type, setType] = useState<ImportType>('expenses'); const [job, setJob] = useState<Job | null>(null); const [fields, setFields] = useState<{ required: string[]; optional: string[] }>({ required: [], optional: [] }); const [mapping, setMapping] = useState<Record<string, string>>({}); const [history, setHistory] = useState<Job[]>([]); const [errors, setErrors] = useState<ErrorRow[]>([]); const [busy, setBusy] = useState('');
  const canCreate = userCanAccess(user, [Permission.IMPORTS_CREATE]); const canExecute = userCanAccess(user, [Permission.IMPORTS_EXECUTE]);
  const loadHistory = useCallback(async () => { try { setHistory((await api.get<{ items: Job[] }>('/imports')).items); } catch { setHistory([]); } }, []);
  useEffect(() => { void loadHistory(); }, [loadHistory]);
  const template = async () => { try { const result = await api.download(`/imports/template/${type}`); const url = URL.createObjectURL(result.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = result.filename; anchor.click(); URL.revokeObjectURL(url); } catch (cause) { showToast({ message: cause instanceof Error ? cause.message : 'No se pudo descargar.', variant: 'error' }); } };
  const upload = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; if (!file) return; setBusy('upload');
    const body = new FormData(); body.append('type', type); body.append('file', file);
    try { const result = await api.post<UploadResponse>('/imports/preview', body); setJob(result.import); setFields(result.fields); setMapping(result.suggestedMapping); setErrors([]); showToast({ message: 'Archivo leído. Revisá el mapeo antes de validar.', variant: 'success' }); }
    catch (cause) { showToast({ message: cause instanceof Error ? cause.message : 'No se pudo leer el archivo.', variant: 'error' }); } finally { setBusy(''); event.target.value = ''; }
  };
  const validate = async () => {
    if (!job) return; setBusy('validate'); const body = new FormData(); body.append('importId', job._id); body.append('mapping', JSON.stringify(mapping));
    try { const result = await api.post<{ import: Job }>('/imports/preview', body); setJob(result.import); setErrors((await api.get<{ items: ErrorRow[] }>(`/imports/${job._id}/errors`)).items); showToast({ message: result.import.errorRows ? 'Validación finalizada con observaciones.' : 'Todas las filas son válidas.', variant: result.import.errorRows ? 'error' : 'success' }); }
    catch (cause) { showToast({ message: cause instanceof Error ? cause.message : 'No se pudo validar.', variant: 'error' }); } finally { setBusy(''); }
  };
  const execute = async () => {
    if (!job || !confirm(`Se importarán ${job.validRows} filas válidas. ¿Continuar?`)) return; setBusy('execute');
    try { const result = await api.post<{ import: Job; idempotent: boolean }>('/imports/execute', { importId: job._id }); setJob(result.import); setErrors((await api.get<{ items: ErrorRow[] }>(`/imports/${job._id}/errors`)).items); await loadHistory(); showToast({ message: result.idempotent ? 'La importación ya se había ejecutado; no se duplicó información.' : 'Importación finalizada.', variant: 'success' }); }
    catch (cause) { showToast({ message: cause instanceof Error ? cause.message : 'No se pudo ejecutar.', variant: 'error' }); } finally { setBusy(''); }
  };
  const reset = () => { setJob(null); setMapping({}); setFields({ required: [], optional: [] }); setErrors([]); };
  const targetFields = [...fields.required, ...fields.optional];
  return <section className="space-y-6"><PageHeader title="Importaciones controladas" description="Excel normalizado con mapeo, previsualización, validación, idempotencia y auditoría. Ninguna fila se importa al cargar el archivo." />
    {canCreate ? <article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-end gap-3"><label className="min-w-56 text-sm font-medium">Tipo de datos<Select className="mt-1.5" value={type} disabled={Boolean(job)} onChange={(event) => { setType(event.target.value as ImportType); reset(); }}>{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label><Button variant="secondary" onClick={() => void template()}><Download className="mr-2 h-4 w-4" />Descargar plantilla</Button>{!job ? <label className="inline-flex cursor-pointer items-center rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-medium text-white"><Upload className="mr-2 h-4 w-4" />{busy === 'upload' ? 'Leyendo…' : 'Seleccionar .xlsx'}<input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="hidden" disabled={Boolean(busy)} onChange={(event) => void upload(event)} /></label> : <Button variant="secondary" onClick={reset}>Nueva importación</Button>}</div><p className="mt-3 text-xs leading-5 text-zinc-500">Máximo 5 MB y 5.000 filas. Los archivos históricos irregulares deben normalizarse o migrarse mediante un script específico revisado previamente.</p></article> : null}
    {job ? <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Filas', job.totalRows], ['Válidas', job.validRows], ['Con error', job.errorRows], ['Duplicadas', job.duplicateRows], ['Importadas', job.importedRows]].map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></article>)}</div>
      {job.status === 'uploaded' ? <article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Mapeo de columnas</h2><p className="mt-1 text-sm text-zinc-500">Confirmá qué columna del archivo corresponde a cada campo del sistema.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{targetFields.map((field) => <label key={field} className="text-sm font-medium">{field}{fields.required.includes(field) ? <span className="text-red-600"> *</span> : null}<Select className="mt-1.5" value={mapping[field] || ''} onChange={(event) => setMapping((current) => ({ ...current, [field]: event.target.value }))}><option value="">No mapear</option>{job.headers.map((header) => <option key={header} value={header}>{header}</option>)}</Select></label>)}</div><footer className="mt-5 flex justify-end"><Button disabled={Boolean(busy) || fields.required.some((field) => !mapping[field])} onClick={() => void validate()}>{busy === 'validate' ? 'Validando…' : 'Validar y previsualizar'}</Button></footer></article> : null}
      {job.previewRows?.length ? <article className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><header className="flex items-center justify-between border-b border-zinc-100 px-5 py-4"><div><h2 className="font-semibold">Previsualización</h2><p className="text-xs text-zinc-500">Primeras {job.previewRows.length} filas; la validación abarca todo el archivo.</p></div>{job.errorRows ? <XCircle className="h-5 w-5 text-red-500" /> : <CheckCircle2 className="h-5 w-5 text-emerald-500" />}</header><div className="overflow-x-auto"><table className="min-w-max w-full text-xs"><thead className="bg-zinc-50"><tr><th className="px-3 py-2 text-left">Fila</th>{targetFields.filter((field) => mapping[field]).map((field) => <th key={field} className="px-3 py-2 text-left">{field}</th>)}<th className="px-3 py-2 text-left">Validación</th></tr></thead><tbody className="divide-y divide-zinc-100">{job.previewRows.map((row) => <tr key={row.rowNumber} className={row.errors.length ? 'bg-red-50/50' : ''}><td className="px-3 py-2">{row.rowNumber}</td>{targetFields.filter((field) => mapping[field]).map((field) => <td key={field} className="max-w-52 truncate px-3 py-2">{row.values[field] || '—'}</td>)}<td className="px-3 py-2">{row.errors.length ? <span className="text-red-700">{row.errors.join(' ')}</span> : <span className="text-emerald-700">Válida</span>}</td></tr>)}</tbody></table></div>{job.status === 'validated' ? <footer className="flex items-center justify-between border-t border-zinc-100 p-4"><p className="text-sm text-zinc-500">Las filas inválidas se omitirán y quedarán en el informe.</p>{canExecute ? <Button disabled={!job.validRows || Boolean(busy)} onClick={() => void execute()}>{busy === 'execute' ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <FileSpreadsheet className="mr-2 h-4 w-4" />}Confirmar e importar</Button> : null}</footer> : null}</article> : null}
      {errors.length ? <article className="rounded-2xl border border-red-200 bg-red-50 p-5"><h2 className="font-semibold text-red-900">Informe de errores</h2><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{errors.map((error) => <p key={error._id} className="text-sm text-red-800"><strong>Fila {error.rowNumber}:</strong> {error.message}</p>)}</div></article> : null}</> : null}
    <article className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><header className="border-b border-zinc-100 px-5 py-4"><h2 className="font-semibold">Historial</h2></header><div className="overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead className="bg-zinc-50"><tr>{['Fecha', 'Archivo', 'Tipo', 'Estado', 'Filas', 'Importadas', 'Omitidas', 'Errores'].map((label) => <th key={label} className="px-4 py-3 text-left text-xs font-semibold uppercase text-zinc-500">{label}</th>)}</tr></thead><tbody className="divide-y divide-zinc-100">{history.map((item) => <tr key={item._id}><td className="px-4 py-3">{dateTime.format(new Date(item.createdAt))}</td><td className="px-4 py-3 font-medium">{item.originalFileName}</td><td className="px-4 py-3">{typeLabels[item.type]}</td><td className="px-4 py-3">{statusLabels[item.status] || item.status}</td><td className="px-4 py-3">{item.totalRows}</td><td className="px-4 py-3">{item.importedRows}</td><td className="px-4 py-3">{item.skippedRows}</td><td className="px-4 py-3">{item.errorRows}</td></tr>)}</tbody></table>{!history.length ? <p className="p-8 text-center text-sm text-zinc-500">No hay importaciones anteriores.</p> : null}</div></article>
  </section>;
}
