'use client';
/* eslint-disable react-hooks/set-state-in-effect */

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Calculator, CheckCircle2, UserRound } from 'lucide-react';
import { api } from '@/lib/api';
import { Button, Input, Modal, Select, Textarea } from '@/components/ui/primitives';
import { useToast } from '@/components/ui/toast-provider';
import { cleanMenuSections, cleanStringList, MenuSectionsEditor, StringListEditor } from '@/components/admin/structured-list-editors';
import type { Customer, LeadOption, PackageTemplate, Quote, QuoteRequest, Salon } from './types';

type CommercialValues = { durationHours: number; startTime: string; endTime: string; pricingMode: 'per_person' | 'fixed'; pricePerPerson: number; fixedPrice: number; discountPercentage: number; depositAmount: number; paymentTerms: string; promotionText: string; giftText: string; notes: string; menuSections: { title: string; items: string[] }[]; includedServices: string[] };
type CommercialSource = Partial<Omit<CommercialValues, 'menuSections'> & { menuSections: { title?: string; name?: string; items: string[] }[] }>;
type RulePackage = PackageTemplate & { ruleConfigured?: boolean };
type QuoteFormModalProps = { open: boolean; quote?: Quote; quoteRequest?: QuoteRequest; initialCustomerId?: string; salons: Salon[]; leads: LeadOption[]; customers?: Customer[]; packages: PackageTemplate[]; saving: boolean; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => Promise<void> };
const dateValue = (value?: string) => value?.slice(0, 10) ?? '';
const leadName = (lead?: LeadOption) => lead?.fullName || [lead?.firstName, lead?.lastName].filter(Boolean).join(' ') || 'Lead sin nombre';
const customerName = (customer?: Customer) => customer?.fullName || [customer?.firstName, customer?.lastName].filter(Boolean).join(' ') || 'Cliente sin nombre';
const money = (value: number) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(value);
const asCommercial = (source?: CommercialSource): CommercialValues => ({ durationHours: source?.durationHours ?? 0, startTime: source?.startTime ?? '', endTime: source?.endTime ?? '', pricingMode: source?.pricingMode === 'fixed' ? 'fixed' : 'per_person', pricePerPerson: source?.pricePerPerson ?? 0, fixedPrice: source?.fixedPrice ?? 0, discountPercentage: source?.discountPercentage ?? 0, depositAmount: source?.depositAmount ?? 0, paymentTerms: source?.paymentTerms ?? '', promotionText: source?.promotionText ?? '', giftText: source?.giftText ?? '', notes: source?.notes ?? '', menuSections: (source?.menuSections ?? []).map((section) => ({ title: section.title ?? section.name ?? 'Menú', items: section.items })), includedServices: source?.includedServices ?? [] });

export function QuoteFormModal({ open, quote, quoteRequest, initialCustomerId, salons, leads, customers = [], packages: initialPackages, saving, onClose, onSubmit }: QuoteFormModalProps) {
  const { showToast } = useToast();
  const [selectedLeadId, setSelectedLeadId] = useState(''); const [selectedCustomerId, setSelectedCustomerId] = useState(''); const [targetMode, setTargetMode] = useState<'search' | 'new'>('search'); const [selectedSalonIds, setSelectedSalonIds] = useState<string[]>([]); const [selectedPackageId, setSelectedPackageId] = useState(''); const [manualMode, setManualMode] = useState(false); const [guestCount, setGuestCount] = useState(0);
  const [packages, setPackages] = useState(initialPackages); const [rules, setRules] = useState<Record<string, RulePackage>>({}); const [commercial, setCommercial] = useState<CommercialValues>(asCommercial()); const [commercialDirty, setCommercialDirty] = useState(false);
  const setNotice = (message: string) => { if (message) showToast({ message, variant: 'error' }); };

  useEffect(() => { if (!open) return; void api.get<{ packages?: PackageTemplate[] }>('/quotes/packages').then((response) => setPackages(response.packages ?? [])).catch((error: Error) => setNotice(`No se pudieron cargar las plantillas: ${error.message}`)); }, [open]);
  useEffect(() => { const source = quote; const request = quoteRequest; const leadId = typeof source?.leadId === 'string' ? source.leadId : source?.leadId?._id ?? (typeof request?.leadId === 'string' ? request.leadId : request?.leadId?._id ?? ''); const customerId = typeof source?.customerId === 'string' ? source.customerId : source?.customerId?._id ?? (typeof request?.customerId === 'string' ? request.customerId : request?.customerId?._id ?? initialCustomerId ?? ''); const requestedPackageId = typeof request?.interestedPackageTemplateId === 'string' ? request.interestedPackageTemplateId : request?.interestedPackageTemplateId?._id ?? ''; setSelectedLeadId(leadId); setSelectedCustomerId(customerId); setTargetMode(!source && !request && !leadId && !customerId ? 'new' : 'search'); setSelectedSalonIds(source ? [typeof source.salonId === 'string' ? source.salonId : source.salonId._id] : (request?.interestedSalonIds ?? []).map((salon) => typeof salon === 'string' ? salon : salon._id)); setSelectedPackageId(typeof source?.packageTemplateId === 'string' ? source.packageTemplateId : source?.packageTemplateId?._id ?? requestedPackageId); setManualMode(Boolean(source && !source.packageTemplateId)); setGuestCount(source?.guestCount ?? request?.guestCount ?? 0); setCommercial(asCommercial(source ? source : request?.message ? { notes: request.message } : undefined)); setCommercialDirty(Boolean(source || request?.message)); setRules({}); setNotice(''); }, [quote, quoteRequest, initialCustomerId, open]);

  const selectedPackage = useMemo(() => packages.find((item) => item._id === selectedPackageId), [packages, selectedPackageId]);
  useEffect(() => { if (!selectedPackageId || !selectedSalonIds.length || manualMode) return; let cancelled = false; void Promise.all(selectedSalonIds.map(async (salonId) => { try { const response = await api.get<{ package: RulePackage }>(`/quotes/packages/${selectedPackageId}/salons/${salonId}`); return [salonId, response.package] as const; } catch { return [salonId, { ...selectedPackage, ruleConfigured: false }] as const; } })).then((items) => { if (cancelled) return; const next = Object.fromEntries(items); setRules(next); const first = items.find(([, item]) => item.ruleConfigured)?.[1]; if (first && !quote) { setCommercial(asCommercial(first)); setCommercialDirty(false); } }).catch(() => { if (!cancelled) setNotice('No se pudieron cargar las reglas comerciales por salón.'); }); return () => { cancelled = true; }; }, [selectedPackageId, selectedSalonIds, manualMode, selectedPackage, quote]);

  const finalPrice = Math.round((commercial.pricingMode === 'fixed' ? commercial.fixedPrice : commercial.pricePerPerson) * (1 - commercial.discountPercentage / 100));
  const changeCommercial = <K extends keyof CommercialValues>(key: K, value: CommercialValues[K]) => { setCommercialDirty(true); setCommercial((current) => ({ ...current, [key]: value })); };
  const selectLead = (leadId: string) => { setSelectedLeadId(leadId); const lead = leads.find((item) => item._id === leadId); if (lead && !quote) { setGuestCount(lead.guestCount ?? 0); setSelectedSalonIds(lead.salonIds?.length ? lead.salonIds : lead.salonId ? [lead.salonId] : []); } };
  const selectCustomer = (customerId: string) => { setSelectedCustomerId(customerId); setSelectedLeadId(''); const customer = customers.find((item) => item._id === customerId); if (customer && !quote) setSelectedSalonIds((ids) => ids.length ? ids : []); };
  const selectPackage = (id: string) => { setSelectedPackageId(id); setManualMode(!id); setCommercialDirty(!id); const item = packages.find((entry) => entry._id === id); if (item) setCommercial(asCommercial(item)); };
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedSalonIds.length) return setNotice('Seleccioná al menos un salón para cotizar.'); if (!quote && targetMode === 'search' && !selectedLeadId && !selectedCustomerId) return setNotice('Seleccioná un lead, un cliente o cargá una persona nueva.'); if (!guestCount) return setNotice('Indicá una cantidad de personas válida.'); if (!manualMode && !selectedPackageId) return setNotice('Seleccione una plantilla o Presupuesto manual.'); if (!manualMode && selectedSalonIds.some((id) => !rules[id]?.ruleConfigured)) return setNotice('Hay salones sin reglas comerciales para este paquete. Elegí modo manual o configurá las reglas.'); if (!finalPrice) return setNotice(commercial.pricingMode === 'fixed' ? 'El precio total debe ser mayor a cero.' : 'El valor por persona debe ser mayor a cero.'); const form = new FormData(event.currentTarget); await onSubmit({ leadId: selectedLeadId || undefined, customerId: selectedCustomerId || undefined, salonIds: selectedSalonIds, salonId: selectedSalonIds[0], packageTemplateId: manualMode ? undefined : selectedPackageId, manualMode, applyCommercialOverrides: manualMode || commercialDirty, contactName: String(form.get('contactName') ?? ''), phone: String(form.get('phone') ?? ''), email: String(form.get('email') ?? '') || undefined, eventType: String(form.get('eventType') ?? ''), eventDate: String(form.get('eventDate') ?? '') || undefined, guestCount, honoreeName: String(form.get('honoreeName') ?? '') || undefined, vegetarianCount: Number(form.get('vegetarianCount') || 0), veganCount: Number(form.get('veganCount') || 0), celiacCount: Number(form.get('celiacCount') || 0), lactoseIntolerantCount: Number(form.get('lactoseIntolerantCount') || 0), tableLinenColor: String(form.get('tableLinenColor') ?? '') || undefined, packageName: manualMode ? String(form.get('packageName') ?? 'Presupuesto manual') : selectedPackage?.name, ...commercial, durationHours: commercial.durationHours || undefined, finalPricePerPerson: commercial.pricingMode === 'per_person' ? finalPrice : 0, finalFixedPrice: commercial.pricingMode === 'fixed' ? finalPrice : 0, menuSections: cleanMenuSections(commercial.menuSections), includedServices: cleanStringList(commercial.includedServices) }); };
  const currentLead = leads.find((item) => item._id === selectedLeadId); const currentCustomer = customers.find((item) => item._id === selectedCustomerId); const defaults = quote ?? quoteRequest ?? currentLead ?? currentCustomer;

  return <Modal open={open} onClose={onClose} title={quote ? 'Editar presupuesto' : 'Nuevo presupuesto'} description={quote ? 'Los cambios afectan sólo el snapshot de este presupuesto.' : 'Cada salón seleccionado genera un presupuesto independiente.'}><form key={`${quote?._id ?? 'new'}-${selectedLeadId}-${selectedCustomerId}-${targetMode}`} onSubmit={(event) => void save(event)} className="grid gap-5 p-5 sm:p-6 lg:grid-cols-2">
    {!quote && <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium text-zinc-900">¿Para quién es el presupuesto?</p><p className="mt-1 text-sm text-zinc-500">Buscá lead/cliente existente o cargá una persona nueva.</p></div><div className="flex gap-2"><Button type="button" variant={targetMode === 'search' ? 'primary' : 'secondary'} onClick={() => setTargetMode('search')}>Buscar</Button><Button type="button" variant={targetMode === 'new' ? 'primary' : 'secondary'} onClick={() => { setTargetMode('new'); setSelectedLeadId(''); setSelectedCustomerId(''); }}>Persona nueva</Button></div></div>{targetMode === 'search' && <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="block text-sm font-medium text-zinc-700">Leads<Select value={selectedLeadId} onChange={(event) => { selectLead(event.target.value); setSelectedCustomerId(''); }} className="mt-1.5"><option value="">Seleccionar lead</option>{leads.map((lead) => <option key={lead._id} value={lead._id}>{leadName(lead)} · {lead.phone ?? 'Sin teléfono'}</option>)}</Select></label><label className="block text-sm font-medium text-zinc-700">Clientes<Select value={selectedCustomerId} onChange={(event) => selectCustomer(event.target.value)} className="mt-1.5"><option value="">Seleccionar cliente</option>{customers.map((customer) => <option key={customer._id} value={customer._id}>{customerName(customer)} · {customer.phone ?? customer.email ?? 'Sin contacto'}</option>)}</Select></label></div>}</div>}
    <label className="text-sm font-medium text-zinc-700">Nombre y apellido<Input required name="contactName" defaultValue={quote?.contactName ?? quoteRequest?.contactName ?? (currentLead ? leadName(currentLead) : currentCustomer ? customerName(currentCustomer) : '')} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Teléfono<Input required name="phone" defaultValue={quote?.phone ?? quoteRequest?.phone ?? (defaults as LeadOption | Customer)?.phone ?? ''} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Email<Input name="email" type="email" defaultValue={quote?.email ?? quoteRequest?.email ?? (defaults as LeadOption | Customer)?.email ?? ''} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Tipo de evento<Input required name="eventType" defaultValue={quote?.eventType ?? quoteRequest?.eventType ?? (defaults as LeadOption)?.eventType ?? ''} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Fecha tentativa<Input name="eventDate" type="date" defaultValue={dateValue(quote?.eventDate ?? quoteRequest?.estimatedEventDate ?? (defaults as LeadOption)?.eventDate)} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Cantidad de personas<Input required min="1" type="number" value={guestCount || ''} onChange={(event) => setGuestCount(Number(event.target.value))} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Agasajado/a<Input name="honoreeName" defaultValue={quote?.honoreeName ?? ''} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Color de mantelería<Input name="tableLinenColor" defaultValue={quote?.tableLinenColor ?? ''} className="mt-1.5" placeholder="Blanco, negro, combinado…" /></label><div className="grid gap-3 rounded-xl border border-zinc-200 bg-zinc-50 p-3 sm:grid-cols-2 lg:col-span-2 lg:grid-cols-4"><label className="text-sm font-medium text-zinc-700">Vegetarianos<Input name="vegetarianCount" type="number" min="0" defaultValue={quote?.vegetarianCount ?? 0} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Veganos<Input name="veganCount" type="number" min="0" defaultValue={quote?.veganCount ?? 0} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Celíacos<Input name="celiacCount" type="number" min="0" defaultValue={quote?.celiacCount ?? 0} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Intolerancia a lactosa<Input name="lactoseIntolerantCount" type="number" min="0" defaultValue={quote?.lactoseIntolerantCount ?? 0} className="mt-1.5" /></label></div>
    <div className="lg:col-span-2"><p className="text-sm font-medium text-zinc-700">Salones a cotizar</p><div className="mt-2 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{salons.map((salon) => <label key={salon._id} className={`flex cursor-pointer items-center gap-3 rounded-xl border px-3 py-3 text-sm ${selectedSalonIds.includes(salon._id) ? 'border-zinc-950 bg-zinc-950 text-white' : 'border-zinc-200 bg-white text-zinc-700'}`}><input className="sr-only" type="checkbox" checked={selectedSalonIds.includes(salon._id)} onChange={() => setSelectedSalonIds((ids) => ids.includes(salon._id) ? ids.filter((id) => id !== salon._id) : [...ids, salon._id])} /><CheckCircle2 className="h-4 w-4" />{salon.name}</label>)}</div></div>
    <label className="text-sm font-medium text-zinc-700 lg:col-span-2">Paquete<Select value={manualMode ? '' : selectedPackageId} onChange={(event) => selectPackage(event.target.value)} className="mt-1.5"><option value="">Presupuesto manual / Sin plantilla</option>{packages.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></label>{!manualMode && !packages.length && <p className="text-sm text-red-700 lg:col-span-2">No hay plantillas disponibles. Configurá una desde el salón o elegí Presupuesto manual.</p>}
    <div className="grid gap-3 rounded-2xl border border-amber-200 bg-amber-50/60 p-4 lg:col-span-2"><p className="flex items-center gap-2 text-sm font-semibold text-amber-950"><Calculator className="h-4 w-4" />Vista previa por salón</p>{selectedSalonIds.map((salonId) => { const rule = rules[salonId] ?? selectedPackage; const missing = !manualMode && selectedPackageId && !rules[salonId]?.ruleConfigured; const source = commercialDirty || manualMode ? commercial : asCommercial(rule); const base = source.pricingMode === 'fixed' ? source.fixedPrice : source.pricePerPerson; const final = Math.round(base * (1 - source.discountPercentage / 100)); const total = source.pricingMode === 'fixed' ? final : final * guestCount; return <div key={salonId} className="rounded-xl border border-amber-200 bg-white p-3"><p className="font-semibold text-zinc-900">{salons.find((salon) => salon._id === salonId)?.name}</p>{missing ? <p className="mt-2 flex gap-2 text-sm text-red-700"><AlertTriangle className="h-4 w-4 shrink-0" />Este paquete no tiene reglas configuradas para este salón.</p> : <div className="mt-2 grid gap-2 text-sm sm:grid-cols-3"><span>Modalidad: <b>{source.pricingMode === 'fixed' ? 'Precio total' : 'Por persona'}</b></span><span>{source.pricingMode === 'fixed' ? 'Precio base' : 'Valor/persona'}: <b>{money(base)}</b></span><span>Descuento: <b>{source.discountPercentage}%</b></span><span>Total: <b>{money(total)}</b></span><span>Seña: <b>{money(source.depositAmount)}</b></span><span>Saldo: <b>{money(Math.max(0, total - source.depositAmount))}</b></span></div>}</div>; })}{!selectedSalonIds.length && <p className="text-sm text-amber-900">Seleccioná uno o más salones para ver el cálculo.</p>}</div>
    <label className="text-sm font-medium text-zinc-700">Nombre comercial<Input name="packageName" defaultValue={quote?.packageName ?? quoteRequest?.interestedPackageName ?? 'Presupuesto manual'} disabled={!manualMode} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Duración (horas)<Input type="number" min="0" value={commercial.durationHours || ''} onChange={(e) => changeCommercial('durationHours', Number(e.target.value))} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Inicio<Input type="time" value={commercial.startTime} onChange={(e) => changeCommercial('startTime', e.target.value)} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Fin<Input type="time" value={commercial.endTime} onChange={(e) => changeCommercial('endTime', e.target.value)} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700 lg:col-span-2">Modalidad de cobro<Select value={commercial.pricingMode} onChange={(e) => changeCommercial('pricingMode', e.target.value as CommercialValues['pricingMode'])} className="mt-1.5"><option value="per_person">Precio por persona</option><option value="fixed">Precio total del evento</option></Select><span className="mt-1 block text-xs font-normal text-zinc-500">El precio total no cambia aunque varíe la cantidad de invitados.</span></label>{commercial.pricingMode === 'fixed' ? <label className="text-sm font-medium text-zinc-700">Precio total<Input type="number" min="0" value={commercial.fixedPrice || ''} onChange={(e) => changeCommercial('fixedPrice', Number(e.target.value))} className="mt-1.5" /></label> : <label className="text-sm font-medium text-zinc-700">Valor por persona<Input type="number" min="0" value={commercial.pricePerPerson || ''} onChange={(e) => changeCommercial('pricePerPerson', Number(e.target.value))} className="mt-1.5" /></label>}<label className="text-sm font-medium text-zinc-700">Descuento (%)<Input type="number" min="0" max="100" value={commercial.discountPercentage || ''} onChange={(e) => changeCommercial('discountPercentage', Number(e.target.value))} className="mt-1.5" /></label><div className="text-sm font-medium text-zinc-700">{commercial.pricingMode === 'fixed' ? 'Precio total final' : 'Valor final por persona'}<p className="mt-1.5 rounded-lg border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-zinc-900">{money(finalPrice)}</p></div><label className="text-sm font-medium text-zinc-700">Seña<Input type="number" min="0" value={commercial.depositAmount || ''} onChange={(e) => changeCommercial('depositAmount', Number(e.target.value))} className="mt-1.5" /></label>
    <label className="text-sm font-medium text-zinc-700">Promoción<Textarea value={commercial.promotionText} onChange={(e) => changeCommercial('promotionText', e.target.value)} className="mt-1.5 min-h-20" /></label><label className="text-sm font-medium text-zinc-700">Regalo<Textarea value={commercial.giftText} onChange={(e) => changeCommercial('giftText', e.target.value)} className="mt-1.5 min-h-20" /></label><label className="text-sm font-medium text-zinc-700 lg:col-span-2">Condiciones de pago<Textarea value={commercial.paymentTerms} onChange={(e) => changeCommercial('paymentTerms', e.target.value)} className="mt-1.5 min-h-20" /></label><div className="lg:col-span-2"><MenuSectionsEditor value={commercial.menuSections} onChange={(value) => changeCommercial('menuSections', value)} /></div><div className="lg:col-span-2"><StringListEditor label="Servicios incluidos" values={commercial.includedServices} itemPlaceholder="Ej.: DJ, sonido e iluminación" onChange={(value) => changeCommercial('includedServices', value)} /></div><label className="text-sm font-medium text-zinc-700 lg:col-span-2">Observaciones internas<Textarea value={commercial.notes} onChange={(e) => changeCommercial('notes', e.target.value)} className="mt-1.5" /></label>
    <footer className="sticky bottom-0 -mx-5 flex justify-end gap-3 border-t border-zinc-200 bg-white px-5 pt-5 sm:-mx-6 sm:px-6 lg:col-span-2"><Button type="button" variant="secondary" onClick={onClose}>Cancelar</Button><Button disabled={saving}><UserRound className="mr-2 h-4 w-4" />{saving ? 'Guardando…' : quote ? 'Guardar cambios' : 'Crear presupuesto'}</Button></footer>
  </form></Modal>;
}
