'use client';
/* eslint-disable react-hooks/set-state-in-effect */

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Calculator, CheckCircle2, UserRound } from 'lucide-react';
import { api } from '@/lib/api';
import { Button, Input, Modal, Select, Textarea } from '@/components/ui/primitives';
import { useToast } from '@/components/ui/toast-provider';
import type { LeadOption, PackageTemplate, Quote, Salon } from './types';

type CommercialValues = { durationHours: number; startTime: string; endTime: string; pricePerPerson: number; discountPercentage: number; depositAmount: number; paymentTerms: string; promotionText: string; giftText: string; notes: string; menuSections: { title: string; items: string[] }[]; includedServices: string[] };
type CommercialSource = Partial<Omit<CommercialValues, 'menuSections'> & { menuSections: { title?: string; name?: string; items: string[] }[] }>;
type RulePackage = PackageTemplate & { ruleConfigured?: boolean };
type QuoteFormModalProps = { open: boolean; quote?: Quote; salons: Salon[]; leads: LeadOption[]; packages: PackageTemplate[]; saving: boolean; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => Promise<void> };
const dateValue = (value?: string) => value?.slice(0, 10) ?? '';
const leadName = (lead?: LeadOption) => lead?.fullName || [lead?.firstName, lead?.lastName].filter(Boolean).join(' ') || 'Lead sin nombre';
const money = (value: number) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(value);
const asCommercial = (source?: CommercialSource): CommercialValues => ({ durationHours: source?.durationHours ?? 0, startTime: source?.startTime ?? '', endTime: source?.endTime ?? '', pricePerPerson: source?.pricePerPerson ?? 0, discountPercentage: source?.discountPercentage ?? 0, depositAmount: source?.depositAmount ?? 0, paymentTerms: source?.paymentTerms ?? '', promotionText: source?.promotionText ?? '', giftText: source?.giftText ?? '', notes: source?.notes ?? '', menuSections: (source?.menuSections ?? []).map((section) => ({ title: section.title ?? section.name ?? 'Menú', items: section.items })), includedServices: source?.includedServices ?? [] });
const menuToText = (sections: CommercialValues['menuSections']) => sections.map((section) => `${section.title}: ${section.items.join(' | ')}`).join('\n');
const textToMenu = (text: string) => text.split('\n').map((line) => { const [title, ...items] = line.split(':'); return { title: title.trim(), items: items.join(':').split('|').map((item) => item.trim()).filter(Boolean) }; }).filter((section) => section.title && section.items.length);

export function QuoteFormModal({ open, quote, salons, leads, packages: initialPackages, saving, onClose, onSubmit }: QuoteFormModalProps) {
  const { showToast } = useToast();
  const [selectedLeadId, setSelectedLeadId] = useState(''); const [selectedSalonIds, setSelectedSalonIds] = useState<string[]>([]); const [selectedPackageId, setSelectedPackageId] = useState(''); const [manualMode, setManualMode] = useState(false); const [createNewPerson, setCreateNewPerson] = useState(false); const [guestCount, setGuestCount] = useState(0);
  const [packages, setPackages] = useState(initialPackages); const [rules, setRules] = useState<Record<string, RulePackage>>({}); const [commercial, setCommercial] = useState<CommercialValues>(asCommercial()); const [commercialDirty, setCommercialDirty] = useState(false);
  const setNotice = (message: string) => { if (message) showToast({ message, variant: 'error' }); };

  useEffect(() => { if (!open) return; void api.get<{ packages?: PackageTemplate[] }>('/quotes/packages').then((response) => setPackages(response.packages ?? [])).catch((error: Error) => setNotice(`No se pudieron cargar las plantillas: ${error.message}`)); }, [open]);
  useEffect(() => { const source = quote; setSelectedLeadId(typeof source?.leadId === 'string' ? source.leadId : source?.leadId?._id ?? ''); setSelectedSalonIds(source ? [typeof source.salonId === 'string' ? source.salonId : source.salonId._id] : []); setSelectedPackageId(typeof source?.packageTemplateId === 'string' ? source.packageTemplateId : source?.packageTemplateId?._id ?? ''); setManualMode(Boolean(source && !source.packageTemplateId)); setCreateNewPerson(Boolean(source && !source.leadId)); setGuestCount(source?.guestCount ?? 0); setCommercial(asCommercial(source)); setCommercialDirty(Boolean(source)); setRules({}); setNotice(''); }, [quote, open]);

  const selectedPackage = useMemo(() => packages.find((item) => item._id === selectedPackageId), [packages, selectedPackageId]);
  useEffect(() => { if (!selectedPackageId || !selectedSalonIds.length || manualMode) return; let cancelled = false; void Promise.all(selectedSalonIds.map(async (salonId) => { try { const response = await api.get<{ package: RulePackage }>(`/quotes/packages/${selectedPackageId}/salons/${salonId}`); return [salonId, response.package] as const; } catch { return [salonId, { ...selectedPackage, ruleConfigured: false }] as const; } })).then((items) => { if (cancelled) return; const next = Object.fromEntries(items); setRules(next); const first = items.find(([, item]) => item.ruleConfigured)?.[1]; if (first && !quote) { setCommercial(asCommercial(first)); setCommercialDirty(false); } }).catch(() => { if (!cancelled) setNotice('No se pudieron cargar las reglas comerciales por salón.'); }); return () => { cancelled = true; }; }, [selectedPackageId, selectedSalonIds, manualMode, selectedPackage, quote]);

  const finalPrice = Math.round(commercial.pricePerPerson * (1 - commercial.discountPercentage / 100));
  const changeCommercial = <K extends keyof CommercialValues>(key: K, value: CommercialValues[K]) => { setCommercialDirty(true); setCommercial((current) => ({ ...current, [key]: value })); };
  const selectLead = (leadId: string) => { setSelectedLeadId(leadId); const lead = leads.find((item) => item._id === leadId); if (lead && !quote) { setGuestCount(lead.guestCount ?? 0); setSelectedSalonIds(lead.salonIds?.length ? lead.salonIds : lead.salonId ? [lead.salonId] : []); } };
  const selectPackage = (id: string) => { setSelectedPackageId(id); setManualMode(!id); setCommercialDirty(!id); const item = packages.find((entry) => entry._id === id); if (item) setCommercial(asCommercial(item)); };
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selectedSalonIds.length) return setNotice('Seleccioná al menos un salón para cotizar.'); if (!quote && !selectedLeadId && !createNewPerson) return setNotice('Seleccioná un lead existente o cargá una persona nueva.'); if (!guestCount) return setNotice('Indicá una cantidad de personas válida.'); if (!manualMode && !selectedPackageId) return setNotice('Seleccione una plantilla o Presupuesto manual.'); if (!manualMode && selectedSalonIds.some((id) => !rules[id]?.ruleConfigured)) return setNotice('Hay salones sin reglas comerciales para este paquete. Elegí modo manual o configurá las reglas.'); if (!commercial.pricePerPerson || !finalPrice) return setNotice('El valor final por persona y el total no pueden quedar en cero.'); const form = new FormData(event.currentTarget); await onSubmit({ leadId: selectedLeadId || undefined, salonIds: selectedSalonIds, salonId: selectedSalonIds[0], packageTemplateId: manualMode ? undefined : selectedPackageId, manualMode, applyCommercialOverrides: manualMode || commercialDirty, contactName: String(form.get('contactName') ?? ''), phone: String(form.get('phone') ?? ''), email: String(form.get('email') ?? '') || undefined, eventType: String(form.get('eventType') ?? ''), eventDate: String(form.get('eventDate') ?? '') || undefined, guestCount, packageName: manualMode ? String(form.get('packageName') ?? 'Presupuesto manual') : selectedPackage?.name, ...commercial, finalPricePerPerson: finalPrice, menuSections: commercial.menuSections, includedServices: commercial.includedServices }); };
  const currentLead = leads.find((item) => item._id === selectedLeadId); const defaults = quote ?? currentLead;

  return <Modal open={open} onClose={onClose} title={quote ? 'Editar presupuesto' : 'Nuevo presupuesto'} description={quote ? 'Los cambios afectan sólo el snapshot de este presupuesto.' : 'Cada salón seleccionado genera un presupuesto independiente.'}><form onSubmit={(event) => void save(event)} className="grid gap-5 p-5 sm:p-6 lg:grid-cols-2">
    {!quote && <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium text-zinc-900">Contacto a presupuestar</p><p className="mt-1 text-sm text-zinc-500">Usá un lead existente o registrá una persona nueva.</p></div><Button type="button" variant="secondary" onClick={() => { setCreateNewPerson((value) => !value); setSelectedLeadId(''); }}>{createNewPerson ? 'Usar lead existente' : 'Cargar persona nueva'}</Button></div>{!createNewPerson && <label className="mt-4 block text-sm font-medium text-zinc-700">Lead existente<Select value={selectedLeadId} onChange={(event) => selectLead(event.target.value)} className="mt-1.5"><option value="">Seleccionar lead</option>{leads.map((lead) => <option key={lead._id} value={lead._id}>{leadName(lead)} · {lead.phone ?? 'Sin teléfono'}</option>)}</Select></label>}</div>}
    <label className="text-sm font-medium text-zinc-700">Nombre y apellido<Input required name="contactName" defaultValue={quote?.contactName ?? (defaults ? leadName(defaults as LeadOption) : '')} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Teléfono<Input required name="phone" defaultValue={quote?.phone ?? (defaults as LeadOption)?.phone ?? ''} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Email<Input name="email" type="email" defaultValue={quote?.email ?? (defaults as LeadOption)?.email ?? ''} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Tipo de evento<Input required name="eventType" defaultValue={quote?.eventType ?? (defaults as LeadOption)?.eventType ?? ''} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Fecha tentativa<Input name="eventDate" type="date" defaultValue={dateValue(quote?.eventDate ?? (defaults as LeadOption)?.eventDate)} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Cantidad de personas<Input required min="1" type="number" value={guestCount || ''} onChange={(event) => setGuestCount(Number(event.target.value))} className="mt-1.5" /></label>
    <div className="lg:col-span-2"><p className="text-sm font-medium text-zinc-700">Salones a cotizar</p><div className="mt-2 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{salons.map((salon) => <label key={salon._id} className={`flex cursor-pointer items-center gap-3 rounded-xl border px-3 py-3 text-sm ${selectedSalonIds.includes(salon._id) ? 'border-zinc-950 bg-zinc-950 text-white' : 'border-zinc-200 bg-white text-zinc-700'}`}><input className="sr-only" type="checkbox" checked={selectedSalonIds.includes(salon._id)} onChange={() => setSelectedSalonIds((ids) => ids.includes(salon._id) ? ids.filter((id) => id !== salon._id) : [...ids, salon._id])} /><CheckCircle2 className="h-4 w-4" />{salon.name}</label>)}</div></div>
    <label className="text-sm font-medium text-zinc-700 lg:col-span-2">Paquete<Select value={manualMode ? '' : selectedPackageId} onChange={(event) => selectPackage(event.target.value)} className="mt-1.5"><option value="">Presupuesto manual / Sin plantilla</option>{packages.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select></label>{!manualMode && !packages.length && <p className="text-sm text-red-700 lg:col-span-2">No hay plantillas disponibles. Ejecutá el seed comercial o elegí Presupuesto manual.</p>}
    <div className="grid gap-3 rounded-2xl border border-amber-200 bg-amber-50/60 p-4 lg:col-span-2"><p className="flex items-center gap-2 text-sm font-semibold text-amber-950"><Calculator className="h-4 w-4" />Vista previa por salón</p>{selectedSalonIds.map((salonId) => { const rule = rules[salonId] ?? selectedPackage; const missing = !manualMode && selectedPackageId && !rules[salonId]?.ruleConfigured; const price = commercialDirty || manualMode ? commercial.pricePerPerson : rule?.pricePerPerson ?? commercial.pricePerPerson; const discount = commercialDirty || manualMode ? commercial.discountPercentage : rule?.discountPercentage ?? commercial.discountPercentage; const final = Math.round(price * (1 - discount / 100)); const total = final * guestCount; const deposit = commercialDirty || manualMode ? commercial.depositAmount : rule?.depositAmount ?? commercial.depositAmount; return <div key={salonId} className="rounded-xl border border-amber-200 bg-white p-3"><p className="font-semibold text-zinc-900">{salons.find((salon) => salon._id === salonId)?.name}</p>{missing ? <p className="mt-2 flex gap-2 text-sm text-red-700"><AlertTriangle className="h-4 w-4 shrink-0" />Este paquete no tiene reglas configuradas para este salón.</p> : <div className="mt-2 grid gap-2 text-sm sm:grid-cols-3"><span>Valor/persona: <b>{money(price)}</b></span><span>Descuento: <b>{discount}%</b></span><span>Final/persona: <b>{money(final)}</b></span><span>Total: <b>{money(total)}</b></span><span>Seña: <b>{money(deposit)}</b></span><span>Saldo: <b>{money(Math.max(0, total - deposit))}</b></span></div>}</div>; })}{!selectedSalonIds.length && <p className="text-sm text-amber-900">Seleccioná uno o más salones para ver el cálculo.</p>}</div>
    <label className="text-sm font-medium text-zinc-700">Nombre comercial<Input name="packageName" defaultValue={quote?.packageName ?? 'Presupuesto manual'} disabled={!manualMode} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Duración (horas)<Input type="number" min="0" value={commercial.durationHours || ''} onChange={(e) => changeCommercial('durationHours', Number(e.target.value))} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Inicio<Input type="time" value={commercial.startTime} onChange={(e) => changeCommercial('startTime', e.target.value)} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Fin<Input type="time" value={commercial.endTime} onChange={(e) => changeCommercial('endTime', e.target.value)} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Valor por persona<Input type="number" min="0" value={commercial.pricePerPerson || ''} onChange={(e) => changeCommercial('pricePerPerson', Number(e.target.value))} className="mt-1.5" /></label><label className="text-sm font-medium text-zinc-700">Descuento (%)<Input type="number" min="0" max="100" value={commercial.discountPercentage || ''} onChange={(e) => changeCommercial('discountPercentage', Number(e.target.value))} className="mt-1.5" /></label><div className="text-sm font-medium text-zinc-700">Valor final por persona<p className="mt-1.5 rounded-lg border border-zinc-200 bg-zinc-50 px-3 py-2.5 text-zinc-900">{money(finalPrice)}</p></div><label className="text-sm font-medium text-zinc-700">Seña<Input type="number" min="0" value={commercial.depositAmount || ''} onChange={(e) => changeCommercial('depositAmount', Number(e.target.value))} className="mt-1.5" /></label>
    <label className="text-sm font-medium text-zinc-700">Promoción<Textarea value={commercial.promotionText} onChange={(e) => changeCommercial('promotionText', e.target.value)} className="mt-1.5 min-h-20" /></label><label className="text-sm font-medium text-zinc-700">Regalo<Textarea value={commercial.giftText} onChange={(e) => changeCommercial('giftText', e.target.value)} className="mt-1.5 min-h-20" /></label><label className="text-sm font-medium text-zinc-700 lg:col-span-2">Condiciones de pago<Textarea value={commercial.paymentTerms} onChange={(e) => changeCommercial('paymentTerms', e.target.value)} className="mt-1.5 min-h-20" /></label><label className="text-sm font-medium text-zinc-700 lg:col-span-2">Menú (una sección por línea: Sección: ítem | ítem)<Textarea value={menuToText(commercial.menuSections)} onChange={(e) => changeCommercial('menuSections', textToMenu(e.target.value))} className="mt-1.5 min-h-28" /></label><label className="text-sm font-medium text-zinc-700 lg:col-span-2">Servicios incluidos (uno por línea)<Textarea value={commercial.includedServices.join('\n')} onChange={(e) => changeCommercial('includedServices', e.target.value.split('\n').map((item) => item.trim()).filter(Boolean))} className="mt-1.5 min-h-28" /></label><label className="text-sm font-medium text-zinc-700 lg:col-span-2">Observaciones internas<Textarea value={commercial.notes} onChange={(e) => changeCommercial('notes', e.target.value)} className="mt-1.5" /></label>
    <footer className="sticky bottom-0 -mx-5 flex justify-end gap-3 border-t border-zinc-200 bg-white px-5 pt-5 sm:-mx-6 sm:px-6 lg:col-span-2"><Button type="button" variant="secondary" onClick={onClose}>Cancelar</Button><Button disabled={saving}><UserRound className="mr-2 h-4 w-4" />{saving ? 'Guardando…' : quote ? 'Guardar cambios' : 'Crear presupuesto'}</Button></footer>
  </form></Modal>;
}
