export type QuoteStatus = 'draft' | 'sent' | 'follow_up' | 'accepted' | 'rejected' | 'expired' | 'converted';

export type Quote = {
  _id: string;
  quoteNumber: string;
  leadId?: string | { _id: string; fullName?: string; firstName?: string; lastName?: string };
  customerId?: string | Customer;
  salonId: string | { _id: string; name: string };
  packageTemplateId?: string | { _id: string; name: string };
  status: QuoteStatus | string;
  contactName: string;
  phone: string;
  email?: string;
  eventType: string;
  eventDate?: string;
  /** Alias de compatibilidad para pantallas previas; la API usa eventDate. */
  estimatedEventDate?: string;
  guestCount: number;
  honoreeName?: string;
  vegetarianCount?: number;
  veganCount?: number;
  celiacCount?: number;
  lactoseIntolerantCount?: number;
  tableLinenColor?: string;
  packageName?: string;
  durationHours?: number;
  startTime?: string;
  endTime?: string;
  pricingMode?: 'per_person' | 'fixed';
  pricePerPerson: number;
  fixedPrice?: number;
  discountPercentage?: number;
  finalPricePerPerson: number;
  finalFixedPrice?: number;
  totalAmount: number;
  depositAmount: number;
  balanceAmount: number;
  paymentTerms?: string;
  promotionText?: string;
  giftText?: string;
  menuSections?: { title?: string; name?: string; items: string[] }[];
  includedServices?: string[];
  notes?: string;
  validUntil?: string;
  pdfUrl?: string;
  pdfSecureUrl?: string;
  pdfPublicId?: string;
  pdfGeneratedAt?: string;
  sentAt?: string;
  acceptedAt?: string;
  rejectedAt?: string;
  createdAt?: string;
  updatedAt?: string;
  convertedCustomerId?: string | Customer;
  convertedEventId?: string | Event;
};

export type Salon = { _id: string; name: string };
export type LeadOption = { _id: string; fullName?: string; firstName?: string; lastName?: string; phone?: string; email?: string; eventType?: string; eventDate?: string; guestCount?: number; salonId?: string; salonIds?: string[] };
export type Customer = { _id: string; fullName?: string; firstName?: string; lastName?: string; phone?: string; email?: string; documentNumber?: string; address?: string; occupation?: string; sourceLeadId?: string | LeadOption; quoteCount?: number; eventCount?: number; lastEvent?: { eventDate?: string; eventName?: string }; createdAt?: string; notes?: string };
export type EventTimelineItem = { id?: string; time?: string; title: string; area?: string; owner?: string; status?: 'pending' | 'ready' | 'done' | 'cancelled' | string; notes?: string };
export type EventProductItem = { id?: string; name: string; category?: string; quantity?: number; unit?: string; supplierName?: string; unitCost?: number; totalCost?: number; status?: 'planned' | 'reserved' | 'purchased' | 'used' | 'returned' | string; notes?: string };
export type EventInventoryItem = { id?: string; name: string; category?: string; quantityRequired?: number; quantityReserved?: number; quantityReturned?: number; unit?: string; status?: 'planned' | 'reserved' | 'delivered' | 'returned' | 'missing' | 'damaged' | string; notes?: string };
export type EventSupplierAssignment = { id?: string; supplierName: string; serviceType?: string; contactName?: string; phone?: string; agreedAmount?: number; status?: 'pending' | 'confirmed' | 'paid' | 'cancelled' | string; arrivalTime?: string; notes?: string };
export type EventTaskItem = { id?: string; title: string; owner?: string; dueDate?: string; priority?: 'low' | 'normal' | 'high' | 'critical' | string; status?: 'pending' | 'in_progress' | 'done' | 'blocked' | string; notes?: string };
export type EventAlertItem = { id?: string; title: string; remindAt?: string; channel?: string; status?: 'pending' | 'scheduled' | 'sent' | 'done' | string; notes?: string };
export type EventResourcePlan = {
  timelineItems?: EventTimelineItem[];
  productItems?: EventProductItem[];
  inventoryItems?: EventInventoryItem[];
  supplierAssignments?: EventSupplierAssignment[];
  tasks?: EventTaskItem[];
  alerts?: EventAlertItem[];
  logistics?: { eventSetupNotes?: string; kitchenNotes?: string; barNotes?: string; decorationNotes?: string; accessNotes?: string; riskNotes?: string };
  source?: string;
  sourceQuoteId?: string;
};
export type Event = {
  _id: string;
  customerId: string | Customer;
  sourceLeadId?: string | LeadOption;
  sourceQuoteId?: string | Quote;
  leadId?: string | LeadOption;
  quoteId?: string | Quote;
  salonId?: string | Salon;
  eventType?: string;
  eventName?: string;
  eventDate?: string;
  guestCount?: number;
  honoreeName?: string;
  vegetarianCount?: number;
  veganCount?: number;
  celiacCount?: number;
  lactoseIntolerantCount?: number;
  tableLinenColor?: string;
  status: string;
  estimatedAmount?: number;
  finalAmount?: number;
  startTime?: string;
  endTime?: string;
  commercialSnapshot?: Record<string, unknown>;
  menuSnapshot?: { title?: string; items?: string[] }[];
  servicesSnapshot?: string[];
  paymentSnapshot?: Record<string, unknown>;
  paymentPlanSnapshot?: Array<{
    id?: string;
    label?: string;
    amount?: number;
    paidAmount?: number;
    paymentId?: string;
    dueDate?: string;
    paymentWindowStart?: string;
    paymentWindowEnd?: string;
    status?: string;
    notes?: string;
  }>;
  resourcePlanSnapshot?: EventResourcePlan;
  contractReadyChecklist?: Record<string, boolean>;
  notes?: string;
  createdAt?: string;
  updatedAt?: string;
};
export type Contract = {
  _id: string;
  contractNumber: string;
  eventId: string | Event;
  quoteId?: string | Quote;
  customerId: string | Customer;
  leadId?: string | LeadOption;
  salonId: string | Salon;
  status: string;
  versionNumber?: number;
  supersedesContractId?: string;
  supersededByContractId?: string;
  customerSnapshot?: Record<string, unknown>;
  eventSnapshot?: Record<string, unknown>;
  commercialSnapshot?: Record<string, unknown>;
  menuSnapshot?: { title?: string; items?: string[] }[];
  servicesSnapshot?: string[];
  paymentAgreementSnapshot?: Record<string, unknown>;
  legalTermsSnapshot?: { providerText?: string; clauses?: { key?: string; title?: string; text?: string }[] };
  securityDeposit?: { amount?: number; requiredAt?: string; returnedAt?: string; status?: string; notes?: string };
  securityDepositSnapshot?: Record<string, unknown>;
  baseAmount?: number;
  approvedAddendumsAmount?: number;
  pendingAddendumsAmount?: number;
  discountsAmount?: number;
  totalAmount?: number;
  paidAmount?: number;
  balanceAmount?: number;
  observations?: string;
  approvedAt?: string;
  approvedByUserId?: string;
  cancelledAt?: string;
  pdfUrl?: string;
  pdfSecureUrl?: string;
  pdfPublicId?: string;
  pdfGeneratedAt?: string;
  createdAt?: string;
  updatedAt?: string;
};
export type ContractAddendumItem = { type?: string; name: string; description?: string; quantity?: number; unitPrice?: number; totalPrice?: number };
export type ContractAddendum = {
  _id: string;
  addendumNumber: string;
  contractId: string | Contract;
  eventId: string | Event;
  customerId: string | Customer;
  salonId: string | Salon;
  status: string;
  title: string;
  description?: string;
  items: ContractAddendumItem[];
  subtotalAmount: number;
  discountAmount: number;
  totalAmount: number;
  affectsBalance: boolean;
  approvedAt?: string;
  cancelledAt?: string;
  createdAt?: string;
};
export type Payment = {
  _id: string;
  paymentNumber: string;
  customerId: string | Customer;
  eventId: string | Event;
  contractId: string | Contract;
  quoteId?: string | Quote;
  salonId: string | Salon;
  type: string;
  method?: string;
  status: string;
  amount: number;
  dueDate?: string;
  paidAt?: string;
  receiptNumber?: string;
  receiptPdfUrl?: string;
  receiptPdfSecureUrl?: string;
  receiptPdfPublicId?: string;
  receiptPdfGeneratedAt?: string;
  receiptEmailSentAt?: string;
  reference?: string;
  notes?: string;
  affectsContractBalance?: boolean;
  refundedPaymentId?: string | Payment;
  cancelledAt?: string;
  createdAt?: string;
  updatedAt?: string;
};
export type PaymentSummary = { paidAmount: number; refundedAmount: number; pendingAmount: number; securityDepositAmount: number; overdueAmount: number };
export type QuoteRequest = {
  _id: string;
  leadId: string | LeadOption;
  customerId?: string | Customer;
  source: string;
  status: string;
  contactName: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  email?: string;
  eventType?: string;
  estimatedEventDate?: string;
  guestCount?: number;
  interestedSalonIds?: Array<string | Salon>;
  interestedPackageTemplateId?: string | { _id: string; name?: string };
  interestedPackageName?: string;
  message?: string;
  assignedToUserId?: string | { _id: string; firstName?: string; lastName?: string; email?: string };
  takenByUserId?: string | { _id: string; firstName?: string; lastName?: string; email?: string };
  convertedQuoteIds?: string[];
  possibleDuplicateLeadIds?: LeadOption[];
  internalNotes?: string;
  createdAt?: string;
  updatedAt?: string;
};
export type PackageTemplate = {
  _id: string;
  name: string;
  durationHours?: number;
  startTime?: string;
  endTime?: string;
  pricingMode?: 'per_person' | 'fixed';
  pricePerPerson?: number;
  fixedPrice?: number;
  discountPercentage?: number;
  finalPricePerPerson?: number;
  finalFixedPrice?: number;
  depositAmount?: number;
  paymentTerms?: string;
  promotionText?: string;
  giftText?: string;
  menuSections?: { title?: string; name?: string; items: string[] }[];
  includedServices?: string[];
};

export type PaginationMeta = { page: number; limit: number; totalItems: number; totalPages: number; hasNextPage: boolean; hasPreviousPage: boolean };

export const getEntityId = (value?: string | { _id: string }) => typeof value === 'string' ? value : value?._id ?? '';
export const getLeadName = (lead?: Quote['leadId']) => {
  if (!lead || typeof lead === 'string') return '';
  return lead.fullName || [lead.firstName, lead.lastName].filter(Boolean).join(' ');
};
export const getSalonName = (salon: Quote['salonId'], salons: Salon[]) => typeof salon === 'string' ? salons.find((item) => item._id === salon)?.name ?? 'Sin salón' : salon.name;
