import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import { uploadBuffer } from '../uploads/cloudinary.service';

const page = { width: 595.28, height: 841.89, left: 46, right: 549, bottom: 785 };
const color = { ink: '#101a2c', gold: '#b78b45', muted: '#64748b', line: '#d8dee8', card: '#f5f7fa', white: '#ffffff' };
const money = (value?: unknown) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(Number(value ?? 0));
const text = (value?: unknown, fallback = 'No informado') => typeof value === 'string' && value.trim() ? value.trim() : fallback;
// `event.eventDate`/`paymentWindowStart`/`paymentWindowEnd`/`dueDate` son fechas civiles
// normalizadas a medianoche UTC (`civilDateInput`) — sin `timeZone: 'UTC'` explícito, el huso
// local del proceso (Argentina, UTC-3) corre esa medianoche al día anterior.
const date = (value?: unknown) => value ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(value as string)) : 'No informado';
// `contract.approvedAt`/"ahora" sí son instantes reales — se muestran en hora de Argentina (la
// del lector), no en el huso del proceso que generó el PDF.
const instantDate = (value?: unknown) => value ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'long', timeZone: 'America/Argentina/Buenos_Aires' }).format(new Date(value as string)) : 'No informado';

function buffer(document: PDFKit.PDFDocument): Promise<Buffer> { return new Promise((resolve, reject) => { const chunks: Buffer[] = []; document.on('data', (chunk) => chunks.push(Buffer.from(chunk))); document.on('end', () => resolve(Buffer.concat(chunks))); document.on('error', reject); document.end(); }); }
function logo(document: PDFKit.PDFDocument, x: number, y: number) { const assets = [path.resolve(process.cwd(), '../web/public/brand/mym-logo-light-on-dark.jpg'), path.resolve(process.cwd(), 'apps/web/public/brand/mym-logo-light-on-dark.jpg')]; const asset = assets.find(fs.existsSync); if (asset) document.image(asset, x, y, { width: 65 }); else document.font('Helvetica-Bold').fontSize(13).fillColor(color.white).text('M&M\nEVENTOS', x, y + 8); }
function header(document: PDFKit.PDFDocument, contract: any) { document.rect(0, 0, page.width, 76).fill(color.ink); logo(document, page.left, 8); document.font('Helvetica').fontSize(8).fillColor('#ddc99f').text('CONTRATO DE PRESTACIÓN DE SERVICIOS', 250, 20, { width: 299, align: 'right', characterSpacing: 1 }); document.font('Helvetica-Bold').fontSize(11).fillColor(color.white).text(contract.contractNumber, 250, 36, { width: 299, align: 'right' }); }
function footer(document: PDFKit.PDFDocument, current: number, total: number) { document.moveTo(page.left, page.bottom - 12).lineTo(page.right, page.bottom - 12).strokeColor(color.line).stroke(); document.font('Helvetica').fontSize(7.5).fillColor(color.muted).text(`M&M Eventos · Contrato ${current} de ${total}`, page.left, page.bottom - 3, { width: page.right - page.left }); }
function ensure(document: PDFKit.PDFDocument, contract: any, height: number) { if (document.y + height < page.bottom - 35) return; document.addPage(); header(document, contract); document.y = 98; }
function title(document: PDFKit.PDFDocument, contract: any, label: string) { ensure(document, contract, 38); const y = document.y; document.font('Helvetica-Bold').fontSize(11).fillColor(color.ink).text(label, page.left, y); document.moveTo(page.left, y + 19).lineTo(page.right, y + 19).strokeColor(color.gold).stroke(); document.y = y + 28; }
function pair(document: PDFKit.PDFDocument, label: string, value: unknown, x: number, y: number, width: number) { document.font('Helvetica-Bold').fontSize(7).fillColor(color.muted).text(label.toUpperCase(), x, y, { width }); document.font('Helvetica').fontSize(8.7).fillColor(color.ink).text(text(value), x, y + 10, { width, height: 23, ellipsis: true }); }
function paragraph(document: PDFKit.PDFDocument, contract: any, value: string) { const height = document.heightOfString(value, { width: page.right - page.left, lineGap: 3 }); ensure(document, contract, height + 8); document.font('Helvetica').fontSize(9.2).fillColor('#273449').text(value, page.left, document.y, { width: page.right - page.left, lineGap: 3 }); document.moveDown(.8); }

export async function buildContractPdfBuffer(contract: any): Promise<Buffer> {
  const document = new PDFDocument({ size: 'A4', margin: 0, bufferPages: true, info: { Title: `Contrato ${contract.contractNumber}`, Author: 'M&M Eventos', Subject: 'Contrato de prestación de servicios' } });
  header(document, contract); document.y = 99;
  document.font('Helvetica-Bold').fontSize(17).fillColor(color.ink).text('Contrato de prestación de servicios', page.left, document.y); document.moveDown(.35); document.font('Helvetica').fontSize(9).fillColor(color.muted).text(`${contract.approvedAt ? 'Formalizado el' : 'Vista previa generada el'} ${instantDate(contract.approvedAt ?? new Date())} · Versión ${contract.versionNumber ?? 1}`); document.moveDown(1);
  const client = contract.customerSnapshot ?? {}; const event = contract.eventSnapshot ?? {}; const commercial = contract.commercialSnapshot ?? {};
  title(document, contract, 'Partes contratantes'); const y = document.y; document.roundedRect(page.left, y, page.right - page.left, 72, 8).fill(color.card); pair(document, 'Prestadora', 'M&M Eventos', page.left + 14, y + 12, 220); pair(document, 'Cliente', client.fullName, page.left + 270, y + 12, 220); pair(document, 'Documento', client.documentNumber ?? client.dni, page.left + 14, y + 43, 220); pair(document, 'Teléfono / email', [client.phone, client.email].filter(Boolean).join(' · '), page.left + 270, y + 43, 220); document.y = y + 85;
  title(document, contract, 'Evento contratado'); const eventY = document.y; document.roundedRect(page.left, eventY, page.right - page.left, 130, 8).fill(color.card); pair(document, 'Evento', event.eventName ?? event.eventType, page.left + 14, eventY + 12, 220); pair(document, 'Fecha', date(event.eventDate), page.left + 270, eventY + 12, 220); pair(document, 'Homenajeado/a', event.honoreeName, page.left + 14, eventY + 43, 220); pair(document, 'Invitados', event.guestCount ? `${event.guestCount} personas` : undefined, page.left + 270, eventY + 43, 220); pair(document, 'Horario', [event.startTime, event.endTime].filter(Boolean).join(' a '), page.left + 14, eventY + 74, 220); pair(document, 'Salón', event.salonName, page.left + 270, eventY + 74, 220); pair(document, 'Dirección', event.salonAddress, page.left + 14, eventY + 105, 476); document.y = eventY + 143;
  title(document, contract, 'Valores y plan de pago'); const amountY = document.y; document.roundedRect(page.left, amountY, page.right - page.left, 72, 8).fill('#f7f1e4'); pair(document, 'Total contractual', money(contract.totalAmount), page.left + 14, amountY + 12, 180); pair(document, 'Seña acordada', money(commercial.depositAmount), page.left + 195, amountY + 12, 145); pair(document, 'Saldo actual', money(contract.balanceAmount), page.left + 350, amountY + 12, 140); pair(document, 'Condiciones', contract.paymentAgreementSnapshot?.paymentTerms ?? commercial.paymentTerms, page.left + 14, amountY + 43, 476); document.y = amountY + 85;
  const installments = Array.isArray(contract.paymentPlanSnapshot) ? contract.paymentPlanSnapshot : []; if (installments.length) { title(document, contract, 'Cuotas programadas'); installments.forEach((item: any, index: number) => { ensure(document, contract, 24); const y = document.y; document.font('Helvetica-Bold').fontSize(8.5).fillColor(color.ink).text(item.label || `Cuota ${index + 1}`, page.left, y, { width: 190 }); document.font('Helvetica').fontSize(8.5).fillColor(color.muted).text(`${date(item.paymentWindowStart)} al ${date(item.paymentWindowEnd ?? item.dueDate)}`, page.left + 195, y, { width: 180 }); document.font('Helvetica-Bold').fontSize(8.5).fillColor(color.ink).text(money(item.amount), page.left + 390, y, { width: 113, align: 'right' }); document.y = y + 18; }); document.moveDown(.5); }
  if (contract.servicesSnapshot?.length) { title(document, contract, 'Servicios incluidos'); contract.servicesSnapshot.forEach((item: string) => paragraph(document, contract, `• ${item}`)); }
  if (contract.menuSnapshot?.length) { title(document, contract, 'Menú contratado'); contract.menuSnapshot.forEach((section: any) => { ensure(document, contract, 35); document.font('Helvetica-Bold').fontSize(9.5).fillColor(color.ink).text(section.title || 'Menú', page.left, document.y); (section.items ?? []).forEach((item: string) => paragraph(document, contract, `• ${item}`)); }); }
  title(document, contract, 'Cláusulas y condiciones'); const clauses = contract.legalTermsSnapshot?.clauses ?? []; if (clauses.length) clauses.forEach((clause: any, index: number) => { ensure(document, contract, 35); document.font('Helvetica-Bold').fontSize(9.5).fillColor(color.ink).text(`${index + 1}. ${text(clause.title, 'Cláusula')}`, page.left, document.y); paragraph(document, contract, text(clause.text, '')); }); else paragraph(document, contract, 'Las partes aceptan las condiciones comerciales y operativas detalladas en este contrato.'); if (text(contract.legalTermsSnapshot?.providerText, '') !== '') { ensure(document, contract, 35); document.font('Helvetica-Bold').fontSize(9.5).fillColor(color.ink).text('Condiciones particulares del salón', page.left, document.y); paragraph(document, contract, text(contract.legalTermsSnapshot?.providerText)); }
  title(document, contract, 'Conformidad'); paragraph(document, contract, 'En prueba de conformidad, las partes firman dos ejemplares de un mismo tenor y a un solo efecto.'); ensure(document, contract, 72); const signY = document.y + 25; document.moveTo(page.left + 28, signY).lineTo(page.left + 215, signY).strokeColor(color.muted).stroke(); document.moveTo(page.left + 287, signY).lineTo(page.right - 28, signY).strokeColor(color.muted).stroke(); document.font('Helvetica').fontSize(8).fillColor(color.muted).text('M&M Eventos · Prestadora', page.left + 28, signY + 8, { width: 187, align: 'center' }); document.text(text(client.fullName, 'Cliente'), page.left + 287, signY + 8, { width: 187, align: 'center' });
  const range = document.bufferedPageRange(); for (let index = 0; index < range.count; index += 1) { document.switchToPage(index); footer(document, index + 1, range.count); }
  return buffer(document);
}

export async function generateAndUploadContractPdf(contract: any): Promise<{ pdfSecureUrl: string; pdfUrl: string; pdfPublicId: string; pdfGeneratedAt: Date }> {
  const pdf = await buildContractPdfBuffer(contract);
  const uploaded = await uploadBuffer(pdf, { folder: `mym-eventos/contracts/${contract._id}`, resource_type: 'raw', public_id: `contrato-${contract.contractNumber}`, overwrite: true, format: 'pdf' });
  return { pdfSecureUrl: uploaded.secureUrl, pdfUrl: uploaded.url, pdfPublicId: uploaded.publicId, pdfGeneratedAt: new Date() };
}
