import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import { uploadBuffer } from '../uploads/cloudinary.service';

const money = (value?: unknown) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(Number(value ?? 0));
// `payment.paidAt` es un instante real (hora de cobro) — se muestra en hora de Argentina (la
// del lector), no en el huso del proceso que generó el PDF.
const date = (value?: unknown) => value ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'long', timeStyle: 'short', timeZone: 'America/Argentina/Buenos_Aires' }).format(new Date(value as string)) : 'No informado';
// `event.eventDate`/`paymentWindowEnd`/`dueDate` son fechas civiles normalizadas a medianoche
// UTC (`civilDateInput`) — sin `timeZone: 'UTC'` explícito, el huso local del proceso corre esa
// medianoche al día anterior. No llevan hora (no tienen una hora real que mostrar).
const civilDate = (value?: unknown) => value ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(value as string)) : 'No informado';
const value = (input?: unknown, fallback = 'No informado') => typeof input === 'string' && input.trim() ? input.trim() : fallback;
const paymentMethod = (method?: string) => ({ cash: 'Efectivo', bank_transfer: 'Transferencia bancaria', mercado_pago: 'Mercado Pago', card: 'Tarjeta', other: 'Otro medio de pago' }[method ?? ''] ?? 'No informado');
function collect(document: PDFKit.PDFDocument): Promise<Buffer> { return new Promise((resolve, reject) => { const chunks: Buffer[] = []; document.on('data', (chunk) => chunks.push(Buffer.from(chunk))); document.on('end', () => resolve(Buffer.concat(chunks))); document.on('error', reject); document.end(); }); }
function logo(document: PDFKit.PDFDocument) { const paths = [path.resolve(process.cwd(), '../web/public/brand/mym-logo-light-on-dark.jpg'), path.resolve(process.cwd(), 'apps/web/public/brand/mym-logo-light-on-dark.jpg')]; const asset = paths.find(fs.existsSync); if (asset) document.image(asset, 46, 24, { width: 72 }); else document.font('Helvetica-Bold').fontSize(14).fillColor('#ffffff').text('M&M EVENTOS', 46, 35); }
function item(document: PDFKit.PDFDocument, label: string, content: unknown, x: number, y: number, width: number) { document.font('Helvetica-Bold').fontSize(7.5).fillColor('#64748b').text(label.toUpperCase(), x, y, { width }); document.font('Helvetica').fontSize(10).fillColor('#101a2c').text(value(content), x, y + 12, { width }); }

export async function generateAndUploadPaymentReceiptPdf(payment: any, event: any, customer: any, contract: any): Promise<{ receiptPdfUrl: string; receiptPdfSecureUrl: string; receiptPdfPublicId: string; receiptPdfGeneratedAt: Date; pdfBuffer: Buffer }> {
  const document = new PDFDocument({ size: 'A4', margin: 0, info: { Title: `Comprobante ${payment.paymentNumber}`, Author: 'M&M Eventos', Subject: 'Comprobante de pago' } });
  document.rect(0, 0, 595.28, 114).fill('#101a2c'); logo(document); document.font('Helvetica').fontSize(8.5).fillColor('#decaa2').text('COMPROBANTE DE PAGO', 300, 34, { width: 249, align: 'right', characterSpacing: 1 }); document.font('Helvetica-Bold').fontSize(15).fillColor('#ffffff').text(payment.paymentNumber, 300, 51, { width: 249, align: 'right' });
  const nextInstallment = (Array.isArray(contract?.paymentPlanSnapshot) ? contract.paymentPlanSnapshot : []).find((item: any) => !['paid', 'cancelled'].includes(item.status) && Number(item.amount || 0) > Number(item.paidAmount || 0));
  document.roundedRect(46, 146, 503, 132, 12).fill('#f5f7fa'); document.font('Helvetica').fontSize(9).fillColor('#64748b').text('IMPORTE RECIBIDO', 68, 169, { characterSpacing: .7 }); document.font('Helvetica-Bold').fontSize(28).fillColor('#101a2c').text(money(payment.amount), 68, 188); document.font('Helvetica').fontSize(9).fillColor('#64748b').text(`Fecha de cobro: ${date(payment.paidAt)}`, 322, 175, { width: 200, align: 'right' }); document.font('Helvetica-Bold').fontSize(9).fillColor('#101a2c').text(`Medio: ${paymentMethod(payment.method)}`, 322, 193, { width: 200, align: 'right' }); document.font('Helvetica').fontSize(9).fillColor('#64748b').text(`Saldo restante: ${money(contract?.balanceAmount)}`, 322, 211, { width: 200, align: 'right' }); document.font('Helvetica').fontSize(8.5).fillColor('#64748b').text(nextInstallment ? `Próxima cuota: ${civilDate(nextInstallment.paymentWindowEnd ?? nextInstallment.dueDate)}` : 'No quedan cuotas pendientes', 322, 229, { width: 200, align: 'right' });
  document.font('Helvetica-Bold').fontSize(12).fillColor('#101a2c').text('Detalle del comprobante', 46, 318); document.moveTo(46, 341).lineTo(549, 341).strokeColor('#b78b45').stroke();
  item(document, 'Cliente', customer?.fullName, 46, 361, 220); item(document, 'Evento', event?.eventName ?? event?.eventType, 300, 361, 249); item(document, 'Contrato', contract?.contractNumber, 46, 408, 220); item(document, 'Fecha del evento', event?.eventDate ? civilDate(event.eventDate) : undefined, 300, 408, 249); item(document, 'Referencia', payment.reference ?? payment.receiptNumber, 46, 455, 220); item(document, 'Próximo vencimiento', nextInstallment ? civilDate(nextInstallment.paymentWindowEnd ?? nextInstallment.dueDate) : 'Sin cuotas pendientes', 300, 455, 249);
  document.roundedRect(46, 520, 503, 84, 10).fill('#f7f1e4'); document.font('Helvetica-Bold').fontSize(9).fillColor('#101a2c').text('OBSERVACIONES', 66, 540); document.font('Helvetica').fontSize(9).fillColor('#374151').text(value(payment.notes, 'Pago registrado correctamente.'), 66, 556, { width: 463, height: 33, ellipsis: true });
  document.font('Helvetica').fontSize(8).fillColor('#64748b').text('Este comprobante acredita la recepción del importe informado por M&M Eventos.', 46, 756, { width: 503, align: 'center' });
  const pdfBuffer = await collect(document); const uploaded = await uploadBuffer(pdfBuffer, { folder: `mym-eventos/payments/${payment._id}`, resource_type: 'raw', public_id: `comprobante-${payment.paymentNumber}`, overwrite: true, format: 'pdf' });
  return { receiptPdfUrl: uploaded.url, receiptPdfSecureUrl: uploaded.secureUrl, receiptPdfPublicId: uploaded.publicId, receiptPdfGeneratedAt: new Date(), pdfBuffer };
}
