'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { Button, Input, PageHeader } from '@/components/ui/primitives';
import { api } from '@/lib/api';
import { useToast } from '@/components/ui/toast-provider';
import { AnalyticsNav } from './analytics-nav';
import { analyticsDeviceLabel, analyticsSectionLabel, analyticsSourceLabel } from './analytics-labels';
type Breakdown = { _id: string; value: number };
type Summary = { metrics: Record<string, number>; funnel: Array<{ id: string; label: string; value: number }>; breakdowns: { sources: Breakdown[]; devices: Breakdown[] } };
type Section = { sectionId: string; views: number; clicks: number; averageEngagementSeconds: number; reachPercentage: number; conversionsAfter: number };
const number = new Intl.NumberFormat('es-AR', { maximumFractionDigits: 1 });
function period() { const p = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Argentina/Buenos_Aires', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()).map((item) => [item.type, item.value])); return { from: `${p.year}-${p.month}-01`, to: `${p.year}-${p.month}-${p.day}` }; }
function Bars({ items, label }: { items: Breakdown[]; label: (value: string) => string }) { const max = Math.max(0, ...items.map((item) => item.value)); return <div className="space-y-3">{items.length ? items.map((item) => <div key={item._id}><div className="mb-1 flex justify-between text-xs"><span>{label(item._id)}</span><span>{number.format(item.value)}</span></div><div className="h-1.5 rounded-full bg-zinc-100"><div className="h-full rounded-full bg-zinc-950" style={{ width: `${max ? item.value / max * 100 : 0}%` }} /></div></div>) : <p className="py-8 text-center text-sm text-zinc-500">Sin datos para el período.</p>}</div>; }
export function AnalyticsOverview() {
  const { showToast } = useToast(); const initial = useMemo(() => period(), []); const [from, setFrom] = useState(initial.from); const [to, setTo] = useState(initial.to); const [summary, setSummary] = useState<Summary | null>(null); const [sections, setSections] = useState<Section[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [s, sectionResponse] = await Promise.all([api.get<Summary>(`/analytics/summary?from=${from}&to=${to}`), api.get<{ items: Section[] }>(`/analytics/sections?from=${from}&to=${to}`)]); setSummary(s); setSections(sectionResponse.items); } catch (cause) { showToast({ message: cause instanceof Error ? cause.message : 'No se pudo cargar analítica.', variant: 'error' }); } finally { setLoading(false); } }, [from, to, showToast]);
  useEffect(() => { void load(); }, [load]);
  const cards = summary ? [
    ['Visitantes', summary.metrics.visitors], ['Sesiones', summary.metrics.sessions], ['Vistas de página', summary.metrics.pageViews], ['Páginas por sesión', summary.metrics.pagesPerSession],
    ['Duración promedio', `${number.format(summary.metrics.averageDurationSeconds)} s`], ['Tasa de rebote', `${number.format(summary.metrics.bounceRate)}%`], ['Tasa de conversión', `${number.format(summary.metrics.conversionRate)}%`], ['Clics en WhatsApp', summary.metrics.whatsappClicks],
    ['Formularios iniciados', summary.metrics.formStarts], ['Consultas enviadas', summary.metrics.formSuccess], ['Errores en formularios', summary.metrics.formErrors], ['Recorrido promedio', `${number.format(summary.metrics.averageScrollDepth)}%`],
  ] : [];
  return <section className="space-y-5"><PageHeader title="Analítica del sitio" description="Resumen anónimo del uso de la página. No registra valores de formularios ni graba sesiones." action={<Button variant="secondary" onClick={() => void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Actualizar</Button>} /><AnalyticsNav /><div className="flex gap-3 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><label className="text-xs font-medium">Desde<Input type="date" className="mt-1.5 w-44" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-xs font-medium">Hasta<Input type="date" className="mt-1.5 w-44" value={to} onChange={(event) => setTo(event.target.value)} /></label></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <article key={String(label)} className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-xs font-medium text-zinc-500">{label}</p><p className="mt-2 text-2xl font-semibold">{typeof value === 'number' ? number.format(value) : value}</p></article>)}</div>
    {summary ? <div className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]"><article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Actividad y resultados</h2><div className="mt-4 grid gap-2 sm:grid-cols-4 lg:grid-cols-8">{summary.funnel.map((item) => <div key={item.id} className="rounded-xl bg-zinc-50 p-3"><p className="text-[11px] leading-4 text-zinc-500">{item.label}</p><p className="mt-2 text-xl font-semibold">{item.value}</p></div>)}</div></article><article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">Dispositivos</h2><Bars items={summary.breakdowns.devices} label={analyticsDeviceLabel} /></article></div> : null}
    <div className="grid gap-4 lg:grid-cols-[1fr_1.5fr]"><article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="mb-4 font-semibold">Origen de las visitas</h2><Bars items={summary?.breakdowns.sources ?? []} label={analyticsSourceLabel} /></article><article className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><header className="border-b border-zinc-100 px-5 py-4"><h2 className="font-semibold">Rendimiento por sección</h2></header><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-zinc-50/80"><tr>{['Sección', 'Vistas', 'Alcance', 'Tiempo promedio', 'Clics', 'Consultas enviadas'].map((label) => <th key={label} className="px-4 py-3 text-left text-xs font-semibold uppercase text-zinc-500">{label}</th>)}</tr></thead><tbody className="divide-y divide-zinc-100">{sections.map((item) => <tr key={item.sectionId}><td className="px-4 py-3 font-semibold">{analyticsSectionLabel(item.sectionId)}</td><td className="px-4 py-3">{item.views}</td><td className="px-4 py-3">{number.format(item.reachPercentage)}%</td><td className="px-4 py-3">{number.format(item.averageEngagementSeconds)} s</td><td className="px-4 py-3">{item.clicks}</td><td className="px-4 py-3">{item.conversionsAfter}</td></tr>)}</tbody></table>{!sections.length ? <p className="p-8 text-center text-sm text-zinc-500">Todavía no hay datos de secciones.</p> : null}</div></article></div>
  </section>;
}
