'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, Input, PageHeader, Select } from '@/components/ui/primitives';
import { api } from '@/lib/api';
import { AnalyticsNav } from './analytics-nav';
type Point = { normalizedX: number; normalizedY: number; sectionId?: string; value: number };
type Response = { points: Point[]; ctas: Array<{ elementId: string; value: number }>; versions: string[] };
function period() { const p = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Argentina/Buenos_Aires', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()).map((item) => [item.type, item.value])); return { from: `${p.year}-${p.month}-01`, to: `${p.year}-${p.month}-${p.day}` }; }
export function AnalyticsHeatmap() {
  const initial = useMemo(() => period(), []); const [from, setFrom] = useState(initial.from); const [to, setTo] = useState(initial.to); const [device, setDevice] = useState('desktop'); const [version, setVersion] = useState(''); const [result, setResult] = useState<Response>({ points: [], ctas: [], versions: [] });
  const load = useCallback(async () => { const query = new URLSearchParams({ from, to, pagePath: '/', deviceType: device }); if (version) query.set('pageVersion', version); setResult(await api.get<Response>(`/analytics/heatmap?${query}`)); }, [from, to, device, version]);
  useEffect(() => { void load(); }, [load]); const max = Math.max(1, ...result.points.map((point) => point.value));
  return <section className="space-y-5"><PageHeader title="Mapa de clics" description="Coordenadas normalizadas y agregadas; no se capturan screenshots, movimientos ni contenido privado." /><AnalyticsNav /><div className="flex flex-wrap gap-3 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><Input type="date" className="w-44" value={from} onChange={(event) => setFrom(event.target.value)} /><Input type="date" className="w-44" value={to} onChange={(event) => setTo(event.target.value)} /><Select className="w-44" value={device} onChange={(event) => setDevice(event.target.value)}><option value="desktop">Desktop</option><option value="tablet">Tablet</option><option value="mobile">Mobile</option></Select><Select className="w-56" value={version} onChange={(event) => setVersion(event.target.value)}><option value="">Todas las versiones</option>{result.versions.map((item) => <option key={item} value={item}>{item}</option>)}</Select><Button variant="secondary" onClick={() => void load()}>Aplicar</Button></div>
    <div className="grid gap-4 xl:grid-cols-[1fr_300px]"><article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className={`relative mx-auto overflow-hidden rounded-xl border border-zinc-200 bg-[linear-gradient(to_bottom,#18181b_0_8%,#f4f4f5_8%_22%,#e4e4e7_22%_40%,#fafafa_40%_65%,#e4e4e7_65%_82%,#f4f4f5_82%_100%)] ${device === 'mobile' ? 'aspect-[9/20] max-w-sm' : device === 'tablet' ? 'aspect-[3/4] max-w-2xl' : 'aspect-[16/20] max-w-4xl'}`}>{result.points.map((point, index) => <span key={`${point.normalizedX}-${point.normalizedY}-${index}`} title={`${point.sectionId || 'Sin sección'}: ${point.value} clics`} className="absolute -translate-x-1/2 -translate-y-1/2 rounded-full border border-red-600/40 bg-red-500/55 shadow-[0_0_24px_rgba(239,68,68,.5)]" style={{ left: `${point.normalizedX * 100}%`, top: `${point.normalizedY * 100}%`, width: `${16 + (point.value / max) * 42}px`, height: `${16 + (point.value / max) * 42}px` }} />)}{!result.points.length ? <span className="absolute inset-0 grid place-items-center text-sm text-zinc-500">No hay clics para estos filtros.</span> : null}</div></article><article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Clics por CTA</h2><div className="mt-4 space-y-2">{result.ctas.map((item) => <div key={item.elementId} className="flex items-center justify-between gap-3 rounded-xl bg-zinc-50 px-3 py-2 text-sm"><span className="truncate">{item.elementId}</span><strong>{item.value}</strong></div>)}</div></article></div>
  </section>;
}
