'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Button, Input, PageHeader } from '@/components/ui/primitives';
import { api } from '@/lib/api';
import { useToast } from '@/components/ui/toast-provider';
import { AnalyticsNav } from './analytics-nav';
type Settings = { enabled: boolean; consentRequired: boolean; retentionDays: number; collectClicks: boolean; collectSectionEngagement: boolean };
export function AnalyticsSettingsWorkspace() {
  const { showToast } = useToast(); const [settings, setSettings] = useState<Settings | null>(null); const [saving, setSaving] = useState(false); const [visitorId, setVisitorId] = useState('');
  useEffect(() => { void api.get<{ settings: Settings }>('/analytics/settings').then((result) => setSettings(result.settings)); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); if (!settings) return; setSaving(true); try { const result = await api.patch<{ settings: Settings }>('/analytics/settings', settings); setSettings(result.settings); showToast({ message: 'Configuración guardada.', variant: 'success' }); } catch (cause) { showToast({ message: cause instanceof Error ? cause.message : 'No se pudo guardar.', variant: 'error' }); } finally { setSaving(false); } };
  const remove = async () => { if (!visitorId.trim()) return; if (!confirm('¿Eliminar los eventos y sesiones de este identificador anónimo?')) return; try { await api.delete(`/analytics/visitor/${encodeURIComponent(visitorId.trim())}`); setVisitorId(''); showToast({ message: 'Datos del visitante eliminados.', variant: 'success' }); } catch (cause) { showToast({ message: cause instanceof Error ? cause.message : 'No se pudieron eliminar.', variant: 'error' }); } };
  return <section className="space-y-5"><PageHeader title="Privacidad y retención" description="Controlá la recolección first-party y atendé solicitudes de eliminación por identificador anónimo." /><AnalyticsNav />{settings ? <form onSubmit={save} className="grid gap-5 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm sm:grid-cols-2"><label className="flex items-start gap-3 rounded-xl border border-zinc-200 p-4"><input type="checkbox" checked={settings.enabled} onChange={(event) => setSettings({ ...settings, enabled: event.target.checked })} /><span><strong className="block text-sm">Analítica habilitada</strong><span className="text-xs text-zinc-500">Detiene toda recolección si se desactiva.</span></span></label><label className="flex items-start gap-3 rounded-xl border border-zinc-200 p-4"><input type="checkbox" checked={settings.consentRequired} onChange={(event) => setSettings({ ...settings, consentRequired: event.target.checked })} /><span><strong className="block text-sm">Solicitar consentimiento</strong><span className="text-xs text-zinc-500">No inicia el tracker opcional hasta aceptar.</span></span></label><label className="flex items-start gap-3 rounded-xl border border-zinc-200 p-4"><input type="checkbox" checked={settings.collectClicks} onChange={(event) => setSettings({ ...settings, collectClicks: event.target.checked })} /><span><strong className="block text-sm">Clics normalizados</strong><span className="text-xs text-zinc-500">Sin captura de pantalla ni movimiento del mouse.</span></span></label><label className="flex items-start gap-3 rounded-xl border border-zinc-200 p-4"><input type="checkbox" checked={settings.collectSectionEngagement} onChange={(event) => setSettings({ ...settings, collectSectionEngagement: event.target.checked })} /><span><strong className="block text-sm">Interacción por sección</strong><span className="text-xs text-zinc-500">Usa visibilidad agregada con umbral.</span></span></label><label className="text-sm font-medium">Retención en días<Input type="number" min="7" max="730" value={settings.retentionDays} onChange={(event) => setSettings({ ...settings, retentionDays: Number(event.target.value) })} className="mt-1.5" /></label><footer className="sm:col-span-2 flex justify-end"><Button disabled={saving}>{saving ? 'Guardando…' : 'Guardar configuración'}</Button></footer></form> : <p className="rounded-2xl border border-zinc-200 bg-white p-6 text-sm text-zinc-500">Cargando configuración…</p>}
    <article className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">Derecho de eliminación</h2><p className="mt-1 text-sm text-zinc-500">El identificador es aleatorio y no contiene email, teléfono ni DNI.</p><div className="mt-4 flex gap-3"><Input value={visitorId} onChange={(event) => setVisitorId(event.target.value)} placeholder="Identificador anónimo" /><Button type="button" variant="danger" onClick={() => void remove()}>Eliminar datos</Button></div></article>
  </section>;
}
