'use client';
/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Info, RefreshCw } from 'lucide-react';
import { Button, Input, PageHeader } from '@/components/ui/primitives';
import { Tooltip } from '@/components/ui/tooltip';
import { api } from '@/lib/api';
import { useToast } from '@/components/ui/toast-provider';
import { AnalyticsNav } from './analytics-nav';
import { analyticsDeviceLabel, analyticsSectionLabel, analyticsSourceLabel } from './analytics-labels';
type Breakdown = { _id: string; value: number };
type Summary = { metrics: Record<string, number>; funnel: Array<{ id: string; label: string; value: number }>; breakdowns: { sources: Breakdown[]; devices: Breakdown[] } };
type Section = { sectionId: string; views: number; clicks: number; averageEngagementSeconds: number; reachPercentage: number; conversionsAfter: number };
type Metric = { label: string; value: string | number; help: string };
const number = new Intl.NumberFormat('es-AR', { maximumFractionDigits: 1 });
const metricHelp: Record<string, string> = {
  Visitantes: 'Cantidad de personas anónimas diferentes que visitaron el sitio durante el período elegido.',
  Sesiones: 'Cantidad de visitas al sitio. Una misma persona puede generar más de una sesión si vuelve otro día o inicia una nueva visita.',
  'Vistas de página': 'Cantidad total de veces que se cargó una página del sitio. Incluye varias vistas de una misma persona.',
  'Páginas por sesión': 'Promedio de páginas vistas en cada visita. Un valor más alto suele indicar que las personas exploran más contenido.',
  'Duración promedio': 'Tiempo promedio entre el inicio y la última actividad registrada en cada visita.',
  'Tasa de rebote': 'Porcentaje de visitas que vieron una sola página y no enviaron una consulta. No significa necesariamente que la experiencia haya sido mala.',
  'Tasa de conversión': 'Porcentaje de visitas que terminaron enviando una consulta mediante el formulario.',
  'Clics en WhatsApp': 'Cantidad de veces que se seleccionó un enlace o botón para iniciar una conversación por WhatsApp.',
  'Formularios iniciados': 'Cantidad de visitas en las que una persona comenzó a completar un formulario.',
  'Consultas enviadas': 'Cantidad de formularios enviados correctamente durante el período seleccionado.',
  'Errores en formularios': 'Cantidad de veces que el formulario informó un problema al intentar enviarse o completarse.',
  'Recorrido promedio': 'Porcentaje promedio de la página que las personas alcanzaron al desplazarse. Ayuda a saber cuánto contenido llegaron a ver.',
};
const funnelHelp: Record<string, string> = {
  landing: 'Cantidad de sesiones registradas en el sitio durante el período elegido.',
  sections: 'Cantidad de veces que una sección de la página llegó a estar visible para una persona.',
  cta: 'Cantidad de clics en botones principales que invitan a realizar una acción.',
  formStart: 'Cantidad de veces que una persona comenzó a completar el formulario de consulta.',
  lead: 'Cantidad de formularios enviados correctamente.',
  quote: 'Cantidad de presupuestos creados a partir de consultas vinculadas a estas visitas.',
  accepted: 'Cantidad de esos presupuestos que fueron aceptados.',
  confirmed: 'Cantidad de eventos confirmados a partir de esos presupuestos.',
};
function period() { const p = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Argentina/Buenos_Aires', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()).map((item) => [item.type, item.value])); return { from: `${p.year}-${p.month}-01`, to: `${p.year}-${p.month}-${p.day}` }; }
function Bars({ items, label }: { items: Breakdown[]; label: (value: string) => string }) { const max = Math.max(0, ...items.map((item) => item.value)); return <div className="space-y-3">{items.length ? items.map((item) => <div key={item._id}><div className="mb-1 flex justify-between text-xs"><span>{label(item._id)}</span><span>{number.format(item.value)}</span></div><div className="h-1.5 rounded-full bg-zinc-100"><div className="h-full rounded-full bg-zinc-950" style={{ width: `${max ? item.value / max * 100 : 0}%` }} /></div></div>) : <p className="py-8 text-center text-sm text-zinc-500">Sin datos para el período.</p>}</div>; }
function HelpTooltip({ label, help }: { label: string; help: string }) { return <Tooltip label={help}><button type="button" aria-label={`Más información sobre ${label}`} className="rounded-full p-1 text-zinc-400 transition-colors hover:bg-zinc-100 hover:text-zinc-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-500 focus-visible:ring-offset-1"><Info className="h-3.5 w-3.5" aria-hidden="true" /></button></Tooltip>; }
export function AnalyticsOverview() {
  const { showToast } = useToast(); const initial = useMemo(() => period(), []); const [from, setFrom] = useState(initial.from); const [to, setTo] = useState(initial.to); const [summary, setSummary] = useState<Summary | null>(null); const [sections, setSections] = useState<Section[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [s, sectionResponse] = await Promise.all([api.get<Summary>(`/analytics/summary?from=${from}&to=${to}`), api.get<{ items: Section[] }>(`/analytics/sections?from=${from}&to=${to}`)]); setSummary(s); setSections(sectionResponse.items); } catch (cause) { showToast({ message: cause instanceof Error ? cause.message : 'No se pudo cargar analítica.', variant: 'error' }); } finally { setLoading(false); } }, [from, to, showToast]);
  useEffect(() => { void load(); }, [load]);
  const cards: Metric[] = summary ? [
    { label: 'Visitantes', value: summary.metrics.visitors, help: metricHelp.Visitantes }, { label: 'Sesiones', value: summary.metrics.sessions, help: metricHelp.Sesiones }, { label: 'Vistas de página', value: summary.metrics.pageViews, help: metricHelp['Vistas de página'] }, { label: 'Páginas por sesión', value: summary.metrics.pagesPerSession, help: metricHelp['Páginas por sesión'] },
    { label: 'Duración promedio', value: `${number.format(summary.metrics.averageDurationSeconds)} s`, help: metricHelp['Duración promedio'] }, { label: 'Tasa de rebote', value: `${number.format(summary.metrics.bounceRate)}%`, help: metricHelp['Tasa de rebote'] }, { label: 'Tasa de conversión', value: `${number.format(summary.metrics.conversionRate)}%`, help: metricHelp['Tasa de conversión'] }, { label: 'Clics en WhatsApp', value: summary.metrics.whatsappClicks, help: metricHelp['Clics en WhatsApp'] },
    { label: 'Formularios iniciados', value: summary.metrics.formStarts, help: metricHelp['Formularios iniciados'] }, { label: 'Consultas enviadas', value: summary.metrics.formSuccess, help: metricHelp['Consultas enviadas'] }, { label: 'Errores en formularios', value: summary.metrics.formErrors, help: metricHelp['Errores en formularios'] }, { label: 'Recorrido promedio', value: `${number.format(summary.metrics.averageScrollDepth)}%`, help: metricHelp['Recorrido promedio'] },
  ] : [];
  return <section className="space-y-5"><PageHeader title="Analítica del sitio" description="Resumen anónimo del uso de la página. No registra valores de formularios ni graba sesiones." action={<Button variant="secondary" onClick={() => void load()} disabled={loading}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Actualizar</Button>} /><AnalyticsNav /><div className="flex gap-3 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><label className="text-xs font-medium">Desde<Input type="date" className="mt-1.5 w-44" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-xs font-medium">Hasta<Input type="date" className="mt-1.5 w-44" value={to} onChange={(event) => setTo(event.target.value)} /></label></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(({ label, value, help }) => <article key={label} className="relative rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><div className="absolute right-3 top-3"><HelpTooltip label={label} help={help} /></div><p className="pr-6 text-xs font-medium text-zinc-500">{label}</p><p className="mt-2 text-2xl font-semibold">{typeof value === 'number' ? number.format(value) : value}</p></article>)}</div>
    {summary ? <div className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]"><article className="relative rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="absolute right-4 top-4"><HelpTooltip label="Actividad y resultados" help="Embudo que muestra el recorrido desde las visitas hasta los eventos confirmados. Cada valor cuenta acciones registradas durante el período." /></div><h2 className="pr-8 font-semibold">Actividad y resultados</h2><div className="mt-4 grid gap-2 sm:grid-cols-4 lg:grid-cols-8">{summary.funnel.map((item) => <div key={item.id} className="relative rounded-xl bg-zinc-50 p-3"><div className="absolute right-2 top-2"><HelpTooltip label={item.label} help={funnelHelp[item.id] ?? 'Cantidad registrada para esta etapa del recorrido.'} /></div><p className="pr-5 text-[11px] leading-4 text-zinc-500">{item.label}</p><p className="mt-2 text-xl font-semibold">{item.value}</p></div>)}</div></article><article className="relative rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="absolute right-4 top-4"><HelpTooltip label="Dispositivos" help="Distribución de las sesiones según el tipo de dispositivo usado, como computadora o celular." /></div><h2 className="mb-4 pr-8 font-semibold">Dispositivos</h2><Bars items={summary.breakdowns.devices} label={analyticsDeviceLabel} /></article></div> : null}
    <div className="grid gap-4 lg:grid-cols-[1fr_1.5fr]"><article className="relative rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><div className="absolute right-4 top-4"><HelpTooltip label="Origen de las visitas" help="Muestra desde dónde se inició cada sesión, por ejemplo, acceso directo o una campaña identificada." /></div><h2 className="mb-4 pr-8 font-semibold">Origen de las visitas</h2><Bars items={summary?.breakdowns.sources ?? []} label={analyticsSourceLabel} /></article><article className="relative overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><div className="absolute right-4 top-3 z-10"><HelpTooltip label="Rendimiento por sección" help="Compara cómo interactúan las personas con cada sección: cuántas la ven, hasta dónde llegan, cuánto tiempo permanecen y qué acciones realizan." /></div><header className="border-b border-zinc-100 px-5 py-4"><h2 className="pr-8 font-semibold">Rendimiento por sección</h2></header><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-zinc-50/80"><tr>{['Sección', 'Vistas', 'Alcance', 'Tiempo promedio', 'Clics', 'Consultas enviadas'].map((label) => <th key={label} className="px-4 py-3 text-left text-xs font-semibold uppercase text-zinc-500">{label}</th>)}</tr></thead><tbody className="divide-y divide-zinc-100">{sections.map((item) => <tr key={item.sectionId}><td className="px-4 py-3 font-semibold">{analyticsSectionLabel(item.sectionId)}</td><td className="px-4 py-3">{item.views}</td><td className="px-4 py-3">{number.format(item.reachPercentage)}%</td><td className="px-4 py-3">{number.format(item.averageEngagementSeconds)} s</td><td className="px-4 py-3">{item.clicks}</td><td className="px-4 py-3">{item.conversionsAfter}</td></tr>)}</tbody></table>{!sections.length ? <p className="p-8 text-center text-sm text-zinc-500">Todavía no hay datos de secciones.</p> : null}</div></article></div>
  </section>;
}
