'use client';
/* eslint-disable react-hooks/set-state-in-effect */

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, RefreshCw } from 'lucide-react';
import { Button, Input, PageHeader } from '@/components/ui/primitives';
import { api } from '@/lib/api';
import { useToast } from '@/components/ui/toast-provider';
import { ExpensesNav } from './expenses-nav';

type CostStatus = 'no_expenses' | 'pending' | 'preliminary' | 'complete';
type Row = { id: string; href: string; eventName: string; eventDate: string; customer: string; salon: string; guests: number; contractedRevenue: number; collectedRevenue: number; estimatedCost: number; actualCost: number; paidCost: number; estimatedMargin: number; economicMargin: number; cashResult: number; marginPercentage: number | null; costPerGuest: number | null; revenuePerGuest: number | null; costDeviation: number; expenseCount: number; pendingExpenseCount: number; costStatus: CostStatus; complete: boolean };
type Summary = { contractedRevenue: number; collectedRevenue: number; estimatedCost: number; actualCost: number; paidCost: number; estimatedMargin: number; economicMargin: number; cashResult: number; incompleteEvents: number };
type Response = { items: Row[]; summary: Summary };
const money = new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 });
const number = new Intl.NumberFormat('es-AR', { maximumFractionDigits: 1 });
// `eventDate` es una fecha civil normalizada a medianoche UTC — se formatea en UTC para no
// correrla un día para atrás.
const date = new Intl.DateTimeFormat('es-AR', { timeZone: 'UTC', dateStyle: 'short' });
const costStatusLabel: Record<CostStatus, string> = { no_expenses: 'Sin gastos', pending: 'Con gastos pendientes', preliminary: 'Preliminar', complete: 'Completa' };
function initialPeriod() { const p = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Argentina/Buenos_Aires', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()).map((part) => [part.type, part.value])); const last = new Date(Date.UTC(Number(p.year), Number(p.month), 0)).getUTCDate(); return { from: `${p.year}-${p.month}-01`, to: `${p.year}-${p.month}-${last}` }; }

export function ProfitabilityWorkspace() {
  const { showToast } = useToast(); const initial = useMemo(() => initialPeriod(), []);
  const [from, setFrom] = useState(initial.from); const [to, setTo] = useState(initial.to); const [result, setResult] = useState<Response | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setResult(await api.get<Response>(`/expenses/profitability/events?from=${from}&to=${to}`)); } catch (cause) { showToast({ message: cause instanceof Error ? cause.message : 'No se pudo calcular rentabilidad.', variant: 'error' }); } finally { setLoading(false); } }, [from, to, showToast]);
  useEffect(() => { void load(); }, [load]);
  return <section className="space-y-5">
    <PageHeader title="Rentabilidad por evento" description="Margen económico y movimiento de caja se muestran por separado para no confundir cobros pendientes con pérdidas." action={<Button variant="secondary" disabled={loading} onClick={() => void load()}><RefreshCw className={`mr-2 h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Actualizar</Button>} />
    <ExpensesNav />
    <div className="flex flex-wrap gap-3 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><label className="text-xs font-medium">Desde<Input className="mt-1.5 w-44" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-xs font-medium">Hasta<Input className="mt-1.5 w-44" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></div>
    {result ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><article className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-xs text-zinc-500">Ingreso contratado</p><p className="mt-2 text-2xl font-semibold">{money.format(result.summary.contractedRevenue)}</p></article><article className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-xs text-zinc-500">Ingreso cobrado</p><p className="mt-2 text-2xl font-semibold">{money.format(result.summary.collectedRevenue)}</p></article><article className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><p className="text-xs text-zinc-500">Costo real registrado</p><p className="mt-2 text-2xl font-semibold">{money.format(result.summary.actualCost)}</p></article><article className={`rounded-2xl border p-4 shadow-sm ${result.summary.economicMargin >= 0 ? 'border-emerald-200 bg-emerald-50' : 'border-red-200 bg-red-50'}`}><p className="text-xs text-zinc-600">Margen económico</p><p className="mt-2 text-2xl font-semibold">{money.format(result.summary.economicMargin)}</p></article><article className={`rounded-2xl border p-4 shadow-sm ${result.summary.cashResult >= 0 ? 'border-sky-200 bg-sky-50' : 'border-amber-200 bg-amber-50'}`}><p className="text-xs text-zinc-600">Resultado de caja</p><p className="mt-2 text-2xl font-semibold">{money.format(result.summary.cashResult)}</p></article></div>{result.summary.incompleteEvents ? <div className="flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><AlertTriangle className="h-5 w-5 shrink-0" /><strong>Hay {result.summary.incompleteEvents} evento(s) con costos preliminares, pendientes o sin gastos cargados.</strong></div> : null}</> : null}
    <article className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm">{result ? <div className="overflow-x-auto"><table className="min-w-[1540px] w-full text-sm"><thead className="border-b border-zinc-200 bg-zinc-50/80"><tr>{['Evento', 'Fecha / salón', 'Invitados', 'Contratado', 'Cobrado', 'Costo estimado', 'Costo real', 'Costo pagado', 'Margen estimado', 'Margen económico', 'Resultado caja', 'Margen %', 'Costo/invitado', 'Ingreso/invitado', 'Desvío costo', 'Calidad'].map((label) => <th key={label} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wide text-zinc-500">{label}</th>)}</tr></thead><tbody className="divide-y divide-zinc-100">{result.items.map((item) => <tr key={item.id} className={!item.complete ? 'bg-amber-50/35' : ''}><td className="px-4 py-3"><Link href={item.href} className="inline-flex items-center gap-2 font-semibold underline">{item.eventName}<ArrowRight className="h-3.5 w-3.5" /></Link><span className="block text-xs text-zinc-500">{item.customer}</span></td><td className="px-4 py-3">{date.format(new Date(item.eventDate))}<span className="block text-xs text-zinc-500">{item.salon}</span></td><td className="px-4 py-3">{item.guests}</td>{[item.contractedRevenue, item.collectedRevenue, item.estimatedCost, item.actualCost, item.paidCost, item.estimatedMargin, item.economicMargin, item.cashResult].map((value, index) => <td key={index} className="px-4 py-3 tabular-nums">{money.format(value)}</td>)}<td className="px-4 py-3">{item.marginPercentage === null ? '—' : `${number.format(item.marginPercentage)}%`}</td><td className="px-4 py-3">{item.costPerGuest === null ? '—' : money.format(item.costPerGuest)}</td><td className="px-4 py-3">{item.revenuePerGuest === null ? '—' : money.format(item.revenuePerGuest)}</td><td className={`px-4 py-3 ${item.costDeviation > 0 ? 'text-red-700' : 'text-emerald-700'}`}>{money.format(item.costDeviation)}</td><td className="px-4 py-3"><span className={item.complete ? 'text-emerald-700' : 'font-medium text-amber-800'}>{costStatusLabel[item.costStatus]}</span>{item.pendingExpenseCount ? <span className="block text-xs text-zinc-500">{item.pendingExpenseCount} pendiente(s)</span> : null}</td></tr>)}</tbody></table>{!result.items.length ? <div className="grid min-h-52 place-items-center text-sm text-zinc-500">No hay eventos en el período.</div> : null}</div> : <div className="p-8 text-sm text-zinc-500">Calculando rentabilidad…</div>}</article>
  </section>;
}
