import { Router } from 'express'; import authRoutes from '../modules/auth/auth.routes'; import userRoutes from '../modules/users/user.routes'; import staffRoutes from '../modules/users/staff.routes'; import salonRoutes from '../modules/salons/salon.routes'; import settingsRoutes from '../modules/settings/settings.routes'; import notificationRoutes from '../modules/notifications/notification.routes'; import landingRoutes from '../modules/landing/landing.routes'; import supplierRoutes from '../modules/operations/suppliers.routes'; import leadRoutes from '../modules/crm/leads.routes'; import customerRoutes from '../modules/crm/customers.routes'; import quoteRoutes from '../modules/crm/quotes.routes'; import quoteRequestRoutes from '../modules/crm/quote-requests.routes'; import eventRoutes from '../modules/crm/events.routes'; import calendarItemRoutes from '../modules/crm/calendar-items.routes'; import contractRoutes from '../modules/crm/contracts.routes'; import paymentRoutes from '../modules/crm/payments.routes'; import publicRoutes from '../modules/crm/public.routes'; import uploadRoutes from '../modules/uploads/uploads.routes'; import invitationRoutes, { publicInvitationRoutes } from '../modules/invitations/invitation.routes'; import { ticketRoutes, publicTicketRoutes } from '../modules/tickets/ticket.routes'; import marketingRoutes from '../modules/marketing/marketing.routes'; import publicMarketingUnsubscribeRoutes from '../modules/marketing/unsubscribe.routes'; import { publicRateLimit } from '../middlewares/publicRateLimit';
import mobileAuthRoutes from '../modules/mobile/mobile-auth.routes'; import mobileProfileRoutes, { mobileDevicePushRoutes } from '../modules/mobile/mobile-profile.routes'; import mobileAttendanceRoutes from '../modules/attendance/mobile-attendance.routes'; import mobileScheduleRoutes from '../modules/attendance/mobile-schedule.routes'; import adminAttendanceRoutes from '../modules/attendance/admin-attendance.routes';
import dashboardRoutes from '../modules/reporting/dashboard.routes';
import reportRoutes from '../modules/reporting/reports.routes';
import productionRoutes from '../modules/production/production.routes';
import expenseRoutes from '../modules/expenses/expenses.routes';
import analyticsRoutes, { publicAnalyticsRoutes } from '../modules/analytics/analytics.routes';
import importRoutes from '../modules/imports/imports.routes';
const router = Router(); router.use('/auth', authRoutes); router.use('/users', userRoutes); router.use('/staff', staffRoutes); router.use('/salons', salonRoutes); router.use('/settings', settingsRoutes); router.use('/notifications', notificationRoutes); router.use('/landing', landingRoutes); router.use('/suppliers', supplierRoutes); router.use('/leads',leadRoutes); router.use('/customers', customerRoutes); router.use('/quote-requests', quoteRequestRoutes); router.use('/quotes', quoteRoutes); router.use('/events', eventRoutes); router.use('/calendar-items', calendarItemRoutes); router.use('/contracts', contractRoutes); router.use('/payments', paymentRoutes); router.use('/dashboard', dashboardRoutes); router.use('/reports', reportRoutes); router.use('/production', productionRoutes); router.use('/expenses', expenseRoutes); router.use('/analytics', analyticsRoutes); router.use('/imports', importRoutes); router.use('/uploads', uploadRoutes); router.use('/invitations', invitationRoutes); router.use('/tickets', ticketRoutes); router.use('/marketing', marketingRoutes); router.use('/mobile/auth', mobileAuthRoutes); router.use('/mobile/me', mobileProfileRoutes); router.use('/mobile/devices', mobileDevicePushRoutes); router.use('/mobile/attendance', mobileAttendanceRoutes); router.use('/mobile/schedule', mobileScheduleRoutes); router.use('/attendance', adminAttendanceRoutes); router.use('/public/analytics', publicRateLimit({ windowMs: 60_000, max: 120 }), publicAnalyticsRoutes); router.use('/public/invitations', publicRateLimit({ windowMs: 60_000, max: 30 }), publicInvitationRoutes); router.use('/public', publicRateLimit({ windowMs: 60_000, max: 40 }), publicTicketRoutes); router.use('/public/marketing/unsubscribe', publicRateLimit({ windowMs: 60_000, max: 20 }), publicMarketingUnsubscribeRoutes); router.use('/public',publicRoutes); export default router;
