'use client';

/* eslint-disable react-hooks/set-state-in-effect */

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Boxes, Pencil, Plus, SlidersHorizontal, Trash2 } from 'lucide-react';
import { Button, Input, Modal, PageHeader, Select, Textarea } from '@/components/ui/primitives';
import { TableActionButton } from '@/components/admin/table-action-button';
import { useToast } from '@/components/ui/toast-provider';
import { api } from '@/lib/api';
import { displayLabel, inventoryAdjustmentTypeLabels, inventoryCategoryLabels, inventoryItemTypeLabels } from '@/lib/display-labels';

type Salon = { _id: string; name: string };
type CatalogItem = { _id: string; name: string };
type InventoryItem = { _id: string; name: string; type: string; category: string; salonId?: string | Salon; unitOfMeasure: string; currentQuantity: number; reservedQuantity?: number; minimumQuantity?: number; replacementCost?: number; active?: boolean };
const empty = { name: '', type: 'CONSUMABLE', category: 'BEVERAGE', catalogItemId: '', salonId: '', unitOfMeasure: 'unidad', currentQuantity: '0', minimumQuantity: '0', replacementCost: '', rentalPrice: '', notes: '', active: true };
const money = (value?: number) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(value ?? 0);
const entityName = (value: unknown) => typeof value === 'string' ? '' : (value as { name?: string } | undefined)?.name ?? '';

export default function InventoryPage() {
  const { showToast } = useToast();
  const [tab, setTab] = useState<'CONSUMABLE' | 'NON_CONSUMABLE' | 'MOVEMENTS'>('CONSUMABLE');
  const [items, setItems] = useState<InventoryItem[]>([]);
  const [salons, setSalons] = useState<Salon[]>([]);
  const [catalog, setCatalog] = useState<CatalogItem[]>([]);
  const [form, setForm] = useState(empty);
  const [editing, setEditing] = useState<InventoryItem | null | undefined>();
  const [adjusting, setAdjusting] = useState<InventoryItem | null>(null);
  const [adjustment, setAdjustment] = useState({ type: 'IN', quantity: '', reason: '', notes: '' });
  const load = useCallback(async () => {
    try {
      const [inventoryResponse, salonsResponse, catalogResponse] = await Promise.all([api.get<{ items: InventoryItem[] }>('/inventory'), api.get<{ salons: Salon[] }>('/salons?active=true'), api.get<{ items: CatalogItem[] }>('/catalog/items?active=true')]);
      setItems(inventoryResponse.items); setSalons(salonsResponse.salons ?? []); setCatalog(catalogResponse.items ?? []);
    } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo cargar stock.', variant: 'error' }); }
  }, [showToast]);
  useEffect(() => { void load(); }, [load]);
  const visibleItems = tab === 'MOVEMENTS' ? items : items.filter((item) => item.type === tab);
  const open = (item?: InventoryItem) => { setEditing(item ?? null); setForm(item ? { ...empty, ...item, currentQuantity: String(item.currentQuantity ?? 0), minimumQuantity: String(item.minimumQuantity ?? 0), replacementCost: String(item.replacementCost ?? ''), salonId: typeof item.salonId === 'string' ? item.salonId : item.salonId?._id ?? '' } : empty); };
  async function save(event: FormEvent) { event.preventDefault(); const body = { ...form, currentQuantity: Number(form.currentQuantity), minimumQuantity: Number(form.minimumQuantity), replacementCost: Number(form.replacementCost) || undefined, rentalPrice: Number(form.rentalPrice) || undefined }; try { if (editing) await api.patch(`/inventory/${editing._id}`, body); else await api.post('/inventory', body); setEditing(undefined); await load(); showToast({ message: 'Item guardado.', variant: 'success' }); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo guardar.', variant: 'error' }); } }
  async function adjust(event: FormEvent) { event.preventDefault(); if (!adjusting) return; try { await api.post(`/inventory/${adjusting._id}/adjust`, { ...adjustment, quantity: Number(adjustment.quantity) }); setAdjusting(null); await load(); showToast({ message: 'Stock ajustado.', variant: 'success' }); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo ajustar stock.', variant: 'error' }); } }
  async function remove(item: InventoryItem) { try { await api.delete(`/inventory/${item._id}`); await load(); showToast({ message: 'Item eliminado.', variant: 'success' }); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo eliminar.', variant: 'error' }); } }
  return <section className="space-y-6"><PageHeader title="Stock" description="Inventario base, consumibles, vajilla, mantelería, materiales y movimientos." action={<Button onClick={() => open()}><Plus className="mr-2 h-4 w-4" />Nuevo item</Button>} />
    <div className="flex flex-wrap gap-2 border-b border-zinc-200">{[['CONSUMABLE','Consumibles'],['NON_CONSUMABLE','Vajilla / Materiales'],['MOVEMENTS','Movimientos']].map(([key,label]) => <button key={key} onClick={() => setTab(key as typeof tab)} className={`px-4 py-3 text-sm font-medium ${tab === key ? 'border-b-2 border-zinc-950 text-zinc-950' : 'text-zinc-500'}`}>{label}</button>)}</div>
    <article className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead className="border-b bg-zinc-50/80 text-zinc-500"><tr>{['Item','Categoría','Salón','Disponible','Reservado','Mínimo','Costo reposición','Estado'].map((h) => <th key={h} className="px-5 py-3.5 text-left text-xs font-semibold uppercase">{h}</th>)}<th className="px-5 py-3.5 text-right text-xs font-semibold uppercase">Acciones</th></tr></thead><tbody className="divide-y divide-zinc-100">{visibleItems.map((item) => <tr key={item._id} className="hover:bg-amber-50/35"><td className="px-5 py-4 font-semibold">{item.name}</td><td className="px-5 py-4">{displayLabel(inventoryCategoryLabels, item.category)}</td><td className="px-5 py-4">{entityName(item.salonId) || 'General'}</td><td className="px-5 py-4">{item.currentQuantity} {item.unitOfMeasure}</td><td className="px-5 py-4">{item.reservedQuantity ?? 0}</td><td className="px-5 py-4">{item.minimumQuantity ?? 0}</td><td className="px-5 py-4">{money(item.replacementCost)}</td><td className="px-5 py-4">{item.active === false ? 'Inactivo' : 'Activo'}</td><td className="px-5 py-4"><div className="flex justify-end"><TableActionButton icon={SlidersHorizontal} label="Ajustar stock" onClick={() => setAdjusting(item)} /><TableActionButton icon={Pencil} label="Editar" onClick={() => open(item)} /><TableActionButton icon={Trash2} label="Eliminar" onClick={() => void remove(item)} /></div></td></tr>)}</tbody></table>{!visibleItems.length ? <div className="grid place-items-center px-6 py-16 text-center"><Boxes className="h-10 w-10 text-zinc-300" /><p className="mt-3 text-sm text-zinc-500">No hay items de stock para mostrar.</p></div> : null}</div></article>
    <Modal open={editing !== undefined} title={editing ? 'Editar stock' : 'Nuevo stock'} onClose={() => setEditing(undefined)}><form onSubmit={save} className="grid gap-3 p-6 md:grid-cols-2"><Input required placeholder="Nombre" value={form.name} onChange={(e) => setForm((c) => ({ ...c, name: e.target.value }))} /><Select value={form.type} onChange={(e) => setForm((c) => ({ ...c, type: e.target.value }))}>{Object.entries(inventoryItemTypeLabels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</Select><Select value={form.category} onChange={(e) => setForm((c) => ({ ...c, category: e.target.value }))}>{Object.entries(inventoryCategoryLabels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</Select><Select value={form.catalogItemId} onChange={(e) => setForm((c) => ({ ...c, catalogItemId: e.target.value }))}><option value="">Sin producto catálogo</option>{catalog.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select><Select value={form.salonId} onChange={(e) => setForm((c) => ({ ...c, salonId: e.target.value }))}><option value="">General</option>{salons.map((salon) => <option key={salon._id} value={salon._id}>{salon.name}</option>)}</Select><Input placeholder="Unidad" value={form.unitOfMeasure} onChange={(e) => setForm((c) => ({ ...c, unitOfMeasure: e.target.value }))} /><Input placeholder="Cantidad actual" value={form.currentQuantity} onChange={(e) => setForm((c) => ({ ...c, currentQuantity: e.target.value }))} /><Input placeholder="Mínimo" value={form.minimumQuantity} onChange={(e) => setForm((c) => ({ ...c, minimumQuantity: e.target.value }))} /><Input placeholder="Costo reposición" value={form.replacementCost} onChange={(e) => setForm((c) => ({ ...c, replacementCost: e.target.value }))} /><Textarea className="md:col-span-2" placeholder="Notas" value={form.notes} onChange={(e) => setForm((c) => ({ ...c, notes: e.target.value }))} /><Footer onClose={() => setEditing(undefined)} /></form></Modal>
    <Modal open={Boolean(adjusting)} title="Ajustar stock" onClose={() => setAdjusting(null)}><form onSubmit={adjust} className="grid gap-3 p-6"><Select value={adjustment.type} onChange={(e) => setAdjustment((c) => ({ ...c, type: e.target.value }))}>{Object.entries(inventoryAdjustmentTypeLabels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</Select><Input required placeholder="Cantidad" value={adjustment.quantity} onChange={(e) => setAdjustment((c) => ({ ...c, quantity: e.target.value }))} /><Input placeholder="Motivo" value={adjustment.reason} onChange={(e) => setAdjustment((c) => ({ ...c, reason: e.target.value }))} /><Textarea placeholder="Notas" value={adjustment.notes} onChange={(e) => setAdjustment((c) => ({ ...c, notes: e.target.value }))} /><Footer onClose={() => setAdjusting(null)} /></form></Modal>
  </section>;
}
function Footer({ onClose }: { onClose: () => void }) { return <footer className="flex justify-end gap-2 border-t pt-4 md:col-span-2"><Button type="button" variant="secondary" onClick={onClose}>Cancelar</Button><Button>Guardar</Button></footer>; }
