'use client';

/* eslint-disable react-hooks/set-state-in-effect */

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Calculator, Pencil, Plus, Trash2 } from 'lucide-react';
import { Button, Input, Modal, PageHeader, Select, Textarea } from '@/components/ui/primitives';
import { TableActionButton } from '@/components/admin/table-action-button';
import { useToast } from '@/components/ui/toast-provider';
import { api } from '@/lib/api';
import { consumptionRuleTargetLabels, displayLabel, roundingModeLabels } from '@/lib/display-labels';

type CatalogItem = { _id: string; name: string };
type ServiceExtra = { _id: string; name: string };
type Rule = { _id: string; name: string; catalogItemId?: string | CatalogItem; serviceExtraId?: string | ServiceExtra; target: string; quantityPerTarget: number; unitOfMeasure: string; minimumQuantity?: number; roundingMode: string; active?: boolean };
const empty = { name: '', catalogItemId: '', serviceExtraId: '', target: 'TOTAL_GUESTS', quantityPerTarget: '1', unitOfMeasure: 'unidad', minimumQuantity: '', roundingMode: 'CEIL', eventType: '', notes: '', active: true };
const entityName = (value: unknown) => typeof value === 'string' ? '' : (value as { name?: string } | undefined)?.name ?? '';

export default function ConsumptionRulesPage() {
  const { showToast } = useToast();
  const [rules, setRules] = useState<Rule[]>([]);
  const [catalog, setCatalog] = useState<CatalogItem[]>([]);
  const [services, setServices] = useState<ServiceExtra[]>([]);
  const [form, setForm] = useState(empty);
  const [editing, setEditing] = useState<Rule | null | undefined>();
  const [calc, setCalc] = useState({ totalGuests: '85', adultsCount: '45', minorsCount: '40', adultsWithAlcoholCount: '45', includesAlcohol: true, durationHours: '5' });
  const [result, setResult] = useState<Array<{ name: string; quantity: number; unit: string; totalPrice: number }>>([]);
  const load = useCallback(async () => {
    try {
      const [rulesResponse, catalogResponse, servicesResponse] = await Promise.all([api.get<{ items: Rule[] }>('/consumption-rules'), api.get<{ items: CatalogItem[] }>('/catalog/items?active=true'), api.get<{ items: ServiceExtra[] }>('/catalog/services?active=true')]);
      setRules(rulesResponse.items); setCatalog(catalogResponse.items); setServices(servicesResponse.items);
    } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudieron cargar reglas.', variant: 'error' }); }
  }, [showToast]);
  useEffect(() => { void load(); }, [load]);
  const open = (rule?: Rule) => { setEditing(rule ?? null); setForm(rule ? { ...empty, ...rule, catalogItemId: typeof rule.catalogItemId === 'string' ? rule.catalogItemId : rule.catalogItemId?._id ?? '', serviceExtraId: typeof rule.serviceExtraId === 'string' ? rule.serviceExtraId : rule.serviceExtraId?._id ?? '', quantityPerTarget: String(rule.quantityPerTarget), minimumQuantity: String(rule.minimumQuantity ?? '') } : empty); };
  async function save(event: FormEvent) { event.preventDefault(); const body = { ...form, quantityPerTarget: Number(form.quantityPerTarget), minimumQuantity: Number(form.minimumQuantity) || undefined }; try { if (editing) await api.patch(`/consumption-rules/${editing._id}`, body); else await api.post('/consumption-rules', body); setEditing(undefined); await load(); showToast({ message: 'Regla guardada.', variant: 'success' }); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo guardar regla.', variant: 'error' }); } }
  async function calculate() { try { const response = await api.post<{ suggestedItems: typeof result }>('/consumption-rules/calculate', { ...calc, totalGuests: Number(calc.totalGuests), adultsCount: Number(calc.adultsCount), minorsCount: Number(calc.minorsCount), adultsWithAlcoholCount: Number(calc.adultsWithAlcoholCount), durationHours: Number(calc.durationHours) }); setResult(response.suggestedItems); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo calcular.', variant: 'error' }); } }
  async function remove(rule: Rule) { try { await api.delete(`/consumption-rules/${rule._id}`); await load(); showToast({ message: 'Regla eliminada.', variant: 'success' }); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo eliminar.', variant: 'error' }); } }
  return <section className="space-y-6"><PageHeader title="Reglas de consumo" description="Calcula cantidades sugeridas para bebidas, comidas, materiales y servicios." action={<Button onClick={() => open()}><Plus className="mr-2 h-4 w-4" />Nueva regla</Button>} />
    <article className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-6"><Input placeholder="Invitados" value={calc.totalGuests} onChange={(e) => setCalc((c) => ({ ...c, totalGuests: e.target.value }))} /><Input placeholder="Adultos" value={calc.adultsCount} onChange={(e) => setCalc((c) => ({ ...c, adultsCount: e.target.value }))} /><Input placeholder="Menores" value={calc.minorsCount} onChange={(e) => setCalc((c) => ({ ...c, minorsCount: e.target.value }))} /><Input placeholder="Adultos alcohol" value={calc.adultsWithAlcoholCount} onChange={(e) => setCalc((c) => ({ ...c, adultsWithAlcoholCount: e.target.value }))} /><Input placeholder="Horas" value={calc.durationHours} onChange={(e) => setCalc((c) => ({ ...c, durationHours: e.target.value }))} /><Button onClick={() => void calculate()}><Calculator className="mr-2 h-4 w-4" />Calcular</Button></div>{result.length ? <div className="mt-4 grid gap-2 md:grid-cols-3">{result.map((item) => <div key={item.name} className="rounded-xl bg-zinc-50 p-3 text-sm"><p className="font-semibold">{item.name}</p><p>{item.quantity} {item.unit}</p></div>)}</div> : null}</article>
    <article className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="border-b bg-zinc-50/80 text-zinc-500"><tr>{['Regla','Ítem','Objetivo','Cantidad','Mínimo','Redondeo','Estado'].map((h) => <th key={h} className="px-5 py-3.5 text-left text-xs font-semibold uppercase">{h}</th>)}<th className="px-5 py-3.5 text-right text-xs font-semibold uppercase">Acciones</th></tr></thead><tbody className="divide-y divide-zinc-100">{rules.map((rule) => <tr key={rule._id} className="hover:bg-amber-50/35"><td className="px-5 py-4 font-semibold">{rule.name}</td><td className="px-5 py-4">{entityName(rule.catalogItemId) || entityName(rule.serviceExtraId)}</td><td className="px-5 py-4">{displayLabel(consumptionRuleTargetLabels, rule.target)}</td><td className="px-5 py-4">{rule.quantityPerTarget} {rule.unitOfMeasure}</td><td className="px-5 py-4">{rule.minimumQuantity ?? '-'}</td><td className="px-5 py-4">{displayLabel(roundingModeLabels, rule.roundingMode)}</td><td className="px-5 py-4">{rule.active === false ? 'Inactiva' : 'Activa'}</td><td className="px-5 py-4"><div className="flex justify-end"><TableActionButton icon={Pencil} label="Editar" onClick={() => open(rule)} /><TableActionButton icon={Trash2} label="Eliminar" onClick={() => void remove(rule)} /></div></td></tr>)}</tbody></table>{!rules.length ? <div className="grid place-items-center px-6 py-16 text-center"><Calculator className="h-10 w-10 text-zinc-300" /><p className="mt-3 text-sm text-zinc-500">No hay reglas configuradas.</p></div> : null}</div></article>
    <Modal open={editing !== undefined} title={editing ? 'Editar regla' : 'Nueva regla'} onClose={() => setEditing(undefined)}><form onSubmit={save} className="grid gap-3 p-6 md:grid-cols-2"><Input required placeholder="Nombre" value={form.name} onChange={(e) => setForm((c) => ({ ...c, name: e.target.value }))} /><Select value={form.target} onChange={(e) => setForm((c) => ({ ...c, target: e.target.value }))}>{Object.entries(consumptionRuleTargetLabels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</Select><Select value={form.catalogItemId} onChange={(e) => setForm((c) => ({ ...c, catalogItemId: e.target.value, serviceExtraId: '' }))}><option value="">Producto</option>{catalog.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select><Select value={form.serviceExtraId} onChange={(e) => setForm((c) => ({ ...c, serviceExtraId: e.target.value, catalogItemId: '' }))}><option value="">Servicio</option>{services.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</Select><Input placeholder="Cantidad por objetivo" value={form.quantityPerTarget} onChange={(e) => setForm((c) => ({ ...c, quantityPerTarget: e.target.value }))} /><Input placeholder="Unidad" value={form.unitOfMeasure} onChange={(e) => setForm((c) => ({ ...c, unitOfMeasure: e.target.value }))} /><Input placeholder="Mínimo" value={form.minimumQuantity} onChange={(e) => setForm((c) => ({ ...c, minimumQuantity: e.target.value }))} /><Select value={form.roundingMode} onChange={(e) => setForm((c) => ({ ...c, roundingMode: e.target.value }))}>{Object.entries(roundingModeLabels).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</Select><Textarea className="md:col-span-2" placeholder="Notas" value={form.notes} onChange={(e) => setForm((c) => ({ ...c, notes: e.target.value }))} /><footer className="flex justify-end gap-2 border-t pt-4 md:col-span-2"><Button type="button" variant="secondary" onClick={() => setEditing(undefined)}>Cancelar</Button><Button>Guardar</Button></footer></form></Modal>
  </section>;
}
