'use client';

/* eslint-disable react-hooks/set-state-in-effect */

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { Pencil, Plus, Search, Trash2, PackageSearch } from 'lucide-react';
import { Button, Input, Modal, PageHeader, Select, Textarea } from '@/components/ui/primitives';
import { TableActionButton } from '@/components/admin/table-action-button';
import { useToast } from '@/components/ui/toast-provider';
import { api } from '@/lib/api';
import { catalogItemTypeLabels, displayLabel, inventoryCategoryLabels, serviceExtraTypeLabels } from '@/lib/display-labels';

type Supplier = { _id: string; name: string };
type Salon = { _id: string; name: string };
type CatalogItem = { _id: string; name: string; type: string; category: string; unitOfMeasure: string; unitCost?: number; suggestedSalePrice?: number; supplierId?: string | Supplier; active?: boolean; notes?: string };
type ServiceExtra = { _id: string; name: string; type: string; cost?: number; basePrice?: number; applicableSalonIds?: Array<string | Salon>; supplierId?: string | Supplier; active?: boolean; notes?: string };
const productEmpty = { name: '', description: '', type: 'FOOD', category: 'FOOD', unitOfMeasure: 'unidad', unitSize: '', unitCost: '0', suggestedSalePrice: '0', supplierId: '', notes: '', active: true };
const serviceEmpty = { name: '', description: '', type: 'FIXED_PRICE', basePrice: '0', cost: '0', pricePerPerson: '', pricePerHour: '', pricePerUnit: '', supplierId: '', applicableSalonIds: [] as string[], notes: '', active: true };
const money = (value?: number) => new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 }).format(value ?? 0);
const entityName = (value: unknown) => typeof value === 'string' ? '' : (value as { name?: string } | undefined)?.name ?? '';
const entityId = (value: unknown) => typeof value === 'string' ? value : (value as { _id?: string } | undefined)?._id ?? '';
const toggle = (items: string[], value: string) => items.includes(value) ? items.filter((item) => item !== value) : [...items, value];

export default function CatalogPage() {
  const { showToast } = useToast();
  const [tab, setTab] = useState<'items' | 'services'>('items');
  const [items, setItems] = useState<CatalogItem[]>([]);
  const [services, setServices] = useState<ServiceExtra[]>([]);
  const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [salons, setSalons] = useState<Salon[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [productForm, setProductForm] = useState(productEmpty);
  const [serviceForm, setServiceForm] = useState(serviceEmpty);
  const [editingProduct, setEditingProduct] = useState<CatalogItem | null | undefined>();
  const [editingService, setEditingService] = useState<ServiceExtra | null | undefined>();
  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [productsResponse, servicesResponse, suppliersResponse, salonsResponse] = await Promise.all([
        api.get<{ items: CatalogItem[] }>(`/catalog/items?search=${encodeURIComponent(search)}`),
        api.get<{ items: ServiceExtra[] }>(`/catalog/services?search=${encodeURIComponent(search)}`),
        api.get<{ items: Supplier[] }>('/suppliers?active=true'),
        api.get<{ salons: Salon[] }>('/salons?active=true'),
      ]);
      setItems(productsResponse.items); setServices(servicesResponse.items); setSuppliers(suppliersResponse.items); setSalons(salonsResponse.salons ?? []);
    } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo cargar el catálogo.', variant: 'error' }); }
    finally { setLoading(false); }
  }, [search, showToast]);
  useEffect(() => { void load(); }, [load]);
  const openProduct = (item?: CatalogItem) => { setEditingProduct(item ?? null); setProductForm(item ? { ...productEmpty, ...item, unitSize: '', unitCost: String(item.unitCost ?? 0), suggestedSalePrice: String(item.suggestedSalePrice ?? 0), supplierId: entityId(item.supplierId) } : productEmpty); };
  const openService = (item?: ServiceExtra) => { setEditingService(item ?? null); setServiceForm(item ? { ...serviceEmpty, ...item, basePrice: String(item.basePrice ?? 0), cost: String(item.cost ?? 0), supplierId: entityId(item.supplierId), applicableSalonIds: (item.applicableSalonIds ?? []).map(entityId) } : serviceEmpty); };
  async function saveProduct(event: FormEvent) { event.preventDefault(); const body = { ...productForm, unitCost: Number(productForm.unitCost), suggestedSalePrice: Number(productForm.suggestedSalePrice), unitSize: Number(productForm.unitSize) || undefined }; try { if (editingProduct) await api.patch(`/catalog/items/${editingProduct._id}`, body); else await api.post('/catalog/items', body); setEditingProduct(undefined); await load(); showToast({ message: 'Producto guardado.', variant: 'success' }); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo guardar el producto.', variant: 'error' }); } }
  async function saveService(event: FormEvent) { event.preventDefault(); const body = { ...serviceForm, basePrice: Number(serviceForm.basePrice), cost: Number(serviceForm.cost), pricePerPerson: Number(serviceForm.pricePerPerson) || undefined, pricePerHour: Number(serviceForm.pricePerHour) || undefined, pricePerUnit: Number(serviceForm.pricePerUnit) || undefined }; try { if (editingService) await api.patch(`/catalog/services/${editingService._id}`, body); else await api.post('/catalog/services', body); setEditingService(undefined); await load(); showToast({ message: 'Servicio guardado.', variant: 'success' }); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo guardar el servicio.', variant: 'error' }); } }
  async function remove(path: string) { try { await api.delete(path); await load(); showToast({ message: 'Registro eliminado.', variant: 'success' }); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo eliminar.', variant: 'error' }); } }
  return <section className="space-y-6"><PageHeader title="Catálogo" description="Productos, bebidas, materiales y servicios extra para presupuestos personalizados." action={<Button onClick={() => tab === 'items' ? openProduct() : openService()}><Plus className="mr-2 h-4 w-4" />Nuevo</Button>} />
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm"><div className="flex gap-2"><button onClick={() => setTab('items')} className={`rounded-xl px-4 py-2 text-sm font-medium ${tab === 'items' ? 'bg-zinc-950 text-white' : 'bg-zinc-100 text-zinc-700'}`}>Productos</button><button onClick={() => setTab('services')} className={`rounded-xl px-4 py-2 text-sm font-medium ${tab === 'services' ? 'bg-zinc-950 text-white' : 'bg-zinc-100 text-zinc-700'}`}>Servicios / Extras</button></div><div className="relative min-w-72"><Search className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-400" /><Input className="h-11 pl-10" placeholder="Buscar..." value={search} onChange={(e) => setSearch(e.target.value)} /></div></div>
    <article className="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm">{loading ? <p className="p-8 text-sm text-zinc-500">Cargando catálogo...</p> : tab === 'items' ? <ProductsTable items={items} onEdit={openProduct} onDelete={(id) => void remove(`/catalog/items/${id}`)} /> : <ServicesTable items={services} onEdit={openService} onDelete={(id) => void remove(`/catalog/services/${id}`)} />}</article>
    <Modal open={editingProduct !== undefined} title={editingProduct ? 'Editar producto' : 'Nuevo producto'} onClose={() => setEditingProduct(undefined)}><form onSubmit={saveProduct} className="grid gap-3 p-6 md:grid-cols-2"><Input required placeholder="Nombre" value={productForm.name} onChange={(e) => setProductForm((c) => ({ ...c, name: e.target.value }))} /><Select value={productForm.type} onChange={(e) => setProductForm((c) => ({ ...c, type: e.target.value }))}>{Object.entries(catalogItemTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Select value={productForm.category} onChange={(e) => setProductForm((c) => ({ ...c, category: e.target.value }))}>{Object.entries(inventoryCategoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Input required placeholder="Unidad" value={productForm.unitOfMeasure} onChange={(e) => setProductForm((c) => ({ ...c, unitOfMeasure: e.target.value }))} /><Input placeholder="Costo" value={productForm.unitCost} onChange={(e) => setProductForm((c) => ({ ...c, unitCost: e.target.value }))} /><Input placeholder="Precio sugerido" value={productForm.suggestedSalePrice} onChange={(e) => setProductForm((c) => ({ ...c, suggestedSalePrice: e.target.value }))} /><Select value={productForm.supplierId} onChange={(e) => setProductForm((c) => ({ ...c, supplierId: e.target.value }))}><option value="">Sin proveedor</option>{suppliers.map((supplier) => <option key={supplier._id} value={supplier._id}>{supplier.name}</option>)}</Select><Textarea className="md:col-span-2" placeholder="Notas" value={productForm.notes} onChange={(e) => setProductForm((c) => ({ ...c, notes: e.target.value }))} /><Footer onClose={() => setEditingProduct(undefined)} /></form></Modal>
    <Modal open={editingService !== undefined} title={editingService ? 'Editar servicio' : 'Nuevo servicio'} onClose={() => setEditingService(undefined)}><form onSubmit={saveService} className="grid gap-3 p-6 md:grid-cols-2"><Input required placeholder="Nombre" value={serviceForm.name} onChange={(e) => setServiceForm((c) => ({ ...c, name: e.target.value }))} /><Select value={serviceForm.type} onChange={(e) => setServiceForm((c) => ({ ...c, type: e.target.value }))}>{Object.entries(serviceExtraTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><Input placeholder="Costo" value={serviceForm.cost} onChange={(e) => setServiceForm((c) => ({ ...c, cost: e.target.value }))} /><Input placeholder="Precio base" value={serviceForm.basePrice} onChange={(e) => setServiceForm((c) => ({ ...c, basePrice: e.target.value }))} /><Select value={serviceForm.supplierId} onChange={(e) => setServiceForm((c) => ({ ...c, supplierId: e.target.value }))}><option value="">Sin proveedor</option>{suppliers.map((supplier) => <option key={supplier._id} value={supplier._id}>{supplier.name}</option>)}</Select><div className="rounded-xl border border-zinc-100 p-3 md:col-span-2"><p className="text-sm font-semibold">Salones aplicables</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{salons.map((salon) => <label key={salon._id} className="text-sm"><input className="mr-2" type="checkbox" checked={serviceForm.applicableSalonIds.includes(salon._id)} onChange={() => setServiceForm((c) => ({ ...c, applicableSalonIds: toggle(c.applicableSalonIds, salon._id) }))} />{salon.name}</label>)}</div></div><Textarea className="md:col-span-2" placeholder="Notas" value={serviceForm.notes} onChange={(e) => setServiceForm((c) => ({ ...c, notes: e.target.value }))} /><Footer onClose={() => setEditingService(undefined)} /></form></Modal>
  </section>;
}
function ProductsTable({ items, onEdit, onDelete }: { items: CatalogItem[]; onEdit: (item: CatalogItem) => void; onDelete: (id: string) => void }) { if (!items.length) return <Empty />; return <div className="overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead className="border-b bg-zinc-50/80 text-zinc-500"><tr>{['Producto','Categoría','Tipo','Unidad','Costo','Precio sugerido','Proveedor','Estado'].map((h) => <th key={h} className="px-5 py-3.5 text-left text-xs font-semibold uppercase">{h}</th>)}<th className="px-5 py-3.5 text-right text-xs font-semibold uppercase">Acciones</th></tr></thead><tbody className="divide-y divide-zinc-100">{items.map((item) => <tr key={item._id} className="hover:bg-amber-50/35"><td className="px-5 py-4 font-semibold">{item.name}</td><td className="px-5 py-4">{displayLabel(inventoryCategoryLabels, item.category)}</td><td className="px-5 py-4">{displayLabel(catalogItemTypeLabels, item.type)}</td><td className="px-5 py-4">{item.unitOfMeasure}</td><td className="px-5 py-4">{money(item.unitCost)}</td><td className="px-5 py-4">{money(item.suggestedSalePrice)}</td><td className="px-5 py-4">{entityName(item.supplierId) || '-'}</td><td className="px-5 py-4">{item.active === false ? 'Inactivo' : 'Activo'}</td><td className="px-5 py-4"><div className="flex justify-end"><TableActionButton icon={Pencil} label="Editar" onClick={() => onEdit(item)} /><TableActionButton icon={Trash2} label="Eliminar" onClick={() => onDelete(item._id)} /></div></td></tr>)}</tbody></table></div>; }
function ServicesTable({ items, onEdit, onDelete }: { items: ServiceExtra[]; onEdit: (item: ServiceExtra) => void; onDelete: (id: string) => void }) { if (!items.length) return <Empty />; return <div className="overflow-x-auto"><table className="min-w-[980px] w-full text-sm"><thead className="border-b bg-zinc-50/80 text-zinc-500"><tr>{['Servicio','Tipo precio','Costo','Precio','Salones','Proveedor','Estado'].map((h) => <th key={h} className="px-5 py-3.5 text-left text-xs font-semibold uppercase">{h}</th>)}<th className="px-5 py-3.5 text-right text-xs font-semibold uppercase">Acciones</th></tr></thead><tbody className="divide-y divide-zinc-100">{items.map((item) => <tr key={item._id} className="hover:bg-amber-50/35"><td className="px-5 py-4 font-semibold">{item.name}</td><td className="px-5 py-4">{displayLabel(serviceExtraTypeLabels, item.type)}</td><td className="px-5 py-4">{money(item.cost)}</td><td className="px-5 py-4">{money(item.basePrice)}</td><td className="px-5 py-4">{item.applicableSalonIds?.map(entityName).filter(Boolean).join(', ') || 'Todos'}</td><td className="px-5 py-4">{entityName(item.supplierId) || '-'}</td><td className="px-5 py-4">{item.active === false ? 'Inactivo' : 'Activo'}</td><td className="px-5 py-4"><div className="flex justify-end"><TableActionButton icon={Pencil} label="Editar" onClick={() => onEdit(item)} /><TableActionButton icon={Trash2} label="Eliminar" onClick={() => onDelete(item._id)} /></div></td></tr>)}</tbody></table></div>; }
function Empty() { return <div className="grid place-items-center px-6 py-16 text-center"><PackageSearch className="h-10 w-10 text-zinc-300" /><p className="mt-3 text-sm text-zinc-500">No hay registros en este catálogo.</p></div>; }
function Footer({ onClose }: { onClose: () => void }) { return <footer className="flex justify-end gap-2 border-t pt-4 md:col-span-2"><Button type="button" variant="secondary" onClick={onClose}>Cancelar</Button><Button>Guardar</Button></footer>; }
