'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { Monitor, Smartphone } from 'lucide-react';
import { Button, PageHeader } from '@/components/ui/primitives';
import { api } from '@/lib/api';
import { PublicInvitationRenderer } from './public-invitation-renderer';
import type { DigitalInvitation, InvitationSection, InvitationTemplate, InvitationTemplateCategory } from './types';

type Props = { initialTemplateId?: string };
type Sample = { title: string; honoreeName: string; address: string; introduction: string; dressCode: string; date: string };

const samples: Record<InvitationTemplateCategory, Sample> = {
  wedding: { title: 'Sofía & Tomás', honoreeName: 'Sofía y Tomás', address: 'Estancia Los Álamos · La Plata', introduction: 'Con muchísima alegría queremos compartir el comienzo de esta nueva etapa junto a quienes más queremos.', dressCode: 'Elegante campestre', date: '2026-11-21T19:30:00.000Z' },
  fifteen: { title: 'Los 15 de Valentina', honoreeName: 'Valentina', address: 'Salón M&M Eventos · La Plata', introduction: 'Una noche soñada, música, brillo y todos mis afectos para celebrar mis quince años.', dressCode: 'Elegante', date: '2026-10-10T21:00:00.000Z' },
  birthday: { title: 'Los 40 de Martín', honoreeName: 'Martín', address: 'Terraza Central · City Bell', introduction: 'Brindemos por los recuerdos, las risas y todo lo que todavía falta celebrar.', dressCode: 'Casual elegante', date: '2026-09-19T20:30:00.000Z' },
  kids: { title: 'El cumple de Emma', honoreeName: 'Emma cumple 6', address: 'M&M Kids · La Plata', introduction: 'Una tarde de colores, juegos, magia y muchísimas sonrisas para festejar.', dressCode: 'Cómodo para jugar', date: '2026-08-23T15:30:00.000Z' },
  baby_shower: { title: 'Baby shower de Olivia', honoreeName: 'Olivia está por llegar', address: 'Casa de Ana · Gonnet', introduction: 'Celebramos con mucho amor la dulce espera de nuestra pequeña Olivia.', dressCode: 'Tonos pastel', date: '2026-09-05T16:00:00.000Z' },
  baptism: { title: 'Bautismo de Benjamín', honoreeName: 'Benjamín', address: 'Parroquia San José · La Plata', introduction: 'Nos emociona compartir este día tan especial en familia.', dressCode: 'Formal y cálido', date: '2026-10-03T11:30:00.000Z' },
  communion: { title: 'Primera comunión de Clara', honoreeName: 'Clara', address: 'Salón Los Tilos · La Plata', introduction: 'Acompañanos en un momento muy importante para nuestra familia.', dressCode: 'Formal', date: '2026-10-17T12:30:00.000Z' },
  anniversary: { title: '25 años juntos', honoreeName: 'Mariana & Diego', address: 'Bodega La Emilia · La Plata', introduction: 'Volvemos a elegirnos y queremos brindar por este camino compartido.', dressCode: 'Elegante', date: '2026-11-07T20:00:00.000Z' },
  corporate: { title: 'Noche de innovación 2026', honoreeName: 'Grupo Horizonte', address: 'Skyline Rooftop · Buenos Aires', introduction: 'Una noche para conectar ideas, celebrar logros y mirar juntos lo que viene.', dressCode: 'Business cocktail', date: '2026-10-29T19:00:00.000Z' },
  general: { title: 'Una noche para celebrar', honoreeName: 'Familia Fernández', address: 'Quinta La Arboleda · La Plata', introduction: 'Hay momentos que merecen celebrarse con las personas que más queremos.', dressCode: 'Elegante informal', date: '2026-11-14T20:30:00.000Z' }
};

function imageFor(category: InvitationTemplateCategory) { if (category === 'corporate') return '/invitation-examples/corporate-rooftop.png'; if (category === 'kids' || category === 'baby_shower' || category === 'baptism' || category === 'communion') return '/invitation-examples/kids-party.png'; if (category === 'fifteen' || category === 'birthday') return '/invitation-examples/fifteen-ballroom.png'; return '/invitation-examples/wedding-garden.png'; }
function categoryLabel(category: InvitationTemplateCategory) { return ({ wedding: 'Boda', fifteen: 'XV', birthday: 'Cumpleaños', kids: 'Infantil', baby_shower: 'Baby shower', baptism: 'Bautismo', communion: 'Comunión', anniversary: 'Aniversario', corporate: 'Corporativo', general: 'General' } as Record<InvitationTemplateCategory, string>)[category]; }

function sampleInvitation(template: InvitationTemplate): DigitalInvitation {
  const category = template.category ?? 'general'; const sample = samples[category]; const image = imageFor(category);
  const section = (id: string, type: InvitationSection['type'], order: number, data: Record<string, unknown>): InvitationSection => ({ id, type, enabled: true, order, layout: 'contained', background: { type: 'transparent' }, textStyle: { alignment: 'center' }, spacing: { paddingTop: 56, paddingBottom: 56 }, animation: { type: 'fade', duration: 350, delay: 0 }, data });
  return { _id: `example-${template._id}`, templateId: template, template: template.slug, templateTier: template.tier, templateFeatures: template.allowedFeatures, celebrationType: category, title: sample.title, honoreeName: sample.honoreeName, eventDate: sample.date, address: sample.address, introduction: sample.introduction, dressCode: sample.dressCode, coverImageUrl: image, theme: template.theme, content: { sections: [section('hero', 'hero', 0, { title: sample.title, subtitle: sample.honoreeName, imageUrl: image, height: '85vh', alignment: 'center' }), section('welcome', 'welcome', 1, { title: 'Una celebración especial', message: sample.introduction, signature: 'Con cariño' }), section('event-details', 'event_details', 2, { pretitle: 'Agendá la fecha' }), section('countdown', 'countdown', 3, { title: 'Falta muy poco', variant: 'blocks' }), section('venue', 'venue', 4, { title: 'Dónde nos encontramos', description: 'Un espacio pensado para vivir una celebración inolvidable.' }), section('gallery', 'gallery', 5, { title: 'Así se vive', layout: 'editorial', items: [{ id: 'photo-1', type: 'image', url: image, altText: 'Ambientación de ejemplo' }, { id: 'photo-2', type: 'image', url: image, altText: 'Ambientación de ejemplo' }, { id: 'photo-3', type: 'image', url: image, altText: 'Ambientación de ejemplo' }] }), section('dress-code', 'dress_code', 6, { title: 'Dress code', description: sample.dressCode, colors: [template.theme?.primaryColor ?? '#777777', template.theme?.accentColor ?? '#dddddd'] }), section('schedule', 'schedule', 7, { title: 'Momentos de la celebración', items: [{ id: 'arrival', time: '20:30', title: 'Recepción', description: 'Bienvenida y brindis.' }, { id: 'celebration', time: '22:00', title: 'Celebración', description: 'El momento más esperado.' }] }), section('footer', 'footer', 8, { message: 'Ejemplo de invitación digital M&M Eventos' })] } };
}

export function InvitationExamples({ initialTemplateId }: Props) {
  const [templates, setTemplates] = useState<InvitationTemplate[]>([]); const [selectedId, setSelectedId] = useState(initialTemplateId ?? ''); const [device, setDevice] = useState<'web' | 'mobile'>('web');
  useEffect(() => { void api.get<{ templates: InvitationTemplate[] }>('/invitations/templates').then((data) => setTemplates(data.templates ?? [])); }, []);
  const selected = templates.find((template) => template._id === selectedId) ?? templates[0];
  const invitation = useMemo(() => selected ? sampleInvitation(selected) : undefined, [selected]);
  const choose = (templateId: string) => { setSelectedId(templateId); window.history.replaceState(null, '', `/admin/digital-invitations/examples?templateId=${templateId}&format=${device}`); };
  const changeDevice = (next: 'web' | 'mobile') => { setDevice(next); if (selected) window.history.replaceState(null, '', `/admin/digital-invitations/examples?templateId=${selected._id}&format=${next}`); };
  return <section className="space-y-6">
    <PageHeader title="Ejemplos de invitaciones" description="Muestras ficticias listas para presentar a clientes y comparar cada opción." action={<Link href="/admin/digital-invitations"><Button variant="secondary">Todas las invitaciones</Button></Link>} />
    <section aria-label="Comparación de planes" className="grid gap-4 lg:grid-cols-2">
      <article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-zinc-500">Invitación Basic</p><h2 className="mt-2 text-xl font-semibold text-zinc-950">Todo lo esencial, con estilo.</h2><p className="mt-3 text-sm leading-6 text-zinc-600">Una propuesta elegante y completa para comunicar tu evento: bienvenida personalizada, fecha, mapa, cuenta regresiva, colores, tipografías y una galería de hasta 4 fotos. Ideal para compartir una invitación clara, linda y fácil de usar.</p><p className="mt-3 text-xs font-medium text-zinc-500">No incluye música de fondo, agenda, mesa de regalos ni fondos personalizados por sección.</p></article>
      <article className="rounded-2xl border border-amber-300 bg-amber-50/70 p-5 shadow-[0_10px_30px_rgba(180,125,20,.12)]"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-800">✦ Invitación Premium</p><h2 className="mt-2 text-xl font-semibold text-amber-950">Una experiencia que sorprende.</h2><p className="mt-3 text-sm leading-6 text-amber-950/80">Incluye todo lo de Basic y suma música de fondo en MP3 o URL, hasta 20 fotos, agenda del evento, mesa de regalos, fondos personalizados por sección, animaciones avanzadas y más libertad para crear contenidos a medida.</p><p className="mt-3 text-xs font-semibold text-amber-900">Ideal para quince años, casamientos y celebraciones donde cada detalle cuenta una historia.</p></article>
    </section>
    <div className="grid gap-6 xl:grid-cols-[310px_minmax(0,1fr)]"><aside className="rounded-2xl border border-zinc-200 bg-white p-4"><p className="text-sm font-semibold text-zinc-950">Elegí una plantilla</p><p className="mt-1 text-xs text-zinc-500">Cada una usa datos y ambientación de ejemplo.</p><div className="mt-4 grid gap-2">{templates.map((template) => <button key={template._id} type="button" onClick={() => choose(template._id)} className={`rounded-xl border p-3 text-left transition ${selected?._id === template._id ? 'border-zinc-950 bg-zinc-950 text-white' : 'border-zinc-200 hover:border-zinc-400'}`}><span className="block text-sm font-semibold">{template.name}</span><span className={`mt-1 block text-xs ${selected?._id === template._id ? 'text-white/70' : 'text-zinc-500'}`}>{categoryLabel(template.category ?? 'general')} · {template.tier === 'premium' ? '✦ Premium · RSVP' : 'Basic · Esencial'}</span></button>)}</div></aside><div className="min-w-0 rounded-2xl border border-zinc-200 bg-zinc-100 p-3 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-zinc-950">{selected?.name ?? 'Cargando ejemplo…'}</p><p className="text-sm text-zinc-500">Vista final de demostración</p></div><div className="flex gap-2"><Button variant={device === 'web' ? 'primary' : 'secondary'} onClick={() => changeDevice('web')}><Monitor className="mr-2 h-4 w-4" />Web</Button><Button variant={device === 'mobile' ? 'primary' : 'secondary'} onClick={() => changeDevice('mobile')}><Smartphone className="mr-2 h-4 w-4" />Móvil</Button></div></div>{invitation ? <div className={`mx-auto overflow-hidden rounded-[1.5rem] bg-white shadow-2xl ${device === 'mobile' ? 'max-w-[390px]' : 'max-w-6xl'}`}><PublicInvitationRenderer invitation={invitation} mode="example" showRsvp={selected?.tier === 'premium'} /></div> : <div className="grid min-h-96 place-items-center text-sm text-zinc-500">Cargando plantillas…</div>}</div></div>
  </section>;
}
