'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Copy, ExternalLink, Plus } from 'lucide-react';
import { api } from '@/lib/api';
import { Button, Input, Modal, PageHeader, Textarea } from '@/components/ui/primitives';
import { useToast } from '@/components/ui/toast-provider';
import type { DigitalInvitation, InvitationGuest, InvitationTemplate } from './types';
import { fullName } from './types';

const publicUrl = (path: string) => `${typeof window === 'undefined' ? '' : window.location.origin}${path}`;
const emptyForm = { title: '', honoreeName: '', eventDate: '', address: '', mapsUrl: '', introduction: '', rsvpDeadline: '', templateId: '' };

export function InvitationsList() {
  const { showToast } = useToast(); const [items, setItems] = useState<DigitalInvitation[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { void api.get<{ invitations: DigitalInvitation[] }>('/invitations').then((data) => setItems(data.invitations ?? [])).catch((error) => showToast({ message: error.message, variant: 'error' })).finally(() => setLoading(false)); }, [showToast]);
  return <section className="space-y-6"><PageHeader title="Invitaciones digitales" description="Creá y administrá invitaciones sin asociarlas a un evento comercial." action={<Link href="/admin/digital-invitations/new"><Button><Plus className="mr-2 h-4 w-4" />Nueva invitación</Button></Link>} />{loading ? <p className="text-sm text-zinc-500">Cargando invitaciones…</p> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Link key={item._id} href={`/admin/digital-invitations/${item._id}`} className="rounded-2xl border bg-white p-5 transition hover:border-zinc-400"><p className="font-semibold">{item.title}</p><p className="mt-1 text-sm text-zinc-500">{item.honoreeName || 'Sin homenajeado'} · {item.status || 'draft'}</p><p className="mt-4 text-sm text-zinc-500">{item.eventDate ? new Date(item.eventDate).toLocaleString('es-AR') : 'Fecha a confirmar'}</p></Link>)}{!items.length ? <div className="rounded-2xl border border-dashed p-10 text-center text-sm text-zinc-500 md:col-span-2 xl:col-span-3">Todavía no hay invitaciones. Creá la primera para compartir un enlace personalizado.</div> : null}</div>}</section>;
}

export function InvitationEditor({ invitationId }: { invitationId?: string }) {
  const { showToast } = useToast(); const [form, setForm] = useState(emptyForm); const [templates, setTemplates] = useState<InvitationTemplate[]>([]); const [saving, setSaving] = useState(false);
  useEffect(() => { void api.get<{ templates: InvitationTemplate[] }>('/invitations/templates').then((data) => setTemplates(data.templates ?? [])); if (invitationId) void api.get<{ invitation: DigitalInvitation }>(`/invitations/${invitationId}`).then(({ invitation }) => setForm({ title: invitation.title ?? '', honoreeName: invitation.honoreeName ?? '', eventDate: invitation.eventDate?.slice(0, 16) ?? '', address: invitation.address ?? '', mapsUrl: invitation.mapsUrl ?? '', introduction: invitation.introduction ?? '', rsvpDeadline: invitation.rsvpDeadline?.slice(0, 16) ?? '', templateId: typeof invitation.templateId === 'string' ? invitation.templateId : invitation.templateId?._id ?? '' })).catch((error) => showToast({ message: error.message, variant: 'error' })); }, [invitationId, showToast]);
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); try { const payload = { ...form, eventDate: form.eventDate || undefined, rsvpDeadline: form.rsvpDeadline || undefined, templateId: form.templateId || undefined }; const result = invitationId ? await api.patch<{ invitation: DigitalInvitation }>(`/invitations/${invitationId}`, payload) : await api.post<{ invitation: DigitalInvitation }>('/invitations', payload); window.location.assign(`/admin/digital-invitations/${result.invitation._id}`); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo guardar.', variant: 'error' }); } finally { setSaving(false); } };
  return <section className="space-y-6"><PageHeader title={invitationId ? 'Editar invitación' : 'Nueva invitación digital'} description="Los datos de fecha, lugar y diseño pertenecen a esta invitación." /><div className="grid gap-4 rounded-2xl border bg-white p-6 md:grid-cols-2"><Input placeholder="Título" value={form.title} onChange={(event) => set('title', event.target.value)} /><Input placeholder="Homenajeado/a" value={form.honoreeName} onChange={(event) => set('honoreeName', event.target.value)} /><Input type="datetime-local" value={form.eventDate} onChange={(event) => set('eventDate', event.target.value)} /><Input type="datetime-local" value={form.rsvpDeadline} onChange={(event) => set('rsvpDeadline', event.target.value)} /><Input placeholder="Dirección o lugar" value={form.address} onChange={(event) => set('address', event.target.value)} /><Input placeholder="URL de Maps" value={form.mapsUrl} onChange={(event) => set('mapsUrl', event.target.value)} /><select className="rounded-xl border px-3 py-2 text-sm" value={form.templateId} onChange={(event) => set('templateId', event.target.value)}><option value="">Diseño clásico</option>{templates.map((template) => <option key={template._id} value={template._id}>{template.name}</option>)}</select><Textarea className="md:col-span-2" placeholder="Texto de bienvenida" value={form.introduction} onChange={(event) => set('introduction', event.target.value)} /><div className="flex justify-end gap-2 md:col-span-2"><Link href={invitationId ? `/admin/digital-invitations/${invitationId}` : '/admin/digital-invitations'}><Button variant="secondary">Cancelar</Button></Link><Button disabled={!form.title || saving} onClick={() => void save()}>Guardar</Button></div></div></section>;
}

export function InvitationDetail({ invitationId }: { invitationId: string }) {
  const { showToast } = useToast(); const [invitation, setInvitation] = useState<DigitalInvitation>(); const [guests, setGuests] = useState<InvitationGuest[]>([]); const [guest, setGuest] = useState<Partial<InvitationGuest>>();
  const load = async () => { try { const [{ invitation: item }, { guests: entries }] = await Promise.all([api.get<{ invitation: DigitalInvitation }>(`/invitations/${invitationId}`), api.get<{ guests: InvitationGuest[] }>(`/invitations/${invitationId}/guests`)]); setInvitation(item); setGuests(entries ?? []); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo cargar.', variant: 'error' }); } };
  useEffect(() => { void load(); }, [invitationId]);
  const publish = async () => { if (!invitation) return; const result = await api.post<{ invitation: DigitalInvitation }>(`/invitations/${invitationId}/${invitation.status === 'published' ? 'unpublish' : 'publish'}`, {}); setInvitation(result.invitation); };
  const saveGuest = async (draft = guest) => { if (!draft?.firstName) return; const payload = { ...draft, assignedSeats: Number(draft.assignedSeats ?? 1) }; const result = draft._id ? await api.patch<{ guest: InvitationGuest }>(`/invitations/${invitationId}/guests/${draft._id}`, payload) : await api.post<{ guest: InvitationGuest }>(`/invitations/${invitationId}/guests`, payload); setGuests((items) => draft._id ? items.map((item) => item._id === draft._id ? result.guest : item) : [...items, result.guest]); setGuest(undefined); };
  const copy = async (entry: InvitationGuest) => { const { token } = await api.get<{ token: string }>(`/invitations/${invitationId}/guests/${entry._id}/link`); await navigator.clipboard.writeText(publicUrl(`/invitacion/${token}`)); showToast({ message: 'Enlace personalizado copiado.', variant: 'success' }); };
  if (!invitation) return <p className="text-sm text-zinc-500">Cargando invitación…</p>;
  return <section className="space-y-6"><PageHeader title={invitation.title || 'Invitación digital'} description={invitation.status === 'published' ? 'Publicada' : 'Borrador'} action={<div className="flex gap-2"><Link href={`/admin/digital-invitations/${invitationId}/edit`}><Button variant="secondary">Editar</Button></Link><Button onClick={() => void publish()}>{invitation.status === 'published' ? 'Despublicar' : 'Publicar'}</Button></div>} /><div className="flex flex-wrap gap-2"><Link href={`/invitacion/${invitation.publicToken}`} target="_blank"><Button variant="secondary"><ExternalLink className="mr-2 h-4 w-4" />Vista pública</Button></Link><Button onClick={() => setGuest({ assignedSeats: 1 })}><Plus className="mr-2 h-4 w-4" />Agregar invitado</Button></div><div className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-zinc-50 text-left text-xs uppercase text-zinc-500"><tr><th className="p-4">Invitado</th><th>Contacto</th><th>RSVP</th><th /></tr></thead><tbody>{guests.map((entry) => <tr key={entry._id} className="border-t"><td className="p-4">{fullName(entry)}</td><td>{entry.email || entry.phone || '—'}</td><td>{entry.status || 'pending'}</td><td className="p-2 text-right"><Button variant="secondary" onClick={() => void copy(entry)}><Copy className="h-4 w-4" /></Button></td></tr>)}</tbody></table>{!guests.length ? <p className="p-8 text-center text-sm text-zinc-500">Todavía no hay invitados.</p> : null}</div><GuestModal guest={guest} onClose={() => setGuest(undefined)} onSave={() => void saveGuest()} /></section>;
}

function GuestModal({ guest, onClose, onSave }: { guest?: Partial<InvitationGuest>; onClose: () => void; onSave: () => void }) { const [draft, setDraft] = useState(guest); useEffect(() => setDraft(guest), [guest]); if (!draft) return null; return <Modal open onClose={onClose} title="Invitado"><div className="grid gap-3 p-6"><Input placeholder="Nombre" value={draft.firstName ?? ''} onChange={(event) => setDraft((value) => ({ ...value, firstName: event.target.value }))} /><Input placeholder="Apellido" value={draft.lastName ?? ''} onChange={(event) => setDraft((value) => ({ ...value, lastName: event.target.value }))} /><Input placeholder="Email" value={draft.email ?? ''} onChange={(event) => setDraft((value) => ({ ...value, email: event.target.value }))} /><Input type="number" min="1" value={draft.assignedSeats ?? 1} onChange={(event) => setDraft((value) => ({ ...value, assignedSeats: Number(event.target.value) }))} /><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button disabled={!draft.firstName} onClick={onSave}>Guardar</Button></div></div></Modal>; }

export function InvitationTemplates() { const { showToast } = useToast(); const [templates, setTemplates] = useState<InvitationTemplate[]>([]); const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const load = () => api.get<{ templates: InvitationTemplate[] }>('/invitations/templates').then((data) => setTemplates(data.templates ?? [])); useEffect(() => { void load(); }, []); const create = async () => { try { await api.post('/invitations/templates', { name, slug }); setName(''); setSlug(''); await load(); } catch (error) { showToast({ message: error instanceof Error ? error.message : 'No se pudo crear la plantilla.', variant: 'error' }); } }; return <section className="space-y-6"><PageHeader title="Plantillas de invitación" description="Diseños reutilizables para nuevas invitaciones." /><div className="flex gap-2 rounded-2xl border bg-white p-5"><Input placeholder="Nombre" value={name} onChange={(event) => setName(event.target.value)} /><Input placeholder="slug-diseno" value={slug} onChange={(event) => setSlug(event.target.value)} /><Button disabled={!name || !slug} onClick={() => void create()}>Crear</Button></div><div className="grid gap-3 md:grid-cols-2">{templates.map((template) => <div key={template._id} className="rounded-2xl border bg-white p-5"><p className="font-semibold">{template.name}</p><p className="text-sm text-zinc-500">{template.slug}</p></div>)}</div></section>; }
