'use client';

import { type CSSProperties, type FormEvent, type ReactNode, useEffect, useMemo, useState } from 'react';
import { CalendarDays, Copy, Gift, MapPin, Music2, Navigation, Pause, Shirt, X } from 'lucide-react';
import { Button, Input, Select, Textarea } from '@/components/ui/primitives';
import type { DigitalInvitation, InvitationGuest, InvitationSection, InvitationSectionBackground } from './types';
import { formatDateTime, fullName } from './types';
import { resolveInvitationTheme } from './invitation-theme';

type RsvpPayload = { response: string; fullName?: string; dietaryRestrictions: string; musicRequest: string; guestMessage: string };
type Props = { invitation: DigitalInvitation; recipient?: InvitationGuest; mode: 'public' | 'preview' | 'example'; showRsvp?: boolean; previewOpening?: boolean; forceMobileLayout?: boolean; onRsvp?: (payload: RsvpPayload) => Promise<void>; saving?: boolean; error?: string };
type SectionData = Record<string, unknown>;

const fallbackSections = (): InvitationSection[] => [
  { id: 'hero', type: 'hero', enabled: true, order: 0, background: { type: 'gradient', gradient: { direction: '135deg', from: '#7c5cff', to: '#211d43' } }, data: {} },
  { id: 'welcome', type: 'welcome', enabled: true, order: 1, background: { type: 'transparent' }, data: {} },
  { id: 'event', type: 'event_details', enabled: true, order: 2, background: { type: 'transparent' }, data: {} },
  { id: 'venue', type: 'venue', enabled: true, order: 3, background: { type: 'transparent' }, data: {} },
  { id: 'rsvp', type: 'rsvp', enabled: true, order: 4, background: { type: 'transparent' }, data: {} }
];
const text = (data: SectionData, key: string) => typeof data[key] === 'string' ? data[key] : '';
const list = (data: SectionData, key: string) => Array.isArray(data[key]) ? data[key] : [];
const calendarUrl = (invitation: DigitalInvitation) => { if (!invitation.eventDate) return ''; const start = new Date(invitation.eventDate); const end = new Date(start.getTime() + 3 * 60 * 60 * 1000); const stamp = (value: Date) => value.toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z'); const params = new URLSearchParams({ action: 'TEMPLATE', text: invitation.title || 'Evento', dates: `${stamp(start)}/${stamp(end)}`, location: invitation.address || '', details: invitation.introduction || '' }); return `https://calendar.google.com/calendar/render?${params}`; };
const mapQuery = (invitation: DigitalInvitation) => invitation.address || invitation.mapsUrl || '';

function backgroundStyle(background: InvitationSectionBackground | undefined): CSSProperties {
  if (!background || background.type === 'transparent') return {};
  if (background.type === 'solid') return { backgroundColor: background.color };
  if (background.type === 'gradient' && background.gradient) return { backgroundImage: `linear-gradient(${background.gradient.direction}, ${background.gradient.from}, ${background.gradient.to})` };
  if (background.type === 'image' && background.image) return { backgroundImage: `${background.image.overlayColor ? `linear-gradient(${background.image.overlayColor}${Math.round((background.image.overlayOpacity ?? .35) * 255).toString(16).padStart(2, '0')}, ${background.image.overlayColor}${Math.round((background.image.overlayOpacity ?? .35) * 255).toString(16).padStart(2, '0')}), ` : ''}url(${background.image.url})`, backgroundPosition: `${background.image.positionX ?? 50}% ${background.image.positionY ?? 50}%`, backgroundSize: background.image.fit ?? 'cover', filter: background.image.blur ? `blur(${background.image.blur}px)` : undefined };
  return {};
}

export function PublicInvitationRenderer({ invitation, recipient, mode, showRsvp = true, previewOpening = false, forceMobileLayout = false, onRsvp, saving, error }: Props) {
  const [opened, setOpened] = useState(!(previewOpening || (mode === 'public' && invitation.templateTier === 'premium')));
  const [musicOn, setMusicOn] = useState(false);
  const [galleryImage, setGalleryImage] = useState<string>();
  const [mapOpen, setMapOpen] = useState(false);
  const theme = resolveInvitationTheme(invitation.theme); const primary = theme.primaryColor; const secondary = theme.secondaryColor; const surface = theme.surfaceColor; const background = theme.backgroundColor; const textColor = theme.textColor;
  const style = { '--invitation-primary': primary, '--invitation-secondary': secondary, '--invitation-accent': theme.accentColor, '--invitation-background': background, '--invitation-surface': surface, '--invitation-text': textColor, '--invitation-muted': theme.mutedTextColor, '--invitation-on-primary': theme.onPrimaryColor, '--invitation-heading-font': theme.headingFont, '--invitation-body-font': theme.bodyFont } as CSSProperties;
  const sections = useMemo(() => (invitation.content?.sections?.length ? invitation.content.sections : fallbackSections()).filter((section) => section.enabled).sort((a, b) => a.order - b.order), [invitation.content]);
  const music = sections.find((section) => section.type === 'music');
  if (!opened) { const opening = sections.find((section) => section.type === 'opening'); const data = opening?.data ?? {}; const openingBackground = opening?.background?.type && opening.background.type !== 'transparent' ? backgroundStyle(opening.background) : { background: `linear-gradient(135deg, ${primary}, ${secondary})` }; const openingTextStyle = opening?.textStyle; const openingTextColor = openingTextStyle?.textColor || '#ffffff'; const openingHeadingColor = openingTextStyle?.headingColor || openingTextColor; const openingAlignment = openingTextStyle?.alignment ?? 'center'; return <div className={`min-h-dvh overflow-hidden ${forceMobileLayout ? 'invitation-mobile-preview' : ''}`} style={{ ...style, ...openingBackground, color: openingTextColor, fontFamily: openingTextStyle?.bodyFont ?? theme.bodyFont }}><div className="mx-auto flex min-h-dvh max-w-5xl flex-col justify-center px-6" style={{ textAlign: openingAlignment }}><p className="text-xs font-semibold uppercase tracking-[.35em] opacity-75">{text(data, 'overline') || 'M&M Eventos'}</p><p className="mt-8 max-w-md text-lg opacity-85" style={openingAlignment === 'center' ? { marginLeft: 'auto', marginRight: 'auto' } : undefined}>{text(data, 'message') || 'Tenemos una invitación especial para'}</p><h1 className="mt-5 text-4xl font-semibold sm:text-6xl" style={{ fontFamily: openingTextStyle?.headingFont ?? theme.headingFont, color: openingHeadingColor }}>{recipient ? fullName(recipient) : text(data, 'recipientText') || 'vos'}</h1>{text(data, 'eventLabel') || invitation.celebrationType ? <p className="mt-10 text-sm uppercase tracking-[.28em] opacity-70">{text(data, 'eventLabel') || invitation.celebrationType}</p> : null}<h2 className="mt-3 text-4xl font-semibold sm:text-6xl" style={{ fontFamily: openingTextStyle?.headingFont ?? theme.headingFont, color: openingHeadingColor }}>{text(data, 'eventTitle') || invitation.title}</h2><button type="button" className="mt-12 min-h-12 w-fit rounded-xl px-7 text-sm font-semibold shadow-lg transition hover:scale-[1.02]" style={{ backgroundColor: '#fffaf0', color: secondary, alignSelf: openingAlignment === 'center' ? 'center' : openingAlignment === 'right' ? 'flex-end' : 'flex-start' }} onClick={() => { setOpened(true); setMusicOn(Boolean(text(data, 'musicUrl') || text(music?.data ?? {}, 'url'))); }}>{text(data, 'buttonLabel') || 'Abrir invitación'}</button></div></div>; }
  return <main className={`min-h-dvh overflow-x-hidden ${forceMobileLayout ? 'invitation-mobile-preview' : ''}`} style={{ ...style, ...backgroundStyle(invitation.generalBackground), backgroundColor: background, color: textColor, fontFamily: theme.bodyFont }}>
    {sections.filter((section) => section.type !== 'opening' && section.type !== 'music' && (mode !== 'example' || (!['share', 'gift_registry'].includes(section.type) && (showRsvp || section.type !== 'rsvp')))).map((section) => <InvitationSectionRenderer key={section.id} section={section} invitation={invitation} recipient={recipient} mode={mode} onRsvp={onRsvp} saving={saving} error={error} onOpenImage={setGalleryImage} onOpenMap={() => setMapOpen(true)} />)}
    {mode !== 'example' && music && text(music.data, 'url') ? <MusicButton src={text(music.data, 'url')} active={musicOn} onChange={setMusicOn} label={text(music.data, 'label') || 'Música'} volume={typeof music.data.volume === 'number' ? music.data.volume : .5} /> : null}
    {galleryImage ? <div className="fixed inset-0 z-50 grid place-items-center bg-zinc-950/85 p-5" onClick={() => setGalleryImage(undefined)}><img src={galleryImage} alt="Vista ampliada" className="max-h-full max-w-full rounded-xl object-contain" /><button className="absolute right-5 top-5 rounded-full bg-white p-3 text-zinc-950" aria-label="Cerrar imagen"><X className="h-5 w-5" /></button></div> : null}
    {mapOpen && mapQuery(invitation) ? <MapModal invitation={invitation} onClose={() => setMapOpen(false)} /> : null}
  </main>;
}

function InvitationSectionRenderer({ section, invitation, recipient, mode, onRsvp, saving, error, onOpenImage, onOpenMap }: { section: InvitationSection; invitation: DigitalInvitation; recipient?: InvitationGuest; mode: 'public' | 'preview' | 'example'; onRsvp?: (payload: RsvpPayload) => Promise<void>; saving?: boolean; error?: string; onOpenImage: (url: string) => void; onOpenMap: () => void }) {
  const data = section.data; const padding = { paddingTop: section.spacing?.paddingTop ?? 64, paddingBottom: section.spacing?.paddingBottom ?? 64, paddingLeft: section.spacing?.paddingLeft, paddingRight: section.spacing?.paddingRight }; const alignment = section.textStyle?.alignment ?? 'center'; const headingSizeClass = section.textStyle?.headingSize ? '[&_h1]:text-[length:var(--section-heading-size)] [&_h2]:text-[length:var(--section-heading-size)] [&_h3]:text-[length:var(--section-heading-size)]' : ''; const headingColorClass = section.textStyle?.headingColor ? '[&_h1]:text-[color:var(--section-heading-color)] [&_h2]:text-[color:var(--section-heading-color)] [&_h3]:text-[color:var(--section-heading-color)]' : ''; const common = { ...padding, ...backgroundStyle(section.background), textAlign: alignment as CSSProperties['textAlign'], color: section.textStyle?.textColor, fontFamily: section.textStyle?.bodyFont, fontSize: section.textStyle?.bodySize ? `${section.textStyle.bodySize}px` : undefined, '--invitation-heading-font': section.textStyle?.headingFont, '--section-heading-size': section.textStyle?.headingSize ? `${section.textStyle.headingSize}px` : undefined, '--section-heading-color': section.textStyle?.headingColor } as CSSProperties;
  const wrap = (children: ReactNode, extra = '') => <section className={`relative ${headingSizeClass} ${headingColorClass} ${extra}`} style={common}><div className="mx-auto w-full px-5 sm:px-8" style={{ maxWidth: section.layout === 'full' ? undefined : 1100 }}>{children}</div></section>;
  switch (section.type) {
    case 'hero': { const image = text(data, 'imageUrl') || invitation.coverImageUrl || invitation.coverImage; return <section className={`relative grid min-h-[70svh] place-items-center overflow-hidden px-5 text-white ${headingSizeClass} ${headingColorClass}`} style={{ ...common, background: image ? `linear-gradient(0deg, ${String(section.background.image?.overlayColor ?? '#111827')}99, ${String(section.background.image?.overlayColor ?? '#111827')}33), url(${image}) center / cover` : `linear-gradient(135deg, var(--invitation-primary), var(--invitation-secondary))` }}><div className="relative mx-auto max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[.3em] text-white/75">M&M Eventos</p><h1 className="mt-5 text-5xl font-semibold leading-tight sm:text-7xl" style={{ fontFamily: 'var(--invitation-heading-font)', color: section.textStyle?.headingColor }}>{text(data, 'title') || invitation.title}</h1>{text(data, 'subtitle') || invitation.honoreeName ? <p className="mt-5 text-xl text-white/85">{text(data, 'subtitle') || invitation.honoreeName}</p> : null}<p className="mt-8 text-base text-white/85">{formatDateTime(invitation.eventDate)}</p></div></section>; }
    case 'welcome': { const imageUrl = text(data, 'imageUrl'); const imagePosition = text(data, 'imagePosition') || 'top'; const imageStyle = text(data, 'imageStyle') || 'arch'; const configuredMessage = text(data, 'message'); const message = configuredMessage === 'Nos encantaría que nos acompañes.' && invitation.introduction ? invitation.introduction : configuredMessage || invitation.introduction || 'Nos encantaría que nos acompañes.'; const imageClass = imageStyle === 'circle' ? 'aspect-square rounded-full' : imageStyle === 'rounded' ? 'aspect-[4/5] rounded-3xl' : 'aspect-[3/4] rounded-t-[999px] rounded-b-2xl'; const photo = imageUrl ? <div className="mx-auto w-full max-w-sm"><img src={imageUrl} alt={text(data, 'title') || 'Imagen de bienvenida'} className={`h-full w-full object-cover ${imageClass}`} style={{ border: '3px solid var(--invitation-primary)', padding: 5 }} /></div> : null; const copy = <div className="min-w-0"><h2 className="text-3xl font-semibold sm:text-5xl" style={{ fontFamily: 'var(--invitation-heading-font)', color: section.textStyle?.headingColor }}>{text(data, 'title') || 'Una celebración especial'}</h2><p className="mt-6 whitespace-pre-line text-lg leading-8" style={{ color: section.textStyle?.textColor }}>{message}</p>{text(data, 'signature') ? <p className="mt-7 text-xl" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{text(data, 'signature')}</p> : null}</div>; return wrap(<div className={`mx-auto max-w-4xl ${imageUrl && imagePosition !== 'top' ? `grid items-center gap-8 sm:grid-cols-2 ${imagePosition === 'right' ? 'sm:[&>*:first-child]:order-2' : ''}` : 'max-w-2xl'}`}>{imagePosition === 'top' ? <>{photo}{photo ? <div className="mt-9">{copy}</div> : copy}</> : <>{photo}{copy}</>}</div>); }
    case 'message': return wrap(<div className="mx-auto max-w-2xl"><h2 className="text-3xl font-semibold sm:text-5xl" style={{ fontFamily: 'var(--invitation-heading-font)', color: section.textStyle?.headingColor }}>{text(data, 'title') || 'Una celebración especial'}</h2><p className="mt-6 whitespace-pre-line text-lg leading-8" style={{ color: section.textStyle?.textColor }}>{text(data, 'message') || invitation.introduction || 'Nos encantaría que nos acompañes.'}</p>{text(data, 'signature') ? <p className="mt-7 text-xl" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{text(data, 'signature')}</p> : null}</div>);
    case 'custom': return wrap(<div className="mx-auto max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.24em]" style={{ color: 'var(--invitation-primary)' }}>{text(data, 'eyebrow')}</p><h2 className="mt-4 text-3xl font-semibold sm:text-5xl" style={{ fontFamily: 'var(--invitation-heading-font)', color: section.textStyle?.headingColor }}>{text(data, 'title') || 'Título de la sección'}</h2><p className="mt-6 whitespace-pre-line text-lg leading-8" style={{ color: section.textStyle?.textColor }}>{text(data, 'body')}</p></div>);
    case 'event_details': return wrap(<div className="mx-auto grid max-w-4xl gap-4 sm:grid-cols-2">{calendarUrl(invitation) ? <a href={calendarUrl(invitation)} target="_blank" rel="noreferrer" className="rounded-2xl transition hover:-translate-y-0.5 hover:shadow-lg"><Info icon={<CalendarDays />} label={text(data, 'pretitle') || 'Cuándo'} value={formatDateTime(invitation.eventDate)} action="Agendar en Google Calendar" /></a> : <Info icon={<CalendarDays />} label={text(data, 'pretitle') || 'Cuándo'} value={formatDateTime(invitation.eventDate)} />}{mapQuery(invitation) ? <button type="button" onClick={onOpenMap} className="rounded-2xl text-left transition hover:-translate-y-0.5 hover:shadow-lg"><Info icon={<MapPin />} label="Dónde" value={invitation.address || 'Ver ubicación'} action="Ver mapa" /></button> : <Info icon={<MapPin />} label="Dónde" value={invitation.address || 'Ubicación a confirmar'} />}</div>);
    case 'countdown': return wrap(<Countdown date={invitation.eventDate} title={text(data, 'title') || 'Falta muy poco'} />);
    case 'venue': return wrap(<div className="mx-auto max-w-3xl"><h2 className="text-3xl font-semibold" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{text(data, 'title') || 'Dónde nos encontramos'}</h2><p className="mt-4 text-lg">{invitation.address || text(data, 'description')}</p>{text(data, 'description') ? <p className="mt-2 text-sm text-[color:var(--invitation-muted)]">{text(data, 'description')}</p> : null}{invitation.mapsUrl ? <a className="mt-7 inline-flex min-h-12 items-center rounded-xl px-5 text-sm font-semibold" style={{ backgroundColor: 'var(--invitation-primary)', color: 'var(--invitation-on-primary)' }} href={invitation.mapsUrl} target="_blank" rel="noreferrer"><Navigation className="mr-2 h-4 w-4" />Cómo llegar</a> : null}</div>);
    case 'map': return invitation.mapsUrl ? wrap(<a className="mx-auto block max-w-4xl rounded-3xl p-10 text-white" style={{ background: 'linear-gradient(135deg, var(--invitation-primary), var(--invitation-secondary))' }} href={invitation.mapsUrl} target="_blank" rel="noreferrer"><MapPin className="mx-auto h-8 w-8" /><p className="mt-3 font-semibold">Abrir ubicación en Maps</p></a>) : null;
    case 'gallery': { const items = list(data, 'items').filter((item): item is { url: string; altText?: string } => typeof item === 'object' && item !== null && typeof (item as { url?: unknown }).url === 'string'); if (!items.length) return mode === 'preview' ? wrap(<p className="text-sm text-[color:var(--invitation-muted)]">La galería aparecerá aquí cuando subas fotografías.</p>) : null; return wrap(<div><h2 className="text-3xl font-semibold" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{text(data, 'title') || 'Momentos para recordar'}</h2><div className={`mt-7 grid gap-3 ${text(data, 'layout') === 'editorial' ? 'sm:grid-cols-3' : 'grid-cols-2 sm:grid-cols-3'}`}>{items.map((item, index) => <button key={`${item.url}-${index}`} type="button" onClick={() => onOpenImage(item.url)} className={`${index === 0 && text(data, 'layout') === 'editorial' ? 'sm:col-span-2 sm:row-span-2' : ''} overflow-hidden rounded-2xl`}><img className="h-48 w-full object-cover transition hover:scale-105 sm:h-60" src={item.url} alt={item.altText ?? 'Foto de la celebración'} /></button>)}</div></div>); }
    case 'schedule': { const items = list(data, 'items').filter((item): item is { time?: string; title?: string; description?: string } => typeof item === 'object' && item !== null); if (!items.length) return mode === 'preview' ? wrap(<p className="text-sm text-[color:var(--invitation-muted)]">Configurá los momentos de la celebración.</p>) : null; return wrap(<div className="mx-auto max-w-3xl"><h2 className="text-3xl font-semibold" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{text(data, 'title') || 'Momentos de la noche'}</h2><ol className="mt-8 space-y-5 border-l-2 pl-6" style={{ borderColor: 'var(--invitation-accent)' }}>{items.map((item, index) => <li key={`${item.title}-${index}`}><p className="font-semibold" style={{ color: 'var(--invitation-primary)' }}>{item.time}</p><h3 className="mt-1 text-lg font-semibold">{item.title}</h3>{item.description ? <p className="mt-1 text-sm text-[color:var(--invitation-muted)]">{item.description}</p> : null}</li>)}</ol></div>); }
    case 'dress_code': return wrap(<div className="mx-auto max-w-2xl"><Shirt className="mx-auto h-8 w-8" style={{ color: 'var(--invitation-primary)' }} /><h2 className="mt-4 text-3xl font-semibold" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{text(data, 'title') || 'Dress code'}</h2><p className="mt-4 text-lg">{text(data, 'description') || invitation.dressCode}</p><div className="mt-5 flex justify-center gap-3">{list(data, 'colors').filter((color): color is string => typeof color === 'string').map((color) => <span key={color} className="h-9 w-9 rounded-full border border-white shadow" style={{ background: color }} />)}</div></div>);
    case 'gift_registry': return wrap(<GiftSection data={data} />);
    case 'rsvp': return wrap(<RsvpSection data={data} recipient={recipient} mode={mode} onRsvp={onRsvp} saving={saving} error={error} />);
    case 'contact': return wrap(<div><h2 className="text-3xl font-semibold" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{text(data, 'title') || 'Contacto'}</h2><p className="mt-4">{text(data, 'phone')} {text(data, 'email') ? `· ${text(data, 'email')}` : ''}</p></div>);
    case 'footer': return wrap(<p className="text-sm text-[color:var(--invitation-muted)]">{text(data, 'message') || '¡Te esperamos!'}</p>);
    default: return null;
  }
}

function Countdown({ date, title }: { date?: string; title: string }) { const [remaining, setRemaining] = useState(() => Math.max(0, date ? new Date(date).getTime() - Date.now() : 0)); useEffect(() => { const id = window.setInterval(() => setRemaining(Math.max(0, date ? new Date(date).getTime() - Date.now() : 0)), 1000); return () => window.clearInterval(id); }, [date]); if (!date) return null; const units = [{ label: 'Días', value: Math.floor(remaining / 86400000) }, { label: 'Horas', value: Math.floor(remaining / 3600000) % 24 }, { label: 'Min', value: Math.floor(remaining / 60000) % 60 }, { label: 'Seg', value: Math.floor(remaining / 1000) % 60 }]; return <div><h2 className="text-3xl font-semibold" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{title}</h2><div className="mt-7 grid grid-cols-4 gap-2 sm:gap-4">{units.map((unit) => <div key={unit.label} className="rounded-2xl p-3 sm:p-5" style={{ background: 'var(--invitation-surface)', boxShadow: '0 10px 30px rgba(0,0,0,.08)' }}><strong className="text-2xl sm:text-4xl" style={{ color: 'var(--invitation-primary)' }}>{String(unit.value).padStart(2, '0')}</strong><p className="mt-1 text-xs uppercase tracking-wide text-[color:var(--invitation-muted)]">{unit.label}</p></div>)}</div></div>; }
function Info({ icon, label, value, action }: { icon: ReactNode; label: string; value: string; action?: string }) { return <div className="rounded-2xl p-5 text-left" style={{ background: 'var(--invitation-surface)', boxShadow: '0 10px 30px rgba(0,0,0,.08)' }}><span style={{ color: 'var(--invitation-primary)' }}>{icon}</span><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-[color:var(--invitation-muted)]">{label}</p><p className="mt-1 font-medium">{value}</p>{action ? <p className="mt-3 text-xs font-semibold" style={{ color: 'var(--invitation-primary)' }}>{action} →</p> : null}</div>; }
function MapModal({ invitation, onClose }: { invitation: DigitalInvitation; onClose: () => void }) { const query = mapQuery(invitation); const src = `https://www.google.com/maps?q=${encodeURIComponent(query)}&output=embed`; const mapsUrl = invitation.mapsUrl || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`; return <div className="fixed inset-0 z-50 grid place-items-center bg-zinc-950/65 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" aria-label="Ubicación del evento" className="w-full max-w-3xl overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-start justify-between gap-4 border-b px-5 py-4"><div><h2 className="font-semibold text-zinc-950">Ubicación del evento</h2><p className="mt-1 text-sm text-zinc-500">{invitation.address || 'Ubicación configurada para la invitación'}</p></div><button type="button" aria-label="Cerrar mapa" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full text-zinc-600 hover:bg-zinc-100"><X className="h-5 w-5" /></button></header><iframe title="Mapa de la ubicación del evento" src={src} className="h-[55svh] min-h-80 w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><footer className="flex justify-end border-t p-4"><a href={mapsUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center rounded-xl px-4 text-sm font-semibold text-white" style={{ backgroundColor: 'var(--invitation-primary)' }}>Abrir en Google Maps</a></footer></section></div>; }
function GiftSection({ data }: { data: SectionData }) { const [show, setShow] = useState(false); const details = [{ label: 'Alias', value: text(data, 'alias') }, { label: 'CBU', value: text(data, 'cbu') }, { label: 'Banco', value: text(data, 'bank') }, { label: 'Titular', value: text(data, 'holder') }].filter((detail) => Boolean(detail.value)); const copy = async (value: string) => { await navigator.clipboard.writeText(value); }; return <div className="mx-auto max-w-2xl"><Gift className="mx-auto h-8 w-8" style={{ color: 'var(--invitation-primary)' }} /><h2 className="mt-4 text-3xl font-semibold" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{text(data, 'title') || 'Regalos'}</h2><p className="mt-4">{text(data, 'message')}</p>{details.length ? <><Button className="mt-6" onClick={() => setShow((current) => !current)}>{show ? 'Ocultar datos' : 'Ver datos'}</Button>{show ? <div className="mt-5 rounded-2xl p-5 text-left" style={{ background: 'var(--invitation-surface)' }}>{details.map((detail, index) => <button key={detail.label} type="button" aria-label={`Copiar ${detail.label}`} className={`flex w-full items-center justify-between py-3 text-left ${index < details.length - 1 ? 'border-b' : ''}`} onClick={() => void copy(detail.value)}><span>{detail.label}: <strong>{detail.value}</strong></span><Copy className="h-4 w-4" /></button>)}</div> : null}</> : null}</div>; }
function RsvpSection({ data, recipient, mode, onRsvp, saving, error }: { data: SectionData; recipient?: InvitationGuest; mode: 'public' | 'preview' | 'example'; onRsvp?: (payload: RsvpPayload) => Promise<void>; saving?: boolean; error?: string }) { const [form, setForm] = useState({ response: 'confirmed', fullName: '', dietaryRestrictions: '', musicRequest: '', guestMessage: '' }); const submit = (event: FormEvent) => { event.preventDefault(); if (onRsvp) void onRsvp({ ...form, fullName: recipient ? undefined : form.fullName }); }; return <form onSubmit={submit} className="mx-auto max-w-xl rounded-3xl p-6 text-left sm:p-8" style={{ background: 'var(--invitation-surface)', boxShadow: '0 15px 40px rgba(0,0,0,.1)' }}><h2 className="text-center text-3xl font-semibold" style={{ fontFamily: 'var(--invitation-heading-font)' }}>{text(data, 'title') || 'Confirmá tu asistencia'}</h2><p className="mt-2 text-center text-sm text-[color:var(--invitation-muted)]">{text(data, 'subtitle') || 'Nos encantaría contar con tu presencia.'}</p>{!recipient ? <label className="mt-5 block text-sm font-medium">Apellido y nombre<Input className="mt-1" required value={form.fullName} onChange={(event) => setForm((current) => ({ ...current, fullName: event.target.value }))} placeholder="Ej.: Martínez Sofía" /></label> : null}<label className="mt-5 block text-sm font-medium">¿Vas a asistir?<Select className="mt-1.5" value={form.response} onChange={(event) => setForm((current) => ({ ...current, response: event.target.value }))}><option value="confirmed">Sí, voy a asistir</option><option value="declined">No voy a poder asistir</option></Select></label><label className="mt-4 block text-sm font-medium">Restricción alimentaria<Textarea className="mt-1" value={form.dietaryRestrictions} onChange={(event) => setForm((current) => ({ ...current, dietaryRestrictions: event.target.value }))} placeholder="Ej.: Celíaco/a, vegetariano/a o ninguna" /></label><label className="mt-4 block text-sm font-medium">Música que no puede faltar<Textarea className="mt-1" value={form.musicRequest} onChange={(event) => setForm((current) => ({ ...current, musicRequest: event.target.value }))} placeholder="Ej.: Un tema o artista favorito" /></label><label className="mt-4 block text-sm font-medium">Mensaje<Textarea className="mt-1" value={form.guestMessage} onChange={(event) => setForm((current) => ({ ...current, guestMessage: event.target.value }))} placeholder="Dejá un mensaje para los anfitriones" /></label>{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}<Button type="submit" disabled={saving || mode !== 'public'} className="mt-5 w-full" style={{ backgroundColor: 'var(--invitation-primary)', color: 'var(--invitation-on-primary)' }}>{mode === 'preview' ? 'Vista previa de RSVP' : saving ? 'Guardando…' : 'Confirmar asistencia'}</Button></form>; }
function MusicButton({ src, active, onChange, label }: { src: string; active: boolean; onChange: (value: boolean) => void; label: string; volume: number }) { const toggle = () => onChange(!active); return <>{active ? <audio src={src} autoPlay loop /> : null}<button type="button" onClick={toggle} className="fixed bottom-5 right-5 z-30 inline-flex min-h-12 items-center rounded-full px-4 text-sm font-semibold shadow-xl" style={{ backgroundColor: 'var(--invitation-primary)', color: 'var(--invitation-on-primary)' }}>{active ? <Pause className="mr-2 h-4 w-4" /> : <Music2 className="mr-2 h-4 w-4" />}{label}</button></>; }
