'use client';
import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, MapPin, Ticket } from 'lucide-react';
import { api } from '@/lib/api';
import { Button, Input } from '@/components/ui/primitives';
import type { DigitalTicket, TicketPublication } from './types'; import { formatDateTime, money } from './types';
function Frame({ children }: { children: React.ReactNode }) { return <main className="min-h-dvh bg-zinc-100 px-4 py-8"><div className="mx-auto max-w-xl">{children}</div></main>; }
export function PublicTickets({ slug }: { slug: string }) { const [publication, setPublication] = useState<TicketPublication>(); const [quantities, setQuantities] = useState<Record<string, number>>({}); const [buyer, setBuyer] = useState({ name: '', email: '', phone: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { void api.get<{ publication: TicketPublication; types: TicketPublication['ticketTypes'] }>(`/public/tickets/${slug}`).then((data) => setPublication({ ...data.publication, ticketTypes: data.types })).catch((cause: Error) => setError(cause.message)); }, [slug]);
  const count = Object.values(quantities).reduce((sum, value) => sum + value, 0); const total = useMemo(() => (publication?.ticketTypes ?? []).reduce((sum, type) => sum + (quantities[type._id] ?? 0) * (type.price ?? 0), 0), [publication, quantities]);
  const reserve = async (event: React.FormEvent) => { event.preventDefault(); if (!count) return setError('Elegí al menos una entrada.'); setSaving(true); try { await api.post(`/public/tickets/${slug}/orders`, { buyer, selections: Object.entries(quantities).filter(([, quantity]) => quantity).map(([ticketTypeId, quantity]) => ({ ticketTypeId, quantity })), idempotencyKey: crypto.randomUUID() }); setError('Reserva creada. Vas a recibir la confirmación de pago por email.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo crear la reserva.'); } finally { setSaving(false); } };
  if (!publication) return <Frame><p className="rounded-2xl bg-white p-6">{error || 'Cargando entradas…'}</p></Frame>;
  return <Frame><article className="overflow-hidden rounded-3xl bg-white shadow-xl"><header className="min-h-48 bg-zinc-900 p-7 text-white" style={publication.coverImage ? { backgroundImage: `linear-gradient(0deg,rgba(9,9,11,.75),rgba(9,9,11,.15)),url(${publication.coverImage})`, backgroundSize: 'cover' } : undefined}><p className="text-sm text-amber-200">ENTRADAS DIGITALES</p><h1 className="mt-14 text-3xl font-semibold">{publication.title}</h1></header><form onSubmit={(event) => void reserve(event)} className="space-y-5 p-6"><p>{publication.description}</p><p className="flex gap-2 text-sm"><CalendarDays className="h-5" />{formatDateTime(publication.startsAt)}</p><p className="flex gap-2 text-sm"><MapPin className="h-5" />{[publication.venueName, publication.address].filter(Boolean).join(' · ')}</p>{(publication.ticketTypes ?? []).map((type) => <div className="flex items-center gap-3 border-t pt-4" key={type._id}><Ticket className="h-5 text-amber-700" /><div className="flex-1"><b>{type.name}</b><p className="text-sm text-zinc-500">{money(type.price)}</p></div><Input className="w-16" type="number" min="0" max={type.maxPerOrder ?? 10} value={quantities[type._id] ?? 0} onChange={(e) => setQuantities((current) => ({ ...current, [type._id]: Number(e.target.value) }))} /></div>)}<div className="grid gap-2 sm:grid-cols-3"><Input required placeholder="Nombre" value={buyer.name} onChange={(e) => setBuyer({ ...buyer, name: e.target.value })} /><Input required type="email" placeholder="Email" value={buyer.email} onChange={(e) => setBuyer({ ...buyer, email: e.target.value })} /><Input placeholder="Teléfono" value={buyer.phone} onChange={(e) => setBuyer({ ...buyer, phone: e.target.value })} /></div>{error ? <p className="text-sm text-amber-800">{error}</p> : null}<Button className="w-full" disabled={saving}>{saving ? 'Reservando…' : `Reservar · ${money(total)}`}</Button></form></article></Frame>; }
export function PublicTicket({ token }: { token: string }) { const [ticket, setTicket] = useState<DigitalTicket>(); const [qr, setQr] = useState(''); useEffect(() => { void api.get<{ ticket: DigitalTicket; qrDataUrl: string }>(`/public/ticket/${token}`).then((data) => { setTicket(data.ticket); setQr(data.qrDataUrl); }); }, [token]); if (!ticket) return <Frame><p>Cargando entrada…</p></Frame>; return <Frame><article className="rounded-3xl bg-white p-7 text-center shadow-xl"><p className="text-sm text-amber-700">ENTRADA DIGITAL</p><h1 className="mt-3 text-3xl font-semibold">{ticket.publicationName}</h1><p className="mt-2">{ticket.attendeeName}</p>{qr ? <img src={qr} alt="Código QR" className="mx-auto my-6 h-56 w-56" /> : <b>{ticket.publicToken}</b>}<p>{ticket.ticketTypeName}</p><p className="mt-2 text-sm">{formatDateTime(ticket.startsAt)}<br />{ticket.venueName || ticket.address}</p><p className="mt-4">Estado: <b>{ticket.status}</b></p></article></Frame>; }
