'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Button, Input, PageHeader, Textarea } from '@/components/ui/primitives';
import type { TicketPublication, TicketType } from './types';

export function TicketPublicationsAdmin() {
  const [items, setItems] = useState<TicketPublication[]>([]); const [title, setTitle] = useState(''); const [slug, setSlug] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => api.get<{ publications: TicketPublication[] }>('/tickets/publications').then((data) => setItems(data.publications)).catch((cause: Error) => setError(cause.message)).finally(() => setLoading(false)); useEffect(() => { void load(); }, []);
  const create = async () => { if (!title || !slug) return; const publication = await api.post<{ publication: TicketPublication }>('/tickets/publications', { title, slug, startsAt: new Date().toISOString(), capacity: 0 }); setItems((current) => [publication.publication, ...current]); setTitle(''); setSlug(''); };
  return <section className="space-y-6"><PageHeader title="Entradas Digitales" description="Publicaciones autónomas: no requieren eventos, salones ni clientes." /><div className="flex flex-wrap gap-2 rounded-2xl border bg-white p-4"><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Nombre de la actividad" /><Input value={slug} onChange={(e) => setSlug(e.target.value)} placeholder="slug-publico" /><Button onClick={() => void create()} disabled={!title || !slug}>Crear publicación</Button></div>{error ? <p className="text-sm text-red-700">{error}</p> : null}{loading ? <p className="text-sm text-zinc-500">Cargando publicaciones…</p> : <div className="grid gap-3">{items.map((item) => <Link className="rounded-2xl border bg-white p-5 hover:border-amber-400" key={item._id} href={`/admin/digital-tickets/${item._id}`}><b>{item.title}</b><p className="mt-1 text-sm text-zinc-500">{item.status} · {item.slug}</p></Link>)}{!items.length ? <p className="rounded-2xl border bg-white p-8 text-center text-zinc-500">Todavía no hay publicaciones.</p> : null}</div>}</section>;
}
export function TicketPublicationAdmin({ publicationId }: { publicationId: string }) {
  const [publication, setPublication] = useState<TicketPublication>(); const [types, setTypes] = useState<TicketType[]>([]); const [name, setName] = useState(''); const [price, setPrice] = useState(0); const [capacity, setCapacity] = useState(0); const [description, setDescription] = useState('');
  const load = () => api.get<{ publication: TicketPublication; types: TicketType[] }>(`/tickets/publications/${publicationId}`).then((data) => { setPublication(data.publication); setTypes(data.types); }); useEffect(() => { void load(); }, [publicationId]);
  const addType = async () => { const data = await api.post<{ ticketType: TicketType }>(`/tickets/publications/${publicationId}/types`, { name, price, capacity }); setTypes((current) => [...current, data.ticketType]); setName(''); };
  const publish = async () => { const data = await api.patch<{ publication: TicketPublication }>(`/tickets/publications/${publicationId}`, { status: publication?.status === 'active' ? 'paused' : 'active' }); setPublication(data.publication); };
  if (!publication) return <p className="text-sm text-zinc-500">Cargando publicación…</p>;
  return <section className="space-y-6"><PageHeader title={publication.title} description="Configuración independiente de entradas digitales." action={<div className="flex gap-2"><Link href={`/admin/digital-tickets/${publicationId}/check-in`}><Button variant="secondary">Control de ingreso</Button></Link><Button onClick={() => void publish()}>{publication.status === 'active' ? 'Pausar' : 'Publicar'}</Button></div>} /><div className="rounded-2xl border bg-white p-5"><Textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Descripción (se configura en edición completa)" /><div className="mt-4 flex flex-wrap gap-2"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Tipo de entrada" /><Input type="number" value={price} onChange={(e) => setPrice(Number(e.target.value))} placeholder="Precio" /><Input type="number" value={capacity} onChange={(e) => setCapacity(Number(e.target.value))} placeholder="Cupo" /><Button onClick={() => void addType()} disabled={!name}>Agregar tipo</Button></div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Tipos de entrada</h2>{types.map((type) => <p className="mt-3 border-t pt-3" key={type._id}><b>{type.name}</b> · {type.price ?? 0} · cupo {type.capacity}</p>)}</div>{publication.slug ? <Link href={`/entradas/${publication.slug}`} target="_blank"><Button variant="secondary">Abrir venta pública</Button></Link> : null}</section>;
}
