import { connectDatabase, disconnectDatabase } from '../db/connection';
import { Types } from 'mongoose';
import { DigitalTicket, TicketOrder, TicketPayment, TicketPublication, TicketRefund, TicketStockReservation, TicketType } from '../modules/tickets/ticket.models';

const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=85`;
const publications = [
  { slug: 'demo-festival-cielo-abierto', internalName: 'DEMO · Festival Cielo Abierto', title: 'Festival Cielo Abierto', category: 'Festival', description: 'Una jornada de música en vivo, gastronomía y experiencias al aire libre.', coverImage: image('photo-1501386761578-eac5c94b800a'), startsAt: new Date('2026-09-19T17:00:00-03:00'), endsAt: new Date('2026-09-20T01:00:00-03:00'), venueName: 'Predio M&M La Plata', address: 'Camino General Belgrano 4500, La Plata', capacity: 420, types: [{ key: 'general', name: 'Entrada general', price: 18000, promotionalPrice: 15000, capacity: 300, sold: 84, reserved: 6 }, { key: 'vip', name: 'Experiencia VIP', price: 42000, capacity: 80, sold: 22, reserved: 2 }, { key: 'kids', name: 'Menores de 12 años', price: 9000, capacity: 40, sold: 11, reserved: 0 }] },
  { slug: 'demo-noche-retro-2000', internalName: 'DEMO · Noche Retro 2000', title: 'Noche Retro 2000', category: 'Fiesta', description: 'Hits, visuales y una pista para volver a bailar como en los 2000.', coverImage: image('photo-1571266028243-d220c9c3bde7'), startsAt: new Date('2026-08-29T23:30:00-03:00'), endsAt: new Date('2026-08-30T05:30:00-03:00'), venueName: 'M&M Villa Elisa', address: 'Calle 419 2253, Villa Elisa', capacity: 260, types: [{ key: 'early', name: 'Early bird', price: 12000, capacity: 120, sold: 120, reserved: 0 }, { key: 'general', name: 'Entrada general', price: 16000, capacity: 120, sold: 45, reserved: 4 }, { key: 'vip', name: 'Mesa VIP para 4', price: 68000, capacity: 20, sold: 5, reserved: 0 }] },
  { slug: 'demo-taller-floral', internalName: 'DEMO · Taller Floral', title: 'Taller Floral & Brunch', category: 'Taller', description: 'Diseñá tu propio arreglo floral y disfrutá un brunch de autor.', coverImage: image('photo-1490750967868-88aa4486c946'), startsAt: new Date('2026-10-10T11:00:00-03:00'), endsAt: new Date('2026-10-10T14:00:00-03:00'), venueName: 'M&M San Carlos', address: 'Calle 144 664, San Carlos', capacity: 48, types: [{ key: 'workshop', name: 'Cupo individual', price: 35000, capacity: 42, sold: 12, reserved: 2 }, { key: 'duo', name: 'Dúo creativo', price: 62000, capacity: 6, sold: 2, reserved: 0 }] },
];

async function seedPublication(seed: typeof publications[number]) {
  const sold = seed.types.reduce((sum, type) => sum + type.sold, 0); const reserved = seed.types.reduce((sum, type) => sum + type.reserved, 0);
  const publication: any = await TicketPublication.findOneAndUpdate({ slug: seed.slug }, { $set: { ...seed, types: undefined, visibility: { isPublic: true, showInPublicCatalog: true }, paymentConfig: { enabled: true, provider: 'mercado_pago', reservationMinutes: 25, feePayer: 'organizer' }, saleSettings: { minTicketsPerOrder: 1, maxTicketsPerOrder: 8, reservationMinutes: 25, showRemainingStock: true }, organizer: { name: 'M&M Eventos', email: 'entradas@mmeventos.demo', phone: '+54 9 221 555 0100', instagram: '@mmeventos' }, appearance: { primaryColor: '#18181b', secondaryColor: '#d4a373', backgroundColor: '#fafaf9', textColor: '#18181b' }, gallery: [seed.coverImage], status: 'active', soldCount: sold, reservedCount: reserved, deletedAt: null } }, { upsert: true, new: true, setDefaultsOnInsert: true });
  const types = new Map<string, any>();
  for (let index = 0; index < seed.types.length; index++) { const source = seed.types[index]; const type: any = await TicketType.findOneAndUpdate({ publicationId: publication._id, name: source.name, deletedAt: null }, { $set: { publicationId: publication._id, name: source.name, description: `Acceso ${source.name.toLowerCase()} para ${seed.title}.`, price: source.price, promotionalPrice: source.promotionalPrice, capacity: source.capacity, soldCount: source.sold, reservedCount: source.reserved, minPerOrder: 1, maxPerOrder: 8, status: 'active', displayOrder: index, color: index === 1 ? '#d4a373' : '#18181b', benefits: index === 1 ? ['Acceso preferencial', 'Sector exclusivo'] : [] } }, { upsert: true, new: true, setDefaultsOnInsert: true }); types.set(source.key, type); }
  return { publication, types };
}

async function seedOrder(input: { publication: any; type: any; code: string; buyer: { name: string; email: string; documentNumber: string }; quantity: number; status: 'paid' | 'payment_pending' | 'refunded'; used?: number }) {
  const amount = (input.type.promotionalPrice ?? input.type.price) * input.quantity; const order: any = await TicketOrder.findOneAndUpdate({ publicId: input.code }, { $set: { publicationId: input.publication._id, idempotencyKey: `demo-${input.code}`, buyer: { ...input.buyer, phone: '+54 9 221 555 0199' }, lines: [{ ticketTypeId: input.type._id, name: input.type.name, unitPrice: input.type.promotionalPrice ?? input.type.price, quantity: input.quantity, subtotal: amount }], subtotal: amount, totalAmount: amount, currency: 'ARS', status: input.status, paymentStatus: input.status === 'paid' ? 'paid' : input.status === 'refunded' ? 'refunded' : 'pending', paymentMethod: input.status === 'paid' ? 'mock' : undefined, providerPaymentId: `mock_${input.code}`, paidAt: input.status === 'paid' || input.status === 'refunded' ? new Date() : undefined, expiresAt: input.status === 'payment_pending' ? new Date(Date.now() + 25 * 60_000) : undefined, deletedAt: null } }, { upsert: true, new: true, setDefaultsOnInsert: true });
  const payment: any = await TicketPayment.findOneAndUpdate({ orderId: order._id }, { $set: { orderId: order._id, provider: 'mock', providerPaymentId: `mock_${input.code}`, providerPreferenceId: `mock_pref_${input.code}`, checkoutUrl: `http://localhost:3000/entradas/mock-payment/${input.code}`, status: input.status === 'paid' ? 'approved' : input.status === 'refunded' ? 'refunded' : 'pending', amount, currency: 'ARS', approvedAt: input.status === 'paid' || input.status === 'refunded' ? new Date() : undefined } }, { upsert: true, new: true, setDefaultsOnInsert: true });
  if (input.status === 'payment_pending') await TicketStockReservation.findOneAndUpdate({ orderId: order._id }, { $set: { publicationId: input.publication._id, orderId: order._id, items: [{ ticketTypeId: input.type._id, quantity: input.quantity }], status: 'active', expiresAt: new Date(Date.now() + 25 * 60_000) } }, { upsert: true, new: true });
  if (input.status === 'refunded') await TicketRefund.findOneAndUpdate({ orderId: order._id }, { $set: { orderId: order._id, paymentId: payment._id, provider: 'mock', providerRefundId: `demo-refund-${input.code}`, type: 'full', status: 'approved', amount, reason: 'Demostración de reembolso', requestedBy: new Types.ObjectId(), idempotencyKey: `demo-refund-${input.code}` } }, { upsert: true, new: true, setDefaultsOnInsert: true });
  for (let position = 0; position < input.quantity; position++) { const status = input.status === 'refunded' ? 'refunded' : input.status === 'payment_pending' ? 'reserved' : position < (input.used ?? 0) ? 'used' : 'valid'; await DigitalTicket.findOneAndUpdate({ publicToken: `demo-${input.code}-${position + 1}` }, { $set: { publicationId: input.publication._id, orderId: order._id, ticketTypeId: input.type._id, publicToken: `demo-${input.code}-${position + 1}`, qrPayload: `demo-${input.code}-${position + 1}`, attendeeName: input.buyer.name, attendeeEmail: input.buyer.email, status, issuedAt: input.status === 'paid' || input.status === 'refunded' ? new Date() : undefined, validatedAt: status === 'used' ? new Date() : undefined, accessCount: status === 'used' ? 1 : 0, deletedAt: null } }, { upsert: true, new: true, setDefaultsOnInsert: true }); }
}

async function seed() { await connectDatabase(); const all = await Promise.all(publications.map(seedPublication)); const [festival, retro, floral] = all; await seedOrder({ publication: festival.publication, type: festival.types.get('general'), code: 'DEMO-FEST-001', buyer: { name: 'Sofía Martínez', email: 'sofia.demo@example.com', documentNumber: '40111222' }, quantity: 2, status: 'paid', used: 1 }); await seedOrder({ publication: festival.publication, type: festival.types.get('vip'), code: 'DEMO-FEST-002', buyer: { name: 'Tomás Rivas', email: 'tomas.demo@example.com', documentNumber: '38555666' }, quantity: 1, status: 'payment_pending' }); await seedOrder({ publication: retro.publication, type: retro.types.get('early'), code: 'DEMO-RETRO-001', buyer: { name: 'Valentina Suárez', email: 'valentina.demo@example.com', documentNumber: '41222777' }, quantity: 2, status: 'refunded' }); await seedOrder({ publication: floral.publication, type: floral.types.get('workshop'), code: 'DEMO-FLORAL-001', buyer: { name: 'Lucía Fernández', email: 'lucia.demo@example.com', documentNumber: '39999888' }, quantity: 1, status: 'paid' }); console.info(`Entradas digitales demo preparadas: ${all.length} publicaciones, ventas de todos los estados y QR emitidos.`); }
seed().then(disconnectDatabase).catch(async (error) => { console.error('Seed de entradas digitales falló:', error); await disconnectDatabase(); process.exitCode = 1; });
