import { Permission } from '@mym/shared';

export type PermissionArea = {
  id: string;
  title: string;
  description: string;
  accessPermission: Permission;
  permissions: Array<{ permission: Permission; label: string }>;
};

export const permissionAreas: PermissionArea[] = [
  { id: 'leads', title: 'Leads', description: 'Consultas y oportunidades comerciales.', accessPermission: Permission.LEADS_READ, permissions: [['LEADS_READ', 'Ver'], ['LEADS_CREATE', 'Crear'], ['LEADS_UPDATE', 'Editar'], ['LEADS_ASSIGN', 'Asignar'], ['LEADS_CONVERT', 'Convertir'], ['LEADS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'customers', title: 'Clientes', description: 'Clientes e historial comercial.', accessPermission: Permission.CUSTOMERS_READ, permissions: [['CUSTOMERS_READ', 'Ver'], ['CUSTOMERS_CREATE', 'Crear'], ['CUSTOMERS_UPDATE', 'Editar'], ['CUSTOMERS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'quotes', title: 'Presupuestos', description: 'Solicitudes y propuestas comerciales.', accessPermission: Permission.QUOTES_READ, permissions: [['QUOTES_READ', 'Ver'], ['QUOTES_CREATE', 'Crear'], ['QUOTES_UPDATE', 'Editar'], ['QUOTES_APPROVE', 'Aprobar'], ['QUOTES_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'events', title: 'Eventos y calendario', description: 'Agenda, eventos y operación.', accessPermission: Permission.EVENTS_READ, permissions: [['EVENTS_READ', 'Ver'], ['EVENTS_CREATE', 'Crear'], ['EVENTS_UPDATE', 'Editar'], ['EVENTS_CANCEL', 'Cancelar'], ['EVENTS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'contracts', title: 'Contratos', description: 'Contratos, adendas y aprobaciones.', accessPermission: Permission.CONTRACTS_READ, permissions: [['CONTRACTS_READ', 'Ver'], ['CONTRACTS_CREATE', 'Crear'], ['CONTRACTS_UPDATE', 'Editar'], ['CONTRACTS_APPROVE', 'Aprobar'], ['CONTRACTS_CANCEL', 'Cancelar'], ['CONTRACTS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'payments', title: 'Pagos', description: 'Señas, cuotas, saldos y devoluciones.', accessPermission: Permission.PAYMENTS_READ, permissions: [['PAYMENTS_READ', 'Ver'], ['PAYMENTS_CREATE', 'Registrar'], ['PAYMENTS_UPDATE', 'Editar'], ['PAYMENTS_APPROVE', 'Aprobar'], ['PAYMENTS_REJECT', 'Rechazar'], ['PAYMENTS_CANCEL', 'Cancelar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'suppliers', title: 'Proveedores', description: 'Proveedores y compras.', accessPermission: Permission.SUPPLIERS_READ, permissions: [['SUPPLIERS_READ', 'Ver'], ['SUPPLIERS_CREATE', 'Crear'], ['SUPPLIERS_UPDATE', 'Editar'], ['SUPPLIERS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'salons', title: 'Salones', description: 'Salones, paquetes y reglas comerciales.', accessPermission: Permission.SALONS_READ, permissions: [['SALONS_READ', 'Ver'], ['SALONS_CREATE', 'Crear'], ['SALONS_UPDATE', 'Editar'], ['SALONS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'landing', title: 'Landing pública', description: 'Contenido y visualización del sitio.', accessPermission: Permission.LANDING_READ, permissions: [['LANDING_READ', 'Ver'], ['LANDING_UPDATE', 'Editar y publicar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'users', title: 'Usuarios y staff', description: 'Usuarios, roles, accesos y personal.', accessPermission: Permission.USERS_READ, permissions: [['USERS_READ', 'Ver'], ['USERS_CREATE', 'Crear'], ['USERS_UPDATE', 'Editar'], ['USERS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'settings', title: 'Configuración general', description: 'Parámetros generales del sistema.', accessPermission: Permission.SETTINGS_READ, permissions: [['SETTINGS_READ', 'Ver'], ['SETTINGS_UPDATE', 'Editar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'promotions', title: 'Promociones', description: 'Promociones comerciales disponibles.', accessPermission: Permission.PROMOTIONS_READ, permissions: [['PROMOTIONS_READ', 'Ver'], ['PROMOTIONS_CREATE', 'Crear'], ['PROMOTIONS_UPDATE', 'Editar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'campaigns', title: 'Campañas', description: 'Campañas y comunicaciones comerciales.', accessPermission: Permission.CAMPAIGNS_READ, permissions: [['CAMPAIGNS_READ', 'Ver'], ['CAMPAIGNS_CREATE', 'Crear'], ['CAMPAIGNS_SEND', 'Enviar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'invitations', title: 'Invitaciones', description: 'Invitaciones digitales para eventos.', accessPermission: Permission.INVITATIONS_READ, permissions: [['INVITATIONS_READ', 'Ver'], ['INVITATIONS_CREATE', 'Crear'], ['INVITATIONS_UPDATE', 'Editar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'tickets', title: 'Entradas', description: 'Entradas y validación de accesos.', accessPermission: Permission.TICKETS_READ, permissions: [['TICKETS_READ', 'Ver'], ['TICKETS_CREATE', 'Crear'], ['TICKETS_VALIDATE', 'Validar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'payroll', title: 'Liquidaciones', description: 'Información de pagos al personal.', accessPermission: Permission.PAYROLL_READ, permissions: [['PAYROLL_READ', 'Ver'], ['PAYROLL_MANAGE', 'Administrar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'reports', title: 'Reportes', description: 'Consulta y exportación de información.', accessPermission: Permission.REPORTS_READ, permissions: [['REPORTS_READ', 'Ver'], ['REPORTS_EXPORT', 'Exportar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
];
