import { Permission } from '@mym/shared';

export type PermissionArea = {
  id: string;
  title: string;
  description: string;
  accessPermission: Permission;
  permissions: Array<{ permission: Permission; label: string }>;
};

export const permissionAreas: PermissionArea[] = [
  { id: 'leads', title: 'Leads', description: 'Consultas y oportunidades comerciales.', accessPermission: Permission.LEADS_READ, permissions: [['LEADS_READ', 'Ver'], ['LEADS_CREATE', 'Crear'], ['LEADS_UPDATE', 'Editar'], ['LEADS_ASSIGN', 'Asignar'], ['LEADS_CONVERT', 'Convertir'], ['LEADS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'customers', title: 'Clientes', description: 'Clientes e historial comercial.', accessPermission: Permission.CUSTOMERS_READ, permissions: [['CUSTOMERS_READ', 'Ver'], ['CUSTOMERS_CREATE', 'Crear'], ['CUSTOMERS_UPDATE', 'Editar'], ['CUSTOMERS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'quotes', title: 'Presupuestos', description: 'Solicitudes y propuestas comerciales.', accessPermission: Permission.QUOTES_READ, permissions: [['QUOTES_READ', 'Ver'], ['QUOTES_CREATE', 'Crear'], ['QUOTES_UPDATE', 'Editar'], ['QUOTES_APPROVE', 'Aprobar'], ['QUOTES_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'events', title: 'Eventos y calendario', description: 'Agenda, eventos y operación.', accessPermission: Permission.EVENTS_READ, permissions: [['EVENTS_READ', 'Ver'], ['EVENTS_CREATE', 'Crear'], ['EVENTS_UPDATE', 'Editar'], ['EVENTS_CANCEL', 'Cancelar'], ['EVENTS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'contracts', title: 'Contratos', description: 'Contratos, adendas y aprobaciones.', accessPermission: Permission.CONTRACTS_READ, permissions: [['CONTRACTS_READ', 'Ver'], ['CONTRACTS_CREATE', 'Crear'], ['CONTRACTS_UPDATE', 'Editar'], ['CONTRACTS_APPROVE', 'Aprobar'], ['CONTRACTS_CANCEL', 'Cancelar'], ['CONTRACTS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'payments', title: 'Pagos', description: 'Señas, cuotas, saldos y devoluciones.', accessPermission: Permission.PAYMENTS_READ, permissions: [['PAYMENTS_READ', 'Ver'], ['PAYMENTS_CREATE', 'Registrar'], ['PAYMENTS_UPDATE', 'Editar'], ['PAYMENTS_APPROVE', 'Aprobar'], ['PAYMENTS_REJECT', 'Rechazar'], ['PAYMENTS_CANCEL', 'Cancelar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'suppliers', title: 'Proveedores', description: 'Proveedores y compras.', accessPermission: Permission.SUPPLIERS_READ, permissions: [['SUPPLIERS_READ', 'Ver'], ['SUPPLIERS_CREATE', 'Crear'], ['SUPPLIERS_UPDATE', 'Editar'], ['SUPPLIERS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'salons', title: 'Salones', description: 'Salones, paquetes y reglas comerciales.', accessPermission: Permission.SALONS_READ, permissions: [['SALONS_READ', 'Ver'], ['SALONS_CREATE', 'Crear'], ['SALONS_UPDATE', 'Editar'], ['SALONS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'landing', title: 'Landing pública', description: 'Contenido y visualización del sitio.', accessPermission: Permission.LANDING_READ, permissions: [['LANDING_READ', 'Ver'], ['LANDING_UPDATE', 'Editar y publicar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'users', title: 'Usuarios y staff', description: 'Usuarios, roles, accesos y personal.', accessPermission: Permission.USERS_READ, permissions: [['USERS_READ', 'Ver'], ['USERS_CREATE', 'Crear'], ['USERS_UPDATE', 'Editar'], ['USERS_DELETE', 'Eliminar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'settings', title: 'Configuración general', description: 'Parámetros generales del sistema.', accessPermission: Permission.SETTINGS_READ, permissions: [['SETTINGS_READ', 'Ver'], ['SETTINGS_UPDATE', 'Editar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'promotions', title: 'Promociones', description: 'Promociones comerciales disponibles.', accessPermission: Permission.PROMOTIONS_READ, permissions: [['PROMOTIONS_READ', 'Ver'], ['PROMOTIONS_CREATE', 'Crear'], ['PROMOTIONS_UPDATE', 'Editar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'campaigns', title: 'Campañas', description: 'Campañas y comunicaciones comerciales.', accessPermission: Permission.CAMPAIGNS_READ, permissions: [['CAMPAIGNS_READ', 'Ver'], ['CAMPAIGNS_CREATE', 'Crear'], ['CAMPAIGNS_UPDATE', 'Editar'], ['CAMPAIGNS_SEND', 'Enviar'], ['CAMPAIGNS_CANCEL', 'Cancelar'], ['CAMPAIGNS_RETRY', 'Reintentar'], ['CAMPAIGNS_DELETE', 'Eliminar'], ['CAMPAIGNS_EXPORT', 'Exportar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'marketingTemplates', title: 'Plantillas de marketing', description: 'Plantillas de email reutilizables para campañas.', accessPermission: Permission.MARKETING_TEMPLATES_READ, permissions: [['MARKETING_TEMPLATES_READ', 'Ver'], ['MARKETING_TEMPLATES_MANAGE', 'Administrar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'marketingAudiences', title: 'Audiencias de marketing', description: 'Segmentos de leads y clientes para campañas.', accessPermission: Permission.MARKETING_AUDIENCES_READ, permissions: [['MARKETING_AUDIENCES_READ', 'Ver'], ['MARKETING_AUDIENCES_MANAGE', 'Administrar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'marketingSettings', title: 'Configuración de marketing', description: 'Identidad institucional para campañas de email.', accessPermission: Permission.MARKETING_SETTINGS_READ, permissions: [['MARKETING_SETTINGS_READ', 'Ver'], ['MARKETING_SETTINGS_UPDATE', 'Editar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'invitations', title: 'Invitaciones', description: 'Invitaciones digitales para eventos.', accessPermission: Permission.INVITATIONS_READ, permissions: [['INVITATIONS_READ', 'Ver'], ['INVITATIONS_CREATE', 'Crear'], ['INVITATIONS_UPDATE', 'Editar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'tickets', title: 'Entradas', description: 'Entradas y validación de accesos.', accessPermission: Permission.TICKETS_READ, permissions: [['TICKETS_READ', 'Ver'], ['TICKETS_CREATE', 'Crear'], ['TICKETS_VALIDATE', 'Validar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'payroll', title: 'Liquidación de sueldos', description: 'Perfiles, asistencias aprobadas, liquidaciones, pagos y auditoría salarial.', accessPermission: Permission.PAYROLL_VIEW, permissions: [['PAYROLL_VIEW', 'Ver'], ['PAYROLL_MANAGE_PROFILES', 'Configurar perfiles'], ['PAYROLL_MANAGE_ATTENDANCE', 'Revisar asistencias'], ['PAYROLL_CREATE', 'Crear liquidaciones'], ['PAYROLL_CALCULATE', 'Calcular'], ['PAYROLL_APPROVE', 'Aprobar'], ['PAYROLL_PAY', 'Registrar pagos'], ['PAYROLL_EXPORT', 'Exportar'], ['PAYROLL_AUDIT', 'Ver auditoría']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'mobileStaff', title: 'App móvil de personal', description: 'Acceso a la app móvil y autogestión de asistencia (fichaje, historial, turnos, perfil y liquidaciones propias). No depende únicamente del rol Staff.', accessPermission: Permission.MOBILE_ACCESS, permissions: [['MOBILE_ACCESS', 'Acceso a la app'], ['ATTENDANCE_CLOCK', 'Fichar entrada/salida'], ['ATTENDANCE_HISTORY_SELF', 'Ver su historial'], ['ATTENDANCE_SCHEDULE_SELF', 'Ver sus turnos'], ['ATTENDANCE_INCIDENT_CREATE', 'Reportar incidencias'], ['ATTENDANCE_ADJUSTMENT_REQUEST', 'Solicitar correcciones'], ['PAYROLL_SELF_READ', 'Ver liquidaciones propias'], ['PROFILE_VIEW_SELF', 'Ver su perfil'], ['PROFILE_UPDATE_SELF', 'Editar su perfil'], ['PROFILE_AVATAR_UPDATE', 'Cambiar su avatar'], ['SECURITY_PASSWORD_CHANGE', 'Cambiar su contraseña']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'attendanceManagement', title: 'Gestión de asistencia', description: 'Supervisión de jornadas activas, incidencias, correcciones, configuración y dispositivos del personal.', accessPermission: Permission.ATTENDANCE_READ, permissions: [['ATTENDANCE_READ', 'Ver'], ['ATTENDANCE_MANAGE', 'Administrar'], ['ATTENDANCE_SETTINGS_MANAGE', 'Configurar'], ['MOBILE_DEVICES_MANAGE', 'Gestionar dispositivos']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'dashboard', title: 'Dashboard gerencial', description: 'Indicadores generales, financieros y alcance multi-salón.', accessPermission: Permission.DASHBOARD_VIEW, permissions: [['DASHBOARD_VIEW', 'Ver'], ['DASHBOARD_FINANCIAL_VIEW', 'Ver finanzas'], ['DASHBOARD_ALL_SALONS_VIEW', 'Ver todos los salones']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'reports', title: 'Reportes', description: 'Consulta segmentada y exportación de información.', accessPermission: Permission.REPORTS_READ, permissions: [['REPORTS_READ', 'Ver centro'], ['REPORTS_COMMERCIAL_READ', 'Comerciales'], ['REPORTS_EVENTS_READ', 'Eventos'], ['REPORTS_CONTRACTS_READ', 'Contratos'], ['REPORTS_PAYMENTS_READ', 'Pagos'], ['REPORTS_PRODUCTION_READ', 'Producción'], ['REPORTS_EXPENSES_READ', 'Gastos'], ['REPORTS_PROFITABILITY_READ', 'Rentabilidad'], ['REPORTS_ANALYTICS_READ', 'Analítica'], ['REPORTS_EXPORT', 'Exportar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'production', title: 'Producción', description: 'Planes, ítems, estados y reglas automáticas de producción.', accessPermission: Permission.PRODUCTION_VIEW, permissions: [['PRODUCTION_VIEW', 'Ver'], ['PRODUCTION_CREATE', 'Crear'], ['PRODUCTION_UPDATE', 'Editar'], ['PRODUCTION_COMPLETE', 'Completar'], ['PRODUCTION_REOPEN', 'Reabrir'], ['PRODUCTION_GENERATE', 'Generar'], ['PRODUCTION_EXPORT', 'Exportar'], ['PRODUCTION_RULES_MANAGE', 'Administrar reglas']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'expenses', title: 'Gastos y rentabilidad', description: 'Gastos directos, categorías e información de rentabilidad.', accessPermission: Permission.EXPENSES_VIEW, permissions: [['EXPENSES_VIEW', 'Ver'], ['EXPENSES_CREATE', 'Crear'], ['EXPENSES_UPDATE', 'Editar'], ['EXPENSES_DELETE', 'Eliminar'], ['EXPENSE_CATEGORIES_MANAGE', 'Administrar categorías']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
  { id: 'analytics', title: 'Analítica propia', description: 'Visitas, consultas, interacciones y configuración de privacidad.', accessPermission: Permission.ANALYTICS_VIEW, permissions: [['ANALYTICS_VIEW', 'Ver'], ['ANALYTICS_HEATMAP_VIEW', 'Ver interacciones'], ['ANALYTICS_SETTINGS_MANAGE', 'Configurar privacidad'], ['ANALYTICS_EXPORT', 'Exportar']].map(([key, label]) => ({ permission: Permission[key as keyof typeof Permission], label })) },
];
